### ISSUE TITLE
Panic in write_uniform_buffers

### ISSUE THREAD

**Issue by sapir** [bevyengine/bevy#1011]
**Bevy version**

1398d783

**Operating system & version**

Ubuntu 20.10 without wayland

**What you did**

I'm not really sure. My code used to work with older git versions. I tried git bisect and I think it's since b5ffab7135fbf6e7b50b1733d2d58e8a21d9b65e. (Edit: 6b004f7d seems to work fine.) I haven't investigated yet what in my code triggers it. I'm sort of hoping it'll be obvious to someone familiar with the relevant code on bevy's side :)

**What you expected to happen**

There shouldn't be a panic.

**What actually happened**

There's a panic before my game really starts, I think in or before the first few frames. Sometimes my game manages to start up properly and then it's fine until I hit a second panic which I'll open a separate issue for.

**Additional information**

Stack trace follows:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /.../dev/bevy/bevy/crates/bevy_render/src/render_graph/nodes/render_resources_node.rs:270:64
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:50:5
   3: bevy_render::render_graph::nodes::render_resources_node::UniformBufferArrays<I,T>::write_uniform_buffers
   4: bevy_render::render_graph::nodes::render_resources_node::render_resources_node_system::{{closure}}
             at /.../dev/bevy/bevy/crates/bevy_render/src/render_graph/nodes/render_resources_node.rs:508:25
   5: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::write_mapped_buffer
             at /.../dev/bevy/bevy/crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:545:9
   6: bevy_render::render_graph::nodes::render_resources_node::render_resources_node_system
             at /.../dev/bevy/bevy/crates/bevy_render/src/render_graph/nodes/render_resources_node.rs:495:9
   7: core::ops::function::FnMut::call_mut
             at /.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:150:5
   8: <Func as bevy_ecs::system::into_system::IntoSystem<(A,B,C,D),bevy_ecs::system::into_system::FuncSystem<Input,Return>>>::system::{{closure}}
             at /.../dev/bevy/bevy/crates/bevy_ecs/src/system/into_system.rs:180:38
   9: bevy_ecs::schedule::schedule::Schedule::run
  10: bevy_render::render_graph::system::render_graph_schedule_executor_system
             at /.../dev/bevy/bevy/crates/bevy_render/src/render_graph/system.rs:18:9
  11: bevy_ecs::schedule::parallel_executor::ExecutorStage::run
             at /.../dev/bevy/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:506:17
  12: bevy_ecs::schedule::parallel_executor::ParallelExecutor::run
             at /.../dev/bevy/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:73:17
  13: bevy_winit::winit_runner::{{closure}}
             at /.../dev/bevy/bevy/crates/bevy_winit/src/lib.rs:360:17
  14: winit::platform_impl::platform::sticky_exit_callback
             at /.../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:726:5
  15: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /.../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:295:17
  16: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /.../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:386:9
  17: winit::platform_impl::platform::EventLoop<T>::run
             at /.../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:642:56
  18: winit::event_loop::EventLoop<T>::run
             at /.../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154:9
  19: bevy_winit::run
             at /.../dev/bevy/bevy/crates/bevy_winit/src/lib.rs:120:5
  20: bevy_winit::winit_runner
             at /.../dev/bevy/bevy/crates/bevy_winit/src/lib.rs:368:9
  21: core::ops::function::Fn::call
             at /.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  22: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1332:9
  23: bevy_app::app::App::run
             at /.../dev/bevy/bevy/crates/bevy_app/src/app.rs:93:9
  24: bevy_app::app_builder::AppBuilder::run
             at /.../dev/bevy/bevy/crates/bevy_app/src/app_builder.rs:44:9
  25: game::main
             at ./src/main.rs:228:5
  26: core::ops::function::FnOnce::call_once
             at /.../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sapir** [comment]
This seems not to happen with current git, 509b138e. I'm getting a different panic instead, which I may open a separate issue for.

**Comment by alice-i-cecile** [comment]
I'm going to close this out now then <3
