### ISSUE TITLE
Panic after spawning a SpriteSheetBundle child

### ISSUE THREAD

**Issue by sapir** [bevyengine/bevy#1012]
**Bevy version**

1398d783

**Operating system & version**

Ubuntu 20.10

**What you did**

Spawned some SpriteSheetBundles as children of an entity that has GlobalTransform and Transform components (but no rendered component.)

There's something else going on here, because I've also tried doing this separately from my game, and then the panic doesn't happen.

But if I comment out the spawn call, the panic doesn't happen.

My code used to work with a previous git revision. 6b004f7d seems to work fine.

**What you expected to happen**

There shouldn't be a panic.

**What actually happened**

There's a panic, I think before the new entities are rendered.

**Additional information**

Stack trace follows:
```
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Dec 06 14:17:31.173  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Dec 06 14:17:31.173  WARN wgpu_core::device: Shader module will not be validated
Dec 06 14:17:31.333  WARN wgpu_core::device: Failed to parse shader SPIR-V code: UnsupportedBuiltIn(4)
Dec 06 14:17:31.333  WARN wgpu_core::device: Shader module will not be validated

thread 'main' panicked at 'Attribute Vertex_Position is required by shader, but not supplied by mesh. Either remove the attribute from the shader or supply the attribute (Vertex_Position) to the mesh.', .../dev/bevy/bevy/crates/bevy_render/src/pipeline/pipeline_compiler.rs:223:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:435:5
   2: bevy_render::pipeline::pipeline_compiler::PipelineCompiler::compile_pipeline
             at .../dev/bevy/bevy/crates/bevy_render/src/pipeline/pipeline_compiler.rs:223:17
   3: bevy_render::draw::DrawContext::set_pipeline
             at .../dev/bevy/bevy/crates/bevy_render/src/draw.rs:162:13
   4: bevy_render::pipeline::render_pipelines::draw_render_pipelines_system
             at .../dev/bevy/bevy/crates/bevy_render/src/pipeline/render_pipelines.rs:139:13
   5: core::ops::function::FnMut::call_mut
             at .../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:150:5
   6: <Func as bevy_ecs::system::into_system::IntoSystem<(A,B,C,D,E),bevy_ecs::system::into_system::FuncSystem<Input,Return>>>::system::{{closure}}
             at .../dev/bevy/bevy/crates/bevy_ecs/src/system/into_system.rs:180:38
   7: bevy_ecs::schedule::parallel_executor::ExecutorStage::run_systems::{{closure}}::{{closure}}
             at .../dev/bevy/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:407:29
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at .../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   9: async_executor::Executor::spawn::{{closure}}
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:138:13
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at .../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  11: async_task::raw::RawTask<F,T,S>::run
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  12: async_executor::Executor::try_tick
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:175:17
  13: bevy_tasks::task_pool::TaskPool::scope
             at .../dev/bevy/bevy/crates/bevy_tasks/src/task_pool.rs:212:17
  14: bevy_ecs::schedule::parallel_executor::ExecutorStage::run_systems
             at .../dev/bevy/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:338:9
  15: bevy_ecs::schedule::parallel_executor::ExecutorStage::run
             at .../dev/bevy/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:478:13
  16: bevy_ecs::schedule::parallel_executor::ParallelExecutor::run
             at .../dev/bevy/bevy/crates/bevy_ecs/src/schedule/parallel_executor.rs:73:17
  17: bevy_winit::winit_runner::{{closure}}
             at .../dev/bevy/bevy/crates/bevy_winit/src/lib.rs:360:17
  18: winit::platform_impl::platform::sticky_exit_callback
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:726:5
  19: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:295:17
  20: winit::platform_impl::platform::x11::EventLoop<T>::run
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:386:9
  21: winit::platform_impl::platform::EventLoop<T>::run
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:642:56
  22: winit::event_loop::EventLoop<T>::run
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154:9
  23: bevy_winit::run
             at .../dev/bevy/bevy/crates/bevy_winit/src/lib.rs:120:5
  24: bevy_winit::winit_runner
             at .../dev/bevy/bevy/crates/bevy_winit/src/lib.rs:368:9
  25: core::ops::function::Fn::call
             at .../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  26: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at .../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1332:9
  27: bevy_app::app::App::run
             at .../dev/bevy/bevy/crates/bevy_app/src/app.rs:93:9
  28: bevy_app::app_builder::AppBuilder::run
             at .../dev/bevy/bevy/crates/bevy_app/src/app_builder.rs:44:9
  29: game::main
             at ./src/main.rs:228:5
  30: core::ops::function::FnOnce::call_once
             at .../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sapir** [comment]
This seems not to happen with current git, 509b138.

I haven't tested it with the same app code though.
