### ISSUE TITLE
ERROR wgpu_core::device: surface configuration failed

### ISSUE THREAD

**Issue by szpolny** [bevyengine/bevy#10149]
## Bevy version

bevy = "0.11.3"

## Relevant system information

cargo 1.73.0 (9c4383fb5 2023-08-26)
Fedora Linux 38 (Workstation Edition) x86_64 
Kernel: 6.5.6-200.fc38.x86_64 

```
`AdapterInfo { name: "NV136", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }`
```

## What you did

```
# Cargo.toml

[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.11.3"

```

```rust
// main.rs

use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
}

```

## What went wrong

Black window, then crush after few seconds 

## Additional information

logs
```
❯ cargo run
    Finished dev [optimized + debuginfo] target(s) in 0.14s
     Running `target/debug/logic_farm_rougelike`
2023-10-16T21:44:13.914990Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-10-16T21:44:13.915114Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-10-16T21:44:40.828510Z  INFO bevy_render::renderer: AdapterInfo { name: "NV136", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2023-10-16T21:44:40.845305Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
2023-10-16T21:44:40.855706Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 38 Fedora Linux", kernel: "6.5.6-200.fc38.x86_64", cpu: "AMD Ryzen 5 3600 6-Core Processor", core_count: "6", memory: "15.5 GiB" }
2023-10-16T21:44:40.864734Z ERROR wgpu_core::device: surface configuration failed: incompatible window kind    
thread 'main' panicked at /home/szymon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:18:
Error in Surface::configure: Validation Error

Caused by:
    Invalid surface

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (5)' panicked at /home/szymon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.11.3/src/pipelined_rendering.rs:143:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by alice-i-cecile** [comment]
Do the `wgpu` examples run for you? This is likely an upstream problem (although it may be fixed already).

**Comment by szpolny** [comment]
@alice-i-cecile which one?

**Comment by szpolny** [comment]
Vulkan was not installed, thank you.
