### ISSUE TITLE
bevy_render-0.11.3 infinite viewport camera panic

### ISSUE THREAD

**Issue by VergilUa** [bevyengine/bevy#10216]
## Bevy version
0.11.3 installed via Cargo, features - dynamic_linking, bevy_winit
rustc 1.73.0 (cc66ad468 2023-10-03)

## What you did

Toggling bevy_pls_editor editor via "e" key press.

## What went wrong

It seems like adding a different camera by the editor causes a panic for some reason. 
Probably because viewport camera has infite value for a frame. 
Perhaps add some kind of safety instead if viewport values are invalid (or don't render at all)?

## Stacktrace
```ignore
thread 'Compute Task Pool (13)' panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\arith.rs:109:1:
attempt to add with overflow
stack backtrace:
   0:     0x7ffd719f738a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c22c4185b55f04
   1:     0x7ffd71a2bb5b - core::fmt::write::h8a7f6edbcadee319
   2:     0x7ffd719ecc51 - <std::io::IoSlice as core::fmt::Debug>::fmt::h0ee392ef0f96e369
   3:     0x7ffd719f710a - std::sys_common::backtrace::lock::h134eeaadb35136bd
   4:     0x7ffd719fa8ca - std::panicking::default_hook::h81d7caaa8c7a40b4
   5:     0x7ffd719fa538 - std::panicking::default_hook::h81d7caaa8c7a40b4
   6:     0x7ffd719fb03e - std::panicking::rust_panic_with_hook::h8ac326f3b5470b08
   7:     0x7ffd719faeea - <std::panicking::begin_panic_handler::StrPanicPayload as core::panic::BoxMeUp>::get::h353ca2f9698f73b3
   8:     0x7ffd719f8049 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c22c4185b55f04
   9:     0x7ffd719fac30 - rust_begin_unwind
  10:     0x7ffd71a60d85 - core::panicking::panic_fmt::hb3ce2a19a4187054
  11:     0x7ffd71a60e32 - core::panicking::panic::h5206d844b81664c1
  12:     0x7ffd6634cc54 - bevy_render::camera::camera::extract_cameras
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\camera\camera.rs:688
  13:     0x7ffd66331b43 - core::ops::function::FnMut::call_mut
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:166
  14:     0x7ffd66331b43 - core::ops::function::impls::impl$3::call_mut
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:294
  15:     0x7ffd66331b43 - bevy_ecs::system::function_system::impl$15::run::call_inner
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\system\function_system.rs:622
  16:     0x7ffd66331b43 - bevy_ecs::system::function_system::impl$15::run
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\system\function_system.rs:625
  17:     0x7ffd66331b43 - bevy_ecs::system::function_system::impl$6::run_unsafe<void (*)(bevy_ecs::system::commands::Commands,bevy_render::extract_param::Extract<bevy_ecs::system::query::Query<tuple$<bevy_ecs::entity::Entity,ref$<bevy_render::camera::camera::Camera>,ref$<bevy_rend
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\system\function_system.rs:460
  18:     0x7ffd67196f61 - core::panic::unwind_safe::impl$26::poll
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:296
  19:     0x7ffd67196f61 - futures_lite::future::impl$14::poll::closure$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  20:     0x7ffd67196f61 - core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::impl$3::spawn_system
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:271
  21:     0x7ffd6719ed3f - futures_lite::future::impl$14::poll
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  22:     0x7ffd6719ed3f - async_executor::impl$5::spawn::async_block$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:152
  23:     0x7ffd6719ed3f - async_task::raw::RawTask<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core::panic::unwind
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.4.1\src\raw.rs:563
  24:     0x7ffd671abba4 - futures_lite::future::impl$12::poll
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:529
  25:     0x7ffd671abba4 - async_executor::impl$5::run::async_fn$0::async_block$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:255
  26:     0x7ffd671abba4 - async_executor::impl$19::with::impl$0::set::async_fn$0::closure$3
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:943
  27:     0x7ffd671abba4 - futures_lite::future::impl$6::poll
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:246
  28:     0x7ffd671abba4 - async_executor::impl$19::with::impl$0::set::async_fn$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:945
  29:     0x7ffd671abba4 - async_executor::impl$5::run::async_fn$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_chan
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:258
  30:     0x7ffd671aa1db - futures_lite::future::block_on::closure$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:89
  31:     0x7ffd671aa1db - std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\thread\local.rs:270
  32:     0x7ffd671aa1db - std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\thread\local.rs:246
  33:     0x7ffd671aa1db - futures_lite::future::block_on<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,enum2$<async_executor::impl$5::run::async_fn_env$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks:
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:79
  34:     0x7ffd671a962a - bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:171
  35:     0x7ffd671a962a - std::panicking::try::do_call
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:502
  36:     0x7ffd671a962a - std::panicking::try
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:466
  37:     0x7ffd671a962a - std::panic::catch_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panic.rs:142
  38:     0x7ffd671a962a - bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:165
  39:     0x7ffd671a962a - std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\thread\local.rs:270
  40:     0x7ffd671a962a - std::thread::local::LocalKey<async_executor::LocalExecutor>::with
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\thread\local.rs:246
  41:     0x7ffd671a962a - bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
                               at C:\Users\UserName\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:158
  42:     0x7ffd671a962a - std::sys_common::backtrace::__rust_begin_short_backtrace<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure_env$0,tuple$<> >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\sys_common\backtrace.rs:154
  43:     0x7ffd671ae648 - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\thread\mod.rs:529
  44:     0x7ffd671ae648 - core::panic::unwind_safe::impl$23::call_once
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\panic\unwind_safe.rs:271
  45:     0x7ffd671ae648 - std::panicking::try::do_call
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:502
  46:     0x7ffd671ae648 - std::panicking::try
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panicking.rs:466
  47:     0x7ffd671ae648 - std::panic::catch_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\panic.rs:142
  48:     0x7ffd671ae648 - std::thread::impl$0::spawn_unchecked_::closure$1
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\std\src\thread\mod.rs:528
  49:     0x7ffd671ae648 - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure_env$0,tuple$<> >,tuple$<> >
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33\library\core\src\ops\function.rs:250
  50:     0x7ffd71a0e3ec - std::sys::windows::thread::Thread::new::h75a9ed52a5af2748
  51:     0x7ffe10a9257d - BaseThreadInitThunk
  52:     0x7ffe1214aa78 - RtlUserThreadStart
Encountered a panic in system `bevy_render::camera::camera::extract_cameras`!

```

**Comment by poperigby** [comment]
I'm also encountering this issue. Any way I can help troubleshoot?

**Comment by rlidwka** [comment]
@poperigby, does it still happen on 0.12?

**Comment by poperigby** [comment]
Yes, but not every single time.

Here's my backtrace:

```
thread 'Compute Task Pool (1)' panicked at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/arith.rs:109:1:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: bevy_render::camera::camera::extract_cameras
   4: core::ops::function::FnMut::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:166:5
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:294:13
   6: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2) .> Out>>::run::call_inner
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.0/src/system/function_system.rs:642:21
   7: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2) .> Out>>::run
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.0/src/system/function_system.rs:645:17
   8: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.0/src/system/function_system.rs:485:19
   9: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_system_task::{{closure}}::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.0/src/schedule/executor/multi_threaded.rs:505:26
  10: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  12: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  13: std::panicking::try
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  14: std::panic::catch_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  15: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_system_task::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.12.0/src/schedule/executor/multi_threaded.rs:500:23
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:296:9
  17: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panic/unwind_safe.rs:271:9
  19: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  20: std::panicking::try
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  21: std::panic::catch_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  22: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  23: async_executor::Executor::spawn::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.7.2/src/lib.rs:158:20
  24: async_task::raw::RawTask<F,T,S,M>::run
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.5.0/src/raw.rs:568:17
  25: async_task::runnable::Runnable<M>::run
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.5.0/src/runnable.rs:784:18
  26: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.7.2/src/lib.rs:250:21
  27: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.0.1/src/future.rs:449:33
  28: async_executor::Executor::run::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.7.2/src/lib.rs:257:32
  29: futures_lite::future::block_on::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:89:27
  30: std::thread::local::LocalKey<T>::try_with
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
  31: std::thread::local::LocalKey<T>::with
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
  32: futures_lite::future::block_on
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:79:11
  33: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.0/src/task_pool.rs:180:37
  34: std::panicking::try::do_call
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  35: std::panicking::try
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  36: std::panic::catch_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  37: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.0/src/task_pool.rs:174:43
  38: std::thread::local::LocalKey<T>::try_with
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:270:16
  39: std::thread::local::LocalKey<T>::with
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/thread/local.rs:246:9
  40: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at /home/cassidy/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.12.0/src/task_pool.rs:167:50
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::camera::camera::extract_cameras`!
warning: queue 0x55f99cdd6f70 destroyed while proxies still attached:
  wl_buffer@46 still attached
  wl_shm_pool@48 still attached
  xdg_wm_base@24 still attached
  zwp_text_input_manager_v3@15 still attached
  wl_output@14 still attached
  xdg_activation_v1@13 still attached
  wl_subcompositor@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  wl_seat@9 still attached
  wl_shm@8 still attached
  wp_fractional_scale_manager_v1@7 still attached
  wp_viewporter@6 still attached
  zxdg_decoration_manager_v1@5 still attached
  wl_compositor@4 still attached
  wl_registry@2 still attached
  ```

**Comment by rlidwka** [comment]
> Here's my project: https://codeberg.org/PopeRigby/platformer

Okay, I've compiled and ran it, seems to work fine for me.

How do I reproduce the issue?

**Comment by poperigby** [comment]
I'm honestly not quite sure. It doesn't even happen every time. I'll launch it multiple times and it crashes every time, but then I'll open it another time and it works fine. It's triggered by pressing `e` to open `bevy_editor_pls`.

The weirdest thing is, this only started happening recently, and I didn't update my dependencies.

It also says this when it launches:

```
2023-11-22T22:36:58.235589Z  WARN bevy_editor_pls_default_windows::cameras: editor viewport size is infinite
```

**Comment by VergilUa** [comment]
Late to the party, but, it happens when second camera is created in runtime. Its framerate dependent. 
High performance rigs most likely will hit it more easily.

Two workarounds I've found so far to avoid this - both involve avoiding to create second camera during game loop.

1. Boot bevy_editor_pls in second window mode at the start of the app. Its much more convenient to just have it open automatically to save you some time. Plus, camera gets created at the boot as well, preventing this issue. 
If your setup allows it, you can even move it to the second monitor like so:
```
fn setup_editor_window() -> EditorPlugin {
    EditorPlugin::
    in_new_window(Default::default(), Window {
        mode: WindowMode::Windowed,
        position: WindowPosition::Centered(MonitorSelection::Index(1)),
        ..Default::default()
    })
}
```

2. Use button at the top of the window to open the editor. For some reason this doesn't trigger camera panic either. Potentially due to when and where camera creation happens.
