### ISSUE TITLE
Bevy still crashes when mesh attributes are different lengths

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#10267]
## Bevy version

main

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.5.1 ", kernel: "22.6.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

Add one more UV in the `generate_custom_mesh` example and `cargo run --example generate_custom_mesh`.

```diff
diff --git a/examples/3d/generate_custom_mesh.rs b/examples/3d/generate_custom_mesh.rs
index a4aa02502..51b0fae24 100644
--- a/examples/3d/generate_custom_mesh.rs
+++ b/examples/3d/generate_custom_mesh.rs
@@ -181,6 +181,8 @@ fn create_cube_mesh() -> Mesh {
             [0.0, 0.45], [0.0, 0.2], [1.0, 0.2], [1.0, 0.45],
             // Assigning the UV coords for the forward side.
             [0.0, 0.45], [0.0, 0.2], [1.0, 0.2], [1.0, 0.45],
+            // extra
+            [0.0, 0.0]
         ],
     );

```

## What went wrong

Warning is emitted, but Bevy still crashes.

The warning seems to imply that Bevy should not be crashing.

```
2023-10-25T20:12:41.865953Z  WARN bevy_render::mesh::mesh: MeshVertexAttributeId(2) has a different vertex count (28) than other attributes (24) in this mesh, all attributes will be truncated to match the smallest.
```
```
thread 'Compute Task Pool (0)' panicked at crates/bevy_render/src/mesh/mesh/mod.rs:370:46:
range end index 800 out of range for slice of length 768
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_render::mesh::mesh::Mesh>`!
thread 'Compute Task Pool (3)' panicked at crates/bevy_render/src/pipelined_rendering.rs:145:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Additional information

I attempted to bisect this, but I see the same crash even with #9699 where the warning was introduced.

First noticed here: <https://github.com/bevyengine/bevy/pull/10259#pullrequestreview-1698045156>.

**Comment by robojeb** [comment]
I think the issue is here in `get_vertex_buffer_data()`:

```rust
for attribute_data in self.attributes.values().take(vertex_count) { // <<<<
 // <snip>
```

This limits the number of attribute buffers that will be iterated over, not the number of values in the attribute itself. 
The inner loop over chunks of data from the attribute buffer should have the `.take(vertex_count)`. 

```diff
- for (vertex_index, attribute_bytes) in
-                attributes_bytes.chunks_exact(attribute_size).enumerate()
+ for (vertex_index, attribute_bytes) in
+                attributes_bytes.chunks_exact(attribute_size).take(vertex_count).enumerate()
```

Quick testing shows that moving the `.take()` into the inner loop prevents the crash.
