### ISSUE TITLE
Asahi Linux: cannot run due to DownlevelFlags(VERTEX_STORAGE) requirement

### ISSUE THREAD

**Issue by inodentry** [bevyengine/bevy#10277]
## Bevy version

commit bfca4384cc34e0314497e809a7e02ae3b8001876

## \[Optional\] Relevant system information

Hardware: Apple M1 Pro, 14in MacBook Pro
OS: Asahi Linux
Mesa: 23.3.0~asahipre20230821^post1-1.fc39

```
AdapterInfo { name: "Apple M1 Pro (G13S C0)", vendor: 65541, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
SystemInfo { os: "Linux 39 Fedora Linux Asahi Remix", kernel: "6.5.6-403.asahi.fc39.aarch64+16k", cpu: "Icestorm-M1-Pro", core_count: "10", memory: "30.9 GiB" }
```

## What you did

Run any Bevy 2d or 3d example:

```
cargo r --features wayland --example bevymark
```

## What went wrong

```
2023-10-27T00:03:25.672781Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at /home/iyes/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.1/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `mesh2d_layout`
    Binding 0 entry is invalid
    Downlevel flags DownlevelFlags(VERTEX_STORAGE) are required but not supported on the device.
This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
```

## Additional information

As seen in the error above, the problem is with `mesh2d_layout`. It wants a `VERTEX_STORAGE` feature that is not yet available in the Asahi GLES drivers.

2D used to work on Asahi in Bevy 0.11. This is a regression.

It is not necessarily Bevy's fault here. Asahi's GPU drivers are WIP and missing many features. It will get better.

However, if Bevy has an easy workaround for this (what's the situation with WebGL2?), maybe we could apply it here, too.

**Comment by dashaomai** [comment]
yes, I meet the same problem on my aarch64 sbc.

Hardware: Embedfire LubanCat4 (aarch64, rk3588s, mali-g610)
OS: Ubuntu 22.04.3
Mesa: 23.0.5-0ubuntu1-panfork-git221210.120202c6757-j2 arm64

`AdapterInfo { name: "Mali-G610 (Panfrost)", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }`


```
2023-11-19T12:43:41.635430Z ERROR log: Handling wgpu errors as fatal by default 
thread 'main' panicked at /home/buddy/.cargo/registry/src/rsproxy.cn-0dccff568467c15b/wgpu-0.17.2/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `mesh2d_layout`
    Binding 0 entry is invalid
    Downlevel flags DownlevelFlags(VERTEX_STORAGE) are required but not supported on the device.
This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
```

**Comment by wallabra** [comment]
I'm having a similar issue. I have a simple stub project which will use Bevy for 2D visualization.

```
2023-12-14T16:30:23.199053Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-12-14T16:30:23.199536Z  INFO log: Guessed window scale factor: 1    
2023-12-14T16:30:28.058235Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD CAICOS (DRM 2.50.0 / 6.6.4-artix1-1, LLVM 16.0.6)", vendor: 65541, device: 0, device_type: Other, driver: "", driver_info: "", backend: Gl }
2023-12-14T16:30:28.943297Z ERROR log: Handling wgpu errors as fatal by default    
thread 'main' panicked at [...]/wgpu-0.17.2/src/backend/direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group_layout
      note: label = `mesh2d_layout`
    Binding 0 entry is invalid
    Downlevel flags DownlevelFlags(VERTEX_STORAGE) are required but not supported on the device.
This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.
```

**Comment by Shatur** [comment]
I have the same problem on PinePhone Pro (RK3399).

**Comment by kirisauce** [comment]
The same problem also happens on android phone when using `Backends::GL`.

Kernel: `5.10.168-android12-9-00001-g81e7418c6466-ab10486262`
Android version: 14

The error occured in [this function](https://github.com/gfx-rs/wgpu/blob/v24/wgpu-core/src/device/global.rs#L560) in `wgpu-core`, with the following arguments:
```rust
Device::create_bind_group_layout(
    Id(0,1),
    BindGroupLayoutDescriptor {
        label: Some("mesh2d_layout"),
        entries: [
            BindGroupLayoutEntry {
                binding: 0,
                visibility: ShaderStages(VERTEX | FRAGMENT),
                ty: Buffer {
                    ty: Storage { read_only: true },
                    has_dynamic_offset: false,
                    min_binding_size: Some(96),
                },
                count: None,
            }
        ]
    },
    None
)
```

I finally made it work by changing the backend to `Backends::VULKAN`.

**Comment by pomoke** [comment]
I have same problem on chromebook duet.
OS: PostmarketOS v25.04
SoC: MTK P60T
GPU: Mali-G72 MP3
Driver: Panfrost

```
thread 'main' panicked at [..]/wgpu/src/backend/wgpu_core.rs:1079:26:
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group_layout, label = 'mesh2d_layout'
    Binding 0 entry is invalid
      Downlevel flags DownlevelFlags(VERTEX_STORAGE) are required but not supported on the device.
This is not an invalid use of WebGPU: the underlying API or device does not support enough features to be a fully compliant implementation. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to work around this issue, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

Vulkan does not work either, as G72 only has non-comformant PanVK:
```

thread 'Compute Task Pool (2)' panicked at [..]/wgpu/src/backend/wgpu_core.rs:1405:18:
wgpu error: Validation Error

Caused by:
  In Device::create_buffer, label = 'general mesh slab 1 (index buffer)'
    Not enough memory left.


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted

```
