### ISSUE TITLE
Crash when spawning a gltf mesh with morph targets

### ISSUE THREAD

**Issue by 5tr1k3r** [bevyengine/bevy#10388]
## Bevy version
0.11.2

## Relevant system information
Windows 10
```
AdapterInfo { name: "NVIDIA GeForce GTX 1650", vendor: 4318, device: 8081, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "537.58", backend: Vulkan }
```

## What you did
I have a gltf model with shape keys/morph targets that I made in Blender. Previously I was spawning it as a Scene without any issues, using `#Scene0` syntax. Yesterday I've tried spawning it as a Mesh, using `#Mesh0/Primitive0` syntax. It results in a crash.

### What was I expecting?
Expected it to work the same way it worked when it was just a Scene. Other models (that do not have shape keys/morph targets) don't crash when they are spawned as Meshes.

### What actually happened?
```
2023-11-05T13:35:46.833577Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread '<unnamed>' panicked at C:\Users\x\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:3019:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 2, Vulkan)>`
    In a draw command, indexed:true indirect:false
      note: render pipeline = `pbr_prepass_pipeline`
    The pipeline layout, associated with the current render pipeline, contains a bind group layout at index 2 which is incompatible with the bind group layout associated with the bind group at 2


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in exclusive system `bevy_render::renderer::render_system`!
thread 'Compute Task Pool (3)' panicked at C:\Users\x\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.2\src\pipelined_rendering.rs:143:45:
called `Result::unwrap()` on an `Err` value: RecvError
error: process didn't exit successfully: `D:\dev\bevy_workspace\target\debug\morph_mre.exe` (exit code: 101)
```

### Minimal reproducible example
https://github.com/5tr1k3r/morph_mre
Run with `cargo run --features bevy/dynamic_linking`

### Theories about what might be going wrong
Spawning a Scene results in four entities in a hierarchy. When I spawn a mesh without morph targets as a Scene, most of the time three higher level entities (parents) are useless to me: I just want the innermost entity (mesh).
When I spawn a mesh with morph targets, though, the direct parent of the innermost mesh entity seems to be involved as well: it contains `MorphWeights` component:

![image](https://github.com/bevyengine/bevy/assets/11004850/737463ce-6b53-4eaf-a3e3-5ad6d599bc68)

When I try spawning it as just a Mesh, it results in one entity only, which is why I think that's directly related to the crash. But I wasn't able to find any workarounds.

### Suggestion
I think having just `MeshMorphWeights` on the innermost mesh entity should be supported, without needing to have the parent entity with `MorphWeights`.

**Comment by cart** [comment]
Punting to 0.13, given that this isn't a regression and the fix might be a bit involved. I do suspect that this relates to hierarchy + setup, as @5tr1k3r hypothesized. Based on my understanding, morph targets were built to work within the context of the full scene. We might need to rethink some things.
