### ISSUE TITLE
Fix `texture_atlas` example

### ISSUE THREAD

**Issue by feelingsonice** [bevyengine/bevy#10899]
## Bevy version

[v0.12.1](https://github.com/bevyengine/bevy/releases/tag/v0.12.1)

## What you did

Run `cargo run --example texture_atlas`

## What went wrong

Panic with error message:

```text
thread 'IO Task Pool (0)' panicked at crates/bevy_asset/src/io/mod.rs:260:10:
asset paths must have extension
```

## Additional information

Backtrace:

```text
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:168:5
   3: core::panicking::panic_str
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:152:5
   4: core::option::expect_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1988:5
   5: core::option::Option<T>::expect
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:898:21
   6: bevy_asset::io::get_meta_path
             at ./crates/bevy_asset/src/io/mod.rs:258:25
   7: bevy_asset::io::file::file_asset::<impl bevy_asset::io::AssetReader for bevy_asset::io::file::FileAssetReader>::read_meta
             at ./crates/bevy_asset/src/io/file/file_asset.rs:40:25
   8: bevy_asset::io::AssetReader::read_meta_bytes::{{closure}}
             at ./crates/bevy_asset/src/io/mod.rs:82:35
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  10: bevy_asset::server::AssetServer::get_meta_loader_and_reader::{{closure}}
             at ./crates/bevy_asset/src/server/mod.rs:863:67
  11: bevy_asset::server::AssetServer::load_internal::{{closure}}
             at ./crates/bevy_asset/src/server/mod.rs:404:14
  12: bevy_asset::server::AssetServer::load_untyped_async::{{closure}}
             at ./crates/bevy_asset/src/server/mod.rs:318:53
  13: bevy_asset::server::AssetServer::load_folder_internal::load_folder::{{closure}}
             at ./crates/bevy_asset/src/server/mod.rs:632:73
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  15: bevy_asset::server::AssetServer::load_folder_internal::load_folder::{{closure}}
             at ./crates/bevy_asset/src/server/mod.rs:628:34
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  17: bevy_asset::server::AssetServer::load_folder_internal::{{closure}}
             at ./crates/bevy_asset/src/server/mod.rs:675:98
  18: async_executor::Executor::spawn::{{closure}}
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  19: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.5.0/src/raw.rs:561:21
  20: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  21: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panic/unwind_safe.rs:271:9
  22: std::panicking::try::do_call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  23: ___rust_try
  24: std::panicking::try
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  25: std::panic::catch_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  26: async_task::raw::RawTask<F,T,S,M>::run
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.5.0/src/raw.rs:560:23
  27: async_task::runnable::Runnable<M>::run
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.5.0/src/runnable.rs:784:18
  28: async_executor::Executor::run::{{closure}}::{{closure}}
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:254:21
  29: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.1.0/src/future.rs:449:33
  30: async_executor::Executor::run::{{closure}}
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  31: futures_lite::future::block_on::{{closure}}
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.1.0/src/future.rs:99:19
  32: std::thread::local::LocalKey<T>::try_with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:270:16
  33: std::thread::local::LocalKey<T>::with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:246:9
  34: futures_lite::future::block_on
             at /Users/bli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.1.0/src/future.rs:78:5
  35: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:180:37
  36: std::panicking::try::do_call
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:504:40
  37: ___rust_try
  38: std::panicking::try
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:468:19
  39: std::panic::catch_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panic.rs:142:14
  40: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:174:43
  41: std::thread::local::LocalKey<T>::try_with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:270:16
  42: std::thread::local::LocalKey<T>::with
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/thread/local.rs:246:9
  43: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:167:25
 ```

**Comment by andristarr** [comment]
Logs errors but doesnt panic for me, I think this is now a different error?

**Comment by Oleksii-Kshenskyi** [comment]
Hey guys, just wanted to let you know that I checked this on both release and debug, branches main, 0.13.0 and 0.13.1, and it never panics anywhere.
@alice-i-cecile can this issue be closed maybe? It doesn't seem to be reproducible anymore.
@feelingsonice can you reproduce the issue with the recent versions of Bevy?
