### ISSUE TITLE
XError `BadWindow (invalid Window parameter)` when closing windows at seemingly random

### ISSUE THREAD

**Issue by Mampfinator** [bevyengine/bevy#11150]
## Bevy version
0.12.1

## Relevant system information
OS: Pop!_OS 22.04 (6.6.6-76060606-generic)
```
AdapterInfo { name: "llvmpipe (LLVM 15.0.7, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.3.0-1pop0~1702935939~22.04~67e417a (LLVM 15.0.7)", backend: Vulkan }
```
## What you did
I was playing around with multiple windows, essentially like so:
```rs
use bevy::prelude::*;

#[derive(Resource)]
struct WindowCounter(pub usize);

fn main() {
    App::new()
        .insert_resource(WindowCounter(1))
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                title: "Window #0".into(),
                ..Default::default()
            }),
            ..Default::default()
        }))
        .add_systems(Update, open_new_window_on_keypress)
        .run();
}

fn open_new_window_on_keypress(
    input: Res<Input<KeyCode>>,
    mut commands: Commands,
    mut windows: ResMut<WindowCounter>,
) {
    if input.just_released(KeyCode::Space) {
        let name = format!("Window #{}", windows.0);

        commands.spawn((
            Window {
                title: name.clone(),
                ..Default::default()
            },
            Name::new(name),
        ));

        windows.0 += 1;
    }
}

```

## What went wrong
Upon closing any window (via Super + Q/Alt + F4 or the close button), there's a pretty small chance that the entire application crashes:
```ignore
2023-12-30T19:14:40.903590Z  INFO bevy_winit::system: Creating new window "Window #2" (1v1)
2023-12-30T19:14:40.903690Z  INFO log: Guessed window scale factor: 1    
2023-12-30T19:14:41.366602Z  INFO bevy_winit::system: Closing window 1v1
2023-12-30T19:14:41.367636Z  WARN bevy_winit: Window 1v1 is missing `Window` component, skipping event Focused(true)
2023-12-30T19:14:41.367732Z  WARN bevy_winit: Window 1v1 is missing `Window` component, skipping event ModifiersChanged(LOGO)
2023-12-30T19:14:41.367743Z  WARN bevy_winit: Window 1v1 is missing `Window` component, skipping event CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: PhysicalPosition { x: 933.0, y: 202.0 }, modifiers: LOGO }
2023-12-30T19:14:41.368243Z  WARN bevy_winit: Window 1v1 is missing `Window` component, skipping event KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 16, state: Pressed, virtual_keycode: Some(Q), modifiers: LOGO }, is_synthetic: true }
2023-12-30T19:14:41.368288Z  WARN bevy_winit: Window 1v1 is missing `Window` component, skipping event KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 125, state: Pressed, virtual_keycode: None, modifiers: LOGO }, is_synthetic: true }
2023-12-30T19:14:41.369414Z  WARN bevy_winit: Window 1v1 is missing `Window` component, skipping event Destroyed
2023-12-30T19:14:41.927830Z  INFO bevy_winit::system: Creating new window "Window #3" (1v2)
2023-12-30T19:14:41.927959Z  INFO log: Guessed window scale factor: 1    
2023-12-30T19:14:42.278620Z  INFO bevy_winit::system: Closing window 1v2
2023-12-30T19:14:42.289309Z ERROR log: X11 error: XError {
    description: "BadWindow (invalid Window parameter)",
    error_code: 3,
    request_code: 148,
    minor_code: 1,
}    
thread 'main' panicked at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/event_processor.rs:936:30:
Failed to focus input context: XError { description: "BadWindow (invalid Window parameter)", error_code: 3, request_code: 148, minor_code: 1 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information
I'm not familiar enough with windowing in general, `winit` or how `bevy_winit` uses it to track down where exactly the error originates from, but I ran a handful of the `winit` examples I deemed relevant and didn't encounter any issues there, so I'm bringing it up here for now.

**Comment by AxiomaticSemantics** [comment]
I'm pretty sure I ran into this once, but my issue was on main with updated wgpu and winit. It happened once and hasn't happened again, if I manage to reproduce it I will try to add some details here or create a new issue.

**Comment by AxiomaticSemantics** [comment]
`2023-12-31T00:14:46.257796Z ERROR log: X11 error: XError {
    description: "BadWindow (invalid Window parameter)",
    error_code: 3,
    request_code: 148,
    minor_code: 1,
}`

just hit it again on up to date main, confirmed to be the same error as above, in my case it's during a normally clean shutdown where I'm sending an exit event after transitioning to my `Game::Exit` `AppState`.

**Comment by cloud303-cholden** [comment]
I'm on Pop!_OS 22.04 (6.5.6-76060506-generic) and I wasn't able to reproduce this. I tried your code with and without tiling enabled, and opened and closed ~50 windows a few times. Here's the error location in `winit` ([link](https://github.com/rust-windowing/winit/blob/2ebbfab6a47f93f76841553dcb3cc53683e4955c/src/platform_impl/linux/x11/event_processor.rs#L936)) and the method that returns the result ([link](https://github.com/rust-windowing/winit/blob/c55a2c779b5521c24121515fbc969718fb704cd3/src/platform_impl/linux/x11/ime/mod.rs#L196)). Did some digging and looks like this is the relevant X11 doc: [link](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#Input_Focus_Events). Can you get the error with a backtrace? That might be helpful.

**Comment by Mampfinator** [comment]
I did some digging in the meantime with a standalone `winit` program to see if I could recreate the issue that way in order to single out `winit` as a cause. I haven't been able to reproduce the issue with the most barebones program I could set up (see below). 
I will admit however that `bevy_winit` and advanced `winit` usage go a little over my head, so if somebody else has a more sophisticated (potentially closer to Bevy's use) idea for a test program, I'd be more than happy to test that and report my findings.
<details>
    <summary>winit app used for testing</summary>

Using `winit`  0.28.7 (same version as Bevy 0.12.1).
I opened around 100 windows in 4 different test runs and haven't encountered the crash once, while the average windows I need to close with Bevy in order to crash seems to be just below 10.

```rs
use std::collections::HashMap;
use winit::{window::{WindowBuilder, WindowId, Window}, dpi::LogicalSize, event_loop::{EventLoopWindowTarget, EventLoop}, event::{Event, WindowEvent, ElementState, KeyboardInput}};

static mut WINDOWS: i32 = 1;

fn spawn_window<T>(wt: &EventLoopWindowTarget<T>, windows: &mut HashMap<WindowId, Window>) {
    let window_no = unsafe { WINDOWS };
    
    let builder = WindowBuilder::new()
        .with_title(format!("{}", window_no))
        .with_inner_size(LogicalSize::new(1280.0_f32, 720.0_f32))
        .with_visible(true);

    println!("Opening window #{window_no}.");

    unsafe {
        WINDOWS += 1;
    }

    let window = builder.build(wt).unwrap();
    let id = window.id();

    windows.insert(id, window);
}

fn main() {
    let mut windows = HashMap::new();
    let event_loop = EventLoop::new();
    
    spawn_window(&event_loop, &mut windows);

    event_loop.run(move |event: Event<()>, elwt, flow| {
        if let Event::WindowEvent { window_id, event } = event {
            match event {
                WindowEvent::CloseRequested => {
                    println!("Closing window with ID {window_id:?}");

                    // drop the window here
                    windows.remove(&window_id);

                    if windows.is_empty() {
                        flow.set_exit();
                    }
                },
                WindowEvent::KeyboardInput { input: KeyboardInput { scancode, state: ElementState::Released, .. }, .. } => {
                    // space scancode on my machine; may need to adjust
                    if scancode == 57 {
                        println!("Spawning window.");
                        spawn_window(elwt, &mut windows);
                    }
                },
                _ => {}
            }
        }
    });
}
```
</details> 

<hr/>

@cloud303-cholden (and whoever else wants to take a look at it) here's a crash with a backtrace:
<details>
<summary>RUST_BACKTRACE=full cargo run</summary>

```ignore
2024-01-02T06:37:14.308136Z  INFO bevy_winit::system: Closing window 3v0
2024-01-02T06:37:14.313281Z ERROR log: X11 error: XError {
    description: "BadWindow (invalid Window parameter)",
    error_code: 3,
    request_code: 148,
    minor_code: 1,
}    
thread 'main' panicked at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/event_processor.rs:939:30:
Failed to focus input context: XError { description: "BadWindow (invalid Window parameter)", error_code: 3, request_code: 148, minor_code: 1 }
stack backtrace:
   0:     0x56e282732f4c - std::backtrace_rs::backtrace::libunwind::trace::hccf3cfe599d26745
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x56e282732f4c - std::backtrace_rs::backtrace::trace_unsynchronized::hd3d8077f873485f2
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56e282732f4c - std::sys_common::backtrace::_print_fmt::h182daaf98b25bd14
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x56e282732f4c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4b6a846227d97bb7
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56e28275d6c0 - core::fmt::rt::Argument::fmt::h9766ef94e9786c29
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/fmt/rt.rs:142:9
   5:     0x56e28275d6c0 - core::fmt::write::hb46e4cb217dc2581
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/fmt/mod.rs:1120:17
   6:     0x56e28273082f - std::io::Write::write_fmt::h0e754bba34fa795b
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/io/mod.rs:1810:15
   7:     0x56e282732d34 - std::sys_common::backtrace::_print::h73ad48f083423281
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x56e282732d34 - std::sys_common::backtrace::print::h394692fca6f2f34a
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x56e2827344e7 - std::panicking::default_hook::{{closure}}::haa3c8a2ef3bd08de
  10:     0x56e28273424f - std::panicking::default_hook::h37c8166f13b8b27c
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:292:9
  11:     0x56e282734968 - std::panicking::rust_panic_with_hook::h71d389cf21201b59
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:779:13
  12:     0x56e28273484e - std::panicking::begin_panic_handler::{{closure}}::h655372ff562611b4
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:657:13
  13:     0x56e282733416 - std::sys_common::backtrace::__rust_end_short_backtrace::h0e91de37c406f2fe
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x56e2827345b2 - rust_begin_unwind
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:645:5
  15:     0x56e280ed80a5 - core::panicking::panic_fmt::h0290566811e2a53e
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/panicking.rs:72:14
  16:     0x56e280ed86f3 - core::result::unwrap_failed::he976b56b2f3075df
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/result.rs:1649:5
  17:     0x56e280fdd0ed - core::result::Result<T,E>::expect::h2fc0c7855b57ed43
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/result.rs:1030:23
  18:     0x56e280fe0878 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::ha00976238f15900c
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/event_processor.rs:936:25
  19:     0x56e280fc87d9 - winit::platform_impl::platform::x11::EventLoop<T>::drain_events::h61a85b51f4d3bf29
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:512:13
  20:     0x56e280fc87d9 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h0f1036af69629628
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:343:13
  21:     0x56e280fc8fb8 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h9b904f152f1618ab
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:483:27
  22:     0x56e280fca90d - winit::platform_impl::platform::x11::EventLoop<T>::run::h57839b6fbf58bc47
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:498:25
  24:     0x56e280fb6edc - winit::event_loop::EventLoop<T>::run::h40a73ee7fd2e1541
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:305:25
  25:     0x56e280fb6edc - bevy_winit::run::h9315aff35291f1a3
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:235:16
  26:     0x56e280fb6edc - bevy_winit::winit_runner::h2455c1625c398a26
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.12.1/src/lib.rs:920:9
  27:     0x56e280ffdbd2 - core::ops::function::FnOnce::call_once::hf2d4ad9fba90a665
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/ops/function.rs:250:5
  28:     0x56e280ffdbd2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h16e543ce6ef9da78
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/ops/function.rs:250:5
  29:     0x56e2826175ac - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf5c5b2907e69bdd0
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/alloc/src/boxed.rs:2015:9
  30:     0x56e2826175ac - bevy_app::app::App::run::hec54bb76e6bfcb30
                               at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.12.1/src/app.rs:314:9
  31:     0x56e280f06f7d - game_thing::main::hd80d2fd3d26f4062
                               at /home/eats/code/game-thing/src/main.rs:9:5
  32:     0x56e280ef222b - core::ops::function::FnOnce::call_once::hecd8aa21e6d9da7e
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/ops/function.rs:250:5
  33:     0x56e280effbce - std::sys_common::backtrace::__rust_begin_short_backtrace::hfe3988bd85af3679
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/sys_common/backtrace.rs:155:18
  34:     0x56e280f0fcd1 - std::rt::lang_start::{{closure}}::h4402b440661ad9f7
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/rt.rs:167:18
  35:     0x56e28272ad77 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd620b3b8c9654887
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/core/src/ops/function.rs:284:13
  36:     0x56e28272ad77 - std::panicking::try::do_call::h319f4a718cea0bc5
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:552:40
  37:     0x56e28272ad77 - std::panicking::try::h2c1b070ca4a247bb
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:516:19
  38:     0x56e28272ad77 - std::panic::catch_unwind::h6a5d720b96964c71
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panic.rs:142:14
  39:     0x56e28272ad77 - std::rt::lang_start_internal::{{closure}}::hbad653246307ad43
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/rt.rs:148:48
  40:     0x56e28272ad77 - std::panicking::try::do_call::h83f4de88adc0ca5e
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:552:40
  41:     0x56e28272ad77 - std::panicking::try::hd3793aaafcd95dda
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panicking.rs:516:19
  42:     0x56e28272ad77 - std::panic::catch_unwind::h4b1c2658c4d0db72
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/panic.rs:142:14
  43:     0x56e28272ad77 - std::rt::lang_start_internal::hcda365c9de08b755
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/rt.rs:148:20
  44:     0x56e280f0fcaa - std::rt::lang_start::h5f00075111c3d3e0
                               at /rustc/f967532a47eb728ada44473a5c4c2eca1a45fe30/library/std/src/rt.rs:166:17
  45:     0x56e280f0749e - main
  46:     0x7fbb20c29d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  47:     0x7fbb20c29e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  48:     0x56e280ed89b5 - _start
  49:                0x0 - <unknown>
```
</details>

I also did some patching on `winit` (albeit naive, since I'm not familiar enough with its or X11's inner workings) and found that if I prevent the crash in the [`ffi::XI_FocusIn` handler](https://github.com/rust-windowing/winit/blob/c55a2c779b5521c24121515fbc969718fb704cd3/src/platform_impl/linux/x11/event_processor.rs#L968) by returning early if the window doesn't exist (exact same logic as in [`ffi::XI_FocusOut` handler](https://github.com/rust-windowing/winit/blob/c55a2c779b5521c24121515fbc969718fb704cd3/src/platform_impl/linux/x11/event_processor.rs#L968); reasoning being a comment I saw in `ffi:XI_Leave` [here](https://github.com/rust-windowing/winit/blob/c55a2c779b5521c24121515fbc969718fb704cd3/src/platform_impl/linux/x11/event_processor.rs#L956C43-L956C43)), I get a different crash in the later [`ffi::DestroyNotify` handler](https://github.com/rust-windowing/winit/blob/c55a2c779b5521c24121515fbc969718fb704cd3/src/platform_impl/linux/x11/event_processor.rs#L968) at `remove_context`. But that feels a little too deep into `winit` internals to be a problem with Bevy.

**Comment by AxiomaticSemantics** [comment]
I've found a way to reproduce this now it seems, a sequence of rapid inputs to bevy_ui seems to cause it to trigger reliably, no closer on a MRE. I think maybe a ui pressed event is being processed at the same time `AppExit` event is destroying the window. There is no crash, so I haven't gotten much more info, entering my game client and rapidly clicking buttons a few times and clicking exit gets me the error message.

**Comment by AxiomaticSemantics** [comment]
This does not happen in my project anymore.

**Comment by mystal** [comment]
I am getting this error on 0.13. I have one PrimaryWindow spawned through the WindowPlugin and I registered the `close_on_esc` system to run on Update. This is the bit of the log that happens when I press Escape:
```
2024-02-24T19:07:36.241542Z  INFO bevy_window::system: No windows are open, exiting
2024-02-24T19:07:36.241886Z  INFO bevy_winit::system: Closing window 0v1
2024-02-24T19:07:36.261944Z ERROR log: X11 error: XError {
    description: "BadWindow (invalid Window parameter)",
    error_code: 3,
    request_code: 148,
    minor_code: 1,
}
2024-02-24T19:07:36.270827Z ERROR bevy_winit: winit event loop returned an error: os error at /home/mystal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/linux/x11/mod.rs:433: Xlib error: X error: BadWindow (invalid Window parameter) (code: 3, request code: 148, minor code: 1)
```

I don't seem to be getting a panic, since setting `RUST_BACKTRACE=1` does nothing.

I commented out a bunch of the code in my game and was able to get a minimal example that throws this error on exit:
```rust
fn main() {
    // Configure DefaultPlugins.
    let default_plugins = DefaultPlugins
        .set(WindowPlugin {
            primary_window: Some(Window {
                title: "Window Title".into(),
                resizable: false,
                mode: WindowMode::Windowed,
                ..default()
            }),
            ..default()
        });

    let mut app = App::new();
    app
        .add_plugins(default_plugins)
        .add_systems(Update, bevy::window::close_on_esc);

    app.run();
```

**Comment by Mampfinator** [comment]
> This does not happen in my project anymore. How about you @Mampfinator ? if it does in 0.13 could you show a full backtrace?

Sorry for the late response, but yeah, the panic made it into 0.13. I seem to be getting it roughly every time I close any window now. At a glance, the backtrace looks similar to the 0.12 one:
<details>
   <summary>RUST_BACKTRACE=1 cargo run</summary>
   
```ignore
2024-02-27T09:10:18.214751Z ERROR log: X11 error: XError {
    description: "BadWindow (invalid Window parameter)",
    error_code: 3,
}    
thread 'main' panicked at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/event_processor.rs:842:18:
Failed to destroy input context: XError { description: "BadWindow (invalid Window parameter)", error_code: 3, request_code: 148, minor_code: 1 }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::expect
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/result.rs:1030:23
   4: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::destroy_notify
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/event_processor.rs:840:13
   5: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_xevent
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/event_processor.rs:171:36
   6: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/event_processor.rs:79:9
   7: winit::platform_impl::platform::x11::EventLoop<T>::drain_events
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/mod.rs:623:13
   8: winit::platform_impl::platform::x11::EventLoop<T>::single_iteration
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/mod.rs:554:9
   9: winit::platform_impl::platform::x11::EventLoop<T>::poll_events_with_timeout
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/mod.rs:538:9
  10: winit::platform_impl::platform::x11::EventLoop<T>::pump_events
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/mod.rs:444:13
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/x11/mod.rs:405:19
  12: winit::platform_impl::platform::EventLoop<T>::run_on_demand
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/mod.rs:829:56
  13: winit::platform_impl::platform::EventLoop<T>::run
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/linux/mod.rs:822:9
  14: winit::event_loop::EventLoop<T>::run
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/event_loop.rs:249:9
  15: bevy_winit::winit_runner
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.13.0/src/lib.rs:296:23
  16: core::ops::function::FnOnce::call_once
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/ops/function.rs:250:5
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/ops/function.rs:250:5
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/alloc/src/boxed.rs:2016:9
  19: bevy_app::app::App::run
             at /home/eats/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.0/src/app.rs:308:9
  20: windowing_test::main
             at ./src/main.rs:10:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/595bc6f00369475047538fdae1ff8cea692ac385/library/core/src/ops/function.rs:250:5
```
</details>

**Comment by cloud303-cholden** [comment]
Seems like the trail leads to `winit` ([link](https://github.com/rust-windowing/winit/blob/e41f0eabb1d0bd4583dce8035e86abaf38427a99/src/platform_impl/linux/x11/ime/inner.rs#L16)) calling the `XDestroyIC` X11 function ([link](https://github.com/sulmone/X11/blob/59029dc09211926a5c95ff1dd2b828574fefcde6/libX11-1.5.0/src/xlibi18n/ICWrap.c#L260)) passing an `XIC` ([link](https://github.com/rust-windowing/winit/blob/e41f0eabb1d0bd4583dce8035e86abaf38427a99/src/platform_impl/linux/x11/ime/context.rs#L194)). If I'm understanding the `request_code` correctly, it indicates that the `GetColorTableParameterfv` call was made. Looks like this might be an OpenGL protocol. Unfortunately at this point, I'm out of my depth.
