### ISSUE TITLE
Crash with `DefaultPlugins` on debug mode

### ISSUE THREAD

**Issue by poweron0102** [bevyengine/bevy#11393]
## Bevy version

0.12.1

## Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

- Rust version
  - cargo 1.75.0 (1d8b05cdd 2023-11-20)
- the operating system or browser used, including its version
  - Fedora 39

Adapter Info:
```ignore

`AdapterInfo { name: "Mesa Intel(R) HD Graphics 620 (KBL GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }`

```

## What you did

``` toml
[package]
name = "bevy-auto-moon"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.12.1", features = ["dynamic_linking"] }
```
``` rust
// main.rs
use bevy::prelude::*;

fn main(){
  App::new()
    .add_plugins(DefaultPlugins)
    .run();
}
```
 - run with `cargo run`

## What went wrong

 - The window crash. 

## Additional information

```
cargo run

    Finished dev [optimized + debuginfo] target(s) in 0.17s
     Running `target/debug/bevy-auto-moon`
2024-01-18T00:50:21.928079Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2024-01-18T00:50:21.928319Z  INFO log: Guessed window scale factor: 1    
2024-01-18T00:50:22.022495Z  INFO bevy_render::renderer: AdapterInfo { name: "Mesa Intel(R) HD Graphics 620 (KBL GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
2024-01-18T00:50:22.151836Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
2024-01-18T00:50:22.167946Z ERROR log: surface configuration failed: incompatible window kind    
thread 'main' panicked at /home/nathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.17.2/src/backend/direct.rs:771:18:
Error in Surface::configure: Validation Error

Caused by:
    Invalid surface

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (0)' panicked at /home/nathan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.12.1/src/pipelined_rendering.rs:145:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Temp solution
 - `cargo run --release` in release mode it's works fine.

**Comment by alice-i-cecile** [comment]
Can you reproduce this upstream in `wgpu`? Looks like we're hitting a debug assert in there.

**Comment by poweron0102** [comment]
Yap, it's has the same problem with wgpu cube example. 
I will open a issue there too.

**Comment by poweron0102** [comment]
For debug mode it needs `vulkan-validation-layers` package, just install it and everything works fine.
