### ISSUE TITLE
Hiding window leads to swap chain texture timeout

### ISSUE THREAD

**Issue by flash-freezing-lava** [bevyengine/bevy#11863]
## Bevy version

Exist at least since `0.10.0` (previous releases don't work with different error, so it might have been a problem there too) up to `0354ce4450dc244ee4ed4a65d729478df0c027e9`

## Relevant system information

```ignore
AdapterInfo { name: "NVIDIA GeForce GTX 1070", vendor: 4318, device: 7041, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.29.06", backend: Vulkan }
SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.7.4-arch1-1", cpu: "AMD Ryzen 9 7950X 16-Core Processor", core_count: "16", memory: "62.0 GiB" }
```
Running GNOME 45.4 via wayland.
Bevy uses XWayland and the error does not occur when running GNOME via XOrg.

## What you did

1. Execute `cargo run --example breakout` (Happens on other examples too)
2. Hide the window

## What went wrong
```
thread 'main' panicked at crates/bevy_render/src/view/window/mod.rs:384:21:
Couldn't get swap chain texture, operation unrecoverable: A timeout was encountered while trying to acquire the next frame
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (22)' panicked at crates/bevy_render/src/pipelined_rendering.rs:145:45:
called `Result::unwrap()` on an `Err` value: RecvError
```

**Comment by rlamarche** [comment]
I reproduce the issue since I moved to Wayland. I moved to Wayland because on X11 there was a freeze when I click in the window (see https://github.com/bevyengine/bevy/issues/14303).

I have a NVIDIA GPU on Ubuntu 24.04 and driver version 570.172.08.

Startup logs:

```
INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux (Ubuntu 24.04)", kernel: "6.11.0-19-generic", cpu: "AMD Ryzen 9 3900X 12-Core Processor", core_count: "12", memory: "62.7 GiB" }    
ERROR wgpu_hal::gles::egl: EGL 'eglCreateSyncKHR' code 0x3004: EGL_BAD_ATTRIBUTE error: In eglCreateSyncKHR: EGL_SYNC_NATIVE_FENCE_FD_ANDROID specified valid fd butEGL_SYNC_STATUS is also being set
    
 INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2070 SUPER", vendor: 4318, device: 7812, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "570.172.08", backend: Vulkan }
INFO bevy_render::batching::gpu_preprocessing: GPU preprocessing is fully supported on this device.

```

The behavior is exactly the same you describe.

Here the full backtrace on Bevy 0.16.1 :

```
thread 'Compute Task Pool (14)' panicked at /home/romain/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_render-0.16.1/src/view/window/mod.rs:275:17:
Couldn't get swap chain texture, operation unrecoverable: A timeout was encountered while trying to acquire the next frame
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/29483883eed69d5fb4db01964cdf2af4d86e9cb2/library/core/src/panicking.rs:75:14
   2: bevy_render::view::window::prepare_windows
             at /home/romain/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_render-0.16.1/src/view/window/mod.rs:275:17
   3: core::ops::function::FnMut::call_mut
             at /home/romain/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:166:5
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /home/romain/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:294:21
   5: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3) .> Out>>::run::call_inner
             at /home/romain/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.1/src/system/function_system.rs:945:21
   6: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3) .> Out>>::run
             at /home/romain/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.1/src/system/function_system.rs:948:17
   7: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/romain/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.1/src/system/function_system.rs:735:29
   8: <bevy_ecs::system::schedule_system::InfallibleSystemWrapper<S> as bevy_ecs::system::system::System>::run_unsafe
             at /home/romain/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bevy_ecs-0.16.1/src/system/schedule_system.rs:68:16
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::view::window::prepare_windows`!

Process finished with exit code 0
```

**Comment by joyousblunder** [comment]
Same here on Fedora 42 and driver version 580.82.07.
Something related to the window being out of focus/hidden
