### ISSUE TITLE
AssetLoaderError(No registration found for Vec3) when loading a scene

### ISSUE THREAD

**Issue by DidiBear** [bevyengine/bevy#1190]
**Bevy version:** 0.4
**Operating system & version:** Ubuntu 19.04

After the upgrade of `bevy` from 0.3 to 0.4, it's not possible to load a scene file with a `Vec3` attribute anymore. For instance:

- `assets/my_scene.scn`:

```
[
  (
    entity: 0,
    components: [
      {
        "type": "Transform",
        "map": {
          "translation": {
            "type": "Vec3", 
            "value": (150.0, 200.0, 0.0),
          },
          "rotation": {
            "type": "Quat",
            "value": (0.0, 0.0, 0.0, 1.0),
          },
          "scale": {
            "type": "Vec3",
            "value": (0.75, 0.75, 0.0),
          },
        },
      },
    ]
  )
]
```

- `main.rs`:
```rust
use bevy::prelude::*;

fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(load_scene_system.system())
        .run();
}

fn load_scene_system(asset_server: Res<AssetServer>, mut scene_spawner: ResMut<SceneSpawner>) {
    let scene_handle: Handle<DynamicScene> = asset_server.load("my_scene.scn");
    scene_spawner.spawn_dynamic(scene_handle);
    asset_server.watch_for_changes().unwrap();
}
```

This raises the following error:
```
thread 'IO Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: AssetLoaderError(No registration found for Vec3)', /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/asset_server.rs:298:60
```

<details>
<summary><strong>Click here to see the full backtrace</strong></summary>

```
thread 'IO Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: AssetLoaderError(No registration found for Vec3)', /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/asset_server.rs:298:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::unwrap
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973
   4: bevy_asset::asset_server::AssetServer::load_untracked::{{closure}}
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.4.0/src/asset_server.rs:298
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
   6: async_executor::Executor::spawn::{{closure}}
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/async-executor-1.3.0/src/lib.rs:116
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
   8: async_task::raw::RawTask<F,T,S>::run
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489
   9: async_task::runnable::Runnable::run
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/runnable.rs:309
  10: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/async-executor-1.3.0/src/lib.rs:207
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  12: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.2/src/future.rs:529
  13: async_executor::Executor::run::{{closure}}
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/async-executor-1.3.0/src/lib.rs:214
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  15: futures_lite::future::block_on::{{closure}}
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.2/src/future.rs:89
  16: std::thread::local::LocalKey<T>::try_with
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:265
  17: std::thread::local::LocalKey<T>::with
             at /home/me/.asdf/installs/rust/1.47.0/toolchains/1.47.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:241
  18: futures_lite::future::block_on
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.2/src/future.rs:79
  19: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.4.0/src/task_pool.rs:133
```
</details>

In `bevy` 0.3, this above code works perfectly fine. 

If the solution is simple, such as a missing `register_type`, could you please add an example in  [`scene`](https://github.com/bevyengine/bevy/tree/master/examples/scene) or [`reflection`](https://github.com/bevyengine/bevy/tree/master/examples/reflection) examples ?

**Comment by mockersf** [comment]
it seems now you must provide the full path to this type instead of `Vec3`, so `glam::f32::vec3::Vec3`, as in this [scene example](https://github.com/bevyengine/bevy/blob/master/assets/scenes/load_scene_example.scn#L9)

**Comment by DidiBear** [comment]
Thank you, so I manually updated the scene file to by replacing type with the full path. I then got this new error:

```
thread 'main' panicked at 'scene contains the unregistered type `bevy_reflect::map::DynamicMap`. consider registering the type using `app.register_type::<T>()`', /home/me/.asdf/installs/rust/1.47.0/registry/src/github.com-1ecc6299db9ec823/bevy_scene-0.4.0/src/scene_spawner.rs:328:31
```

^ This is because the `"map"` field have changed too and now it's `"struct"`.

So here are the changes that resolve the issue:

```diff
  [
    (
      entity: 0,
      components: [
        {
-         "type": "Transform",
+         "type": "bevy_transform::components::transform::Transform",
-         "map": {
+         "struct": {
            "translation": {
-             "type": "Vec3", 
+             "type": "glam::f32::vec3::Vec3", 
              "value": (150.0, 200.0, 0.0),
            },
            "rotation": {
-             "type": "Quat", 
+             "type": "glam::f32::quat::Quat",
              "value": (0.0, 0.0, 0.0, 1.0),
            },
            "scale": {
-             "type": "Vec3", 
+             "type": "glam::f32::vec3::Vec3",
              "value": (0.75, 0.75, 0.0),
            },
          },
        },
      ]
    )
  ]
```

To whoever facing this issue, I advice you to re-run this [`save_scene_system` in this `scene.rs` example](
https://github.com/bevyengine/bevy/blob/master/examples/scene/scene.rs) with your own components.
