### ISSUE TITLE
`scene_viewer` panics when given a gltf with a camera

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#11905]
## Bevy version

main 80f2ee291042af970242a255b5630242fe264a3f

Possibly broken by #11868 adding exposure settings to camera bundles?

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

Exported a gltf (bistro outdoor exported as gltf in blender with camera export enabled)

```
cargo run --release --example scene_viewer -- ~/untitled.glb
```

## What went wrong

```
2024-02-16T18:09:57.052459Z  INFO scene_viewer::scene_viewer_plugin: Spawning scene...
thread 'main' panicked at crates/bevy_scene/src/scene_spawner.rs:431:35:
scene contains the unregistered type `bevy_render::camera::camera::Exposure`. consider reflecting it with `#[derive(Reflect)]` and registering the type using `app.register_type::<T>()`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in exclusive system `bevy_scene::scene_spawner::scene_spawner_system`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
thread 'main' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.10/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by alice-i-cecile** [comment]
This is an extension of https://github.com/bevyengine/bevy/issues/11852. @cart, your call on if we block on this, or put a fix in a point release.
