### ISSUE TITLE
Panic with UI hierarchy when no camera is present

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#12184]
## Bevy version

main, 0.13

bisected to #10559

## Relevant system information

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

I noticed this while writing some doc examples which were accidentally not `no_run`.

This is the most minimal repro I can make, but I also see this panic in e.g. the `button` example modified with no camera.

```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands
        .spawn(NodeBundle::default())
        .with_children(|parent| {
            parent.spawn(NodeBundle::default());
        });
}
```

## What went wrong

Received a warning about a camera not being present, which I suppose makes sense.

Received a warning about an "unstyled child in a UI entity hierarchy" which does not make sense as far as I can tell.

Finally, panicked on an `unwrap` which doesn't seem desirable.

```
2024-02-28T15:05:02.776557Z  WARN bevy_ui::layout: No camera found to render UI to. To fix this, add at least one camera to the scene.
2024-02-28T15:05:02.776596Z  WARN bevy_ui::layout: Unstyled child in a UI entity hierarchy. You are using an entity without UI components as a child of an entity with UI components, results may be unexpected.
thread 'Compute Task Pool (0)' panicked at crates/bevy_ui/src/layout/mod.rs:131:60:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_ui::layout::ui_layout_system`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
thread 'main' panicked at /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by ekropotin** [comment]
I want to work on this issue, if it's OK
