### ISSUE TITLE
Resizing causes a crash on latest stable Nvidia driver 550

### ISSUE THREAD

**Issue by eero-lehtinen** [bevyengine/bevy#12199]
## Bevy version

Affects both 0.13 and main (21adeb684261eacd39acecaa8b056e0b9e918268)

## Relevant system information

```
cargo 1.76.0 (c84b36747 2024-01-18)
KDE desktop X11
```
```
AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.54.14", backend: Vulkan }
SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.7.6-arch1-1", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
```

## What you did

Run `cargo run --example window_resizing` or pretty much any example. Then drag a window corner to resize.

## What went wrong

Outputs this and crashes.
```
thread 'Compute Task Pool (6)' panicked at crates/bevy_render/src/view/window/mod.rs:357:26:
Error reconfiguring surface: Outdated
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (1)' panicked at crates/bevy_render/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Additional information

550 was very recently stabilized (https://www.phoronix.com/news/NVIDIA-550.54.14-Linux-Driver).

Everything starts working again if I downgrade to the 545 driver.

I tested an example from the winit repository `cargo run --example window` and there was no issues. 

Other applications I use aren't affected by this issue, so it might not be Nvidia's fault.

Complete log of the bevy example with backtrace:
```
❯ RUST_BACKTRACE=1 cargo run --example window_resizing
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/window_resizing`
2024-02-29T12:17:29.654613Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-02-29T12:17:29.654883Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.1666666666666667    
2024-02-29T12:17:29.722909Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.54.14", backend: Vulkan }
2024-02-29T12:17:30.120325Z  INFO gilrs_core::platform::platform::gamepad: Gamepad /dev/input/event9 (Generic X-Box pad) connected.    
2024-02-29T12:17:30.203046Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.7.6-arch1-1", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
2024-02-29T12:17:30.215488Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
thread 'Compute Task Pool (6)' panicked at crates/bevy_render/src/view/window/mod.rs:357:26:
Error reconfiguring surface: Outdated
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::expect
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
   4: bevy_render::view::window::prepare_windows
             at ./crates/bevy_render/src/view/window/mod.rs:355:33
   5: core::ops::function::FnMut::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:166:5
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:294:13
   7: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6,F7,F8) .> Out>>::run::call_inner
             at ./crates/bevy_ecs/src/system/function_system.rs:661:21
   8: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6,F7,F8) .> Out>>::run
             at ./crates/bevy_ecs/src/system/function_system.rs:664:17
   9: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at ./crates/bevy_ecs/src/system/function_system.rs:504:19
  10: bevy_ecs::schedule::executor::multi_threaded::ExecutorState::spawn_system_task::{{closure}}::{{closure}}
             at ./crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:621:26
  11: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  13: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  14: __rust_try
  15: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  16: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  17: bevy_ecs::schedule::executor::multi_threaded::ExecutorState::spawn_system_task::{{closure}}
             at ./crates/bevy_ecs/src/schedule/executor/multi_threaded.rs:614:23
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:297:9
  19: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:42
  20: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  21: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  22: __rust_try
  23: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  24: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  25: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:9
  26: async_executor::Executor::spawn::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  27: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:550:21
  28: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  29: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  30: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  31: __rust_try
  32: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  33: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  34: async_task::raw::RawTask<F,T,S,M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:549:23
  35: async_task::runnable::Runnable<M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:781:18
  36: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:254:21
  37: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:449:33
  38: async_executor::Executor::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  39: futures_lite::future::block_on::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:99:19
  40: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  41: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  42: futures_lite::future::block_on
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:78:5
  43: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:180:37
  44: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  45: __rust_try
  46: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  47: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  48: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:174:43
  49: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  50: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  51: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:167:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (0)' panicked at crates/bevy_render/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1073:23
   4: bevy_render::pipelined_rendering::RenderAppChannels::recv::{{closure}}
             at ./crates/bevy_render/src/pipelined_rendering.rs:49:26
   5: bevy_render::pipelined_rendering::update_rendering::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_render/src/pipelined_rendering.rs:185:60
   6: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:297:9
   7: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:42
   8: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
   9: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  10: __rust_try
  11: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  12: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  13: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:588:9
  14: async_executor::Executor::spawn::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:158:20
  15: async_task::raw::RawTask<F,T,S,M>::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:550:21
  16: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  17: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panic/unwind_safe.rs:272:9
  18: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  19: __rust_try
  20: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  21: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  22: async_task::raw::RawTask<F,T,S,M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:549:23
  23: async_task::runnable::Runnable<M>::run
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:781:18
  24: async_executor::Executor::run::{{closure}}::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:254:21
  25: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:449:33
  26: async_executor::Executor::run::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.8.0/src/lib.rs:261:32
  27: futures_lite::future::block_on::{{closure}}
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:99:19
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  30: futures_lite::future::block_on
             at /home/eero/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-2.2.0/src/future.rs:78:5
  31: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:180:37
  32: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  33: __rust_try
  34: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  35: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  36: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:174:43
  37: std::thread::local::LocalKey<T>::try_with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  38: std::thread::local::LocalKey<T>::with
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  39: bevy_tasks::task_pool::TaskPool::new_internal::{{closure}}::{{closure}}
             at ./crates/bevy_tasks/src/task_pool.rs:167:25
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alice-i-cecile** [comment]
Can you reproduce this upstream on `winit`'s examples? If so, please open an issue there and link this issue for us <3

**Comment by eero-lehtinen** [comment]
I tested older versions of bevy and it looks like 0.9 is the latest version that works :D

**Comment by eero-lehtinen** [comment]
Bisected the issue to the introduction of pipelined rendering 2027af4c54082007fed2091f112a11cb0bc5fc08 :)

**Comment by alice-i-cecile** [comment]
FYI @james7132 @hymm. Thanks a ton for bisecting!

**Comment by eero-lehtinen** [comment]
Also works on main if I disable the `multi-threading` feature as it disables pipelined rendering.

**Comment by StarArawn** [comment]
I just ran into this myself. Arch linux with nvidia drivers `550.54.14-2`.

**Comment by DissolveDZ** [comment]
I have the same issue on the newest nvidia drivers and X11

**Comment by DissolveDZ** [comment]
> Also works on main if I disable the `multi-threading` feature as it disables pipelined rendering.

after disabling multithreading i'm getting the following error:
```
thread 'main' panicked at /home/colin/.cargo/registry/s
c/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/s
c/view/window/mod.rs:346:18:
Error configuring surface: Outdated
note: run with `RUST_BACKTRACE=1` environment variable 
o display a backtrace
Encountered a panic in system `bevy_render::view::windo
::prepare_windows`!
```

**Comment by eero-lehtinen** [comment]
I did some more investigation and found that we call `surface.get_current_texture()` directly after `WindowEvent::Resized`, while `wgpu` examples only do it on `WindowEvent::RedrawRequested`. If I modify the `wgpu` examples to do that, they crash too.

I tried to remove those calls from `bevy` by commenting out [these lines](https://github.com/bevyengine/bevy/blob/4cd53cc7e12fb8e4d612fc02b634828cda97af82/crates/bevy_render/src/view/window/mod.rs#L322-L325), and the crashes went away and everything worked fine. I don't know if doing this is safe overall, as I'm not experienced in `wgpu`. Why do we even call this function when `wgpu` examples don't?

**Comment by alice-i-cecile** [comment]
Excellent digging. I'd be happy to review a PR that changes this behavior in Bevy: it sounds like we're doing work overly eagerly for no real benefit.

**Comment by eero-lehtinen** [comment]
I'm not actually sure if our code is too eager. It's just that with this specific driver `surface.get_current_texture` doesn't work if called just after `surface.configure`. Maybe as a workaround maybe we could skip drawing a frame on resize? I'm not really familiar with bevy or wgpu internals though, just testing stuff out.

**Comment by theHamsta** [comment]
```
2024-03-06T20:26:51.531143Z DEBUG present_frames: wgpu_core::present: Removing swapchain texture Id(12,115,vk) from the device tracker    
2024-03-06T20:26:51.549641Z DEBUG present_frames: wgpu_core::present: Presented. End of Frame    
2024-03-06T20:26:51.550759Z DEBUG wgpu_core::device::global: configuring surface with SurfaceConfiguration { usage: TextureUsages(RENDER_ATTACHMENT), format: Bgra8UnormSrgb, width: 1493, height: 840, present_mode: Fifo, desired_maximum_frame_latency: 2, alpha_mode: Auto, view_formats: [] }    
2024-03-06T20:26:51.550953Z  WARN wgpu_hal::vulkan::conv: Unrecognized present mode 1000361000    
2024-03-06T20:26:51.551007Z DEBUG wgpu_core::device::life: Active submission 229 is done    
VUID-VkSwapchainCreateInfoKHR-pNext-07781(ERROR / SPEC): msgNum: 1284057537 - Validation Error: [ VUID-VkSwapchainCreateInfoKHR-pNext-07781 ] | MessageID = 0x4c8929c1 | vkCreateSwapchainKHR(): pCreateInfo->imageExtent (1493, 840), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (1477,826), minImageExtent = (1477,826), maxImageExtent = (1477,826). The Vulkan spec states: If a VkSwapchainPresentScalingCreateInfoEXT structure was not included in the pNext chain, or it is included and VkSwapchainPresentScalingCreateInfoEXT::scalingBehavior is zero then imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkSwapchainCreateInfoKHR-pNext-07781)
    Objects: 0
2024-03-06T20:26:51.559037Z  INFO wgpu_hal::vulkan::instance: GENERAL [NVIDIA (0x4)]
        Requested image extent (1493x840) does not match surface (1477x826), marking swapchain out of date    
2024-03-06T20:26:51.559068Z  INFO wgpu_hal::vulkan::instance:   objects: (type: SWAPCHAIN_KHR, hndl: 0x7e7f1801b060, name: ?)    
thread 'Compute Task Pool (3)' panicked at crates/bevy_render/src/view/window/mod.rs:324:26:
Error reconfiguring surface: Outdated
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (7)' panicked at crates/bevy_render/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
```
I get this error when running with validation layers.

**Comment by mockersf** [comment]
> I did some more investigation and found that we call `surface.get_current_texture()` directly after `WindowEvent::Resized`, while `wgpu` examples only do it on `WindowEvent::RedrawRequested`. If I modify the `wgpu` examples to do that, they crash too.

`surface.get_current_texture()` is called in the render app, so it's mostly unrelated to the order Bevy receives events from winit

**Comment by eero-lehtinen** [comment]
> `surface.get_current_texture()` is called in the render app, so it's mostly unrelated to the order Bevy receives events from winit

I guess what I should have said is that we call both `surface.configure` and `surface.get_current_texture` at the same time in the render app after the window size has changed, while `wgpu` calls them in separate winit events (`Resized` and `RedrawRequested`). That maybe gives the driver enough time to finish processing and not error out, at least it doesn't crash. Though that might not be applicable in bevy architecture.

**Comment by mockersf** [comment]
@eero-lehtinen could you try with this branch? https://github.com/mockersf/bevy/tree/nvidia-outdated

I'm not sure how that will behave, it may fix the issue or make it worse 😄

**Comment by eero-lehtinen** [comment]
> @eero-lehtinen could you try with this branch? https://github.com/mockersf/bevy/tree/nvidia-outdated

Looks like that just works :D. I think I also at some point tried just blindly `return`ing but had bad results.

Though was that previous retrying behaviour needed on other platforms? `wgpu` examples do it too.

**Comment by eero-lehtinen** [comment]
I ported the fix to my game and there are definitely still situations where it can crash. E.g. switching between fullscreen and windowed quickly at startup and resizing the window when it is one of the two windows tiled side by side. The error is the same.

**Comment by eero-lehtinen** [comment]
It seems to break when there are resizes in consecutive frames, as the outdated error is ignored in only one code path of two. I made a version where the outdated error is always ignored, and that seems to work perfectly. https://github.com/eero-lehtinen/bevy/tree/v0.13.0-nvidia-fix

**Comment by zentasumu** [comment]
Under arch linux, using nvidia driver version 550.54.14-4, with Xwayland.

Testing winit 0.29.14 examples, no issues.

Testing with wgpu 0.19.3 boids example, issue was reproducible.

```
[2024-03-09T04:53:35Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1.5
[2024-03-09T04:53:35Z INFO  wgpu_examples::framework] Initializing wgpu...
[2024-03-09T04:53:35Z INFO  wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce RTX 3060 Laptop GPU", vendor: 4318, device: 9504, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "550.54.14", backend: Vulkan }
[2024-03-09T04:53:35Z INFO  wgpu_examples::framework] Using NVIDIA GeForce RTX 3060 Laptop GPU (Vulkan)
[2024-03-09T04:53:35Z INFO  wgpu_examples::framework] Entering event loop...
[2024-03-09T04:53:35Z INFO  wgpu_examples::framework] Surface resume PhysicalSize { width: 800, height: 600 }
[2024-03-09T04:53:35Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 800, height: 600 }
[2024-03-09T04:53:35Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 624, height: 1137 }
[2024-03-09T04:53:36Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 800, height: 600 }
[2024-03-09T04:53:36Z INFO  wgpu_examples::framework] Frame time 6.05ms (165.4 FPS)
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Frame time 6.06ms (165.0 FPS)
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 801, height: 600 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 802, height: 600 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 802, height: 602 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 806, height: 605 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 807, height: 605 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 808, height: 606 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 808, height: 607 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 815, height: 613 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 818, height: 615 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 829, height: 621 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 832, height: 622 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 844, height: 628 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 847, height: 630 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 855, height: 636 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 863, height: 640 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 879, height: 651 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 882, height: 654 }
[2024-03-09T04:53:37Z INFO  wgpu_examples::framework] Surface resize PhysicalSize { width: 885, height: 656 }
thread 'main' panicked at 'Failed to acquire next surface texture!: Outdated', examples/src/framework.rs:235:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jake8655** [comment]
> It seems to break when there are resizes in consecutive frames, as the outdated error is ignored only in the code path where there is no resize. I made a version where the outdated error is always ignored, and that seems to work perfectly. https://github.com/eero-lehtinen/bevy/tree/v0.13.0-nvidia-fix

Tried out your fix, works for me too in XWayland, nvidia drivers v550.54.14

**Comment by notverymoe** [comment]
> It seems to break when there are resizes in consecutive frames, as the outdated error is ignored only in the code path where there is no resize. I made a version where the outdated error is always ignored, and that seems to work perfectly. https://github.com/eero-lehtinen/bevy/tree/v0.13.0-nvidia-fix

This appears to work for me too. Arch Linux, i3, X11, Nvidia 550.54.14.

**Comment by amethys7dev** [comment]
Sorry for the necro - been tearing my hair out for a while over this.
Anyone here from a search engine: You're likely running in XWayland, it's probably nvidia's fault. I don't know why it happens but my session is Wayland and I don't want it running in Xorg anyways, you can make it run in Wayland by editing `Cargo.toml`:
```toml
bevy = { version = "0.16", features = ["wayland"] } # Add wayland feature
```

My game wasn't crashing, just spamming this repeatedly and never presenting a window:
```
2025-06-01T06:50:20.398270Z  WARN wgpu_hal::vulkan::conv: Unrecognized present mode 1000361000    
2025-06-01T06:50:20.403844Z  WARN bevy_render::view::window: Couldn't get swap chain texture after configuring. Cause: 'The underlying surface has changed, and therefore the swap chain must be updated'
```
