### ISSUE TITLE
WGPU Panic when there's a transmission material in scene and camera is switched 

### ISSUE THREAD

**Issue by franklinblanco** [bevyengine/bevy#12445]
## Bevy version
0.13

## Relevant system information
`cargo 1.77.0-nightly (1ae631085 2024-01-17)`

`AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }`

## What you did

I Spawned a Cube mesh and gave it the following StandardMaterial:

```rust
materials.add(StandardMaterial {
        base_color: Color::Rgba { red: 0.455, green: 1.0, blue: 0.905, alpha: 1.0 },
        specular_transmission: 0.95,
        diffuse_transmission: 0.0,
        thickness: 1.8,
        ior: 1.0,
        perceptual_roughness: 0.05,
        reflectance: 0.5,
        ..default()
});
```

Then, I clicked my keybind for opening the bevy_editor_pls once, all good, then I clicked the keybind again, which takes me out of the inspector view, and then once again, and then I get a panic. 

I did this a couple of times and can confirm, it always happens the second time.

## What went wrong

This is the error message in the console:

```
ERROR log: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at <REDACTED>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:3009:5:
wgpu error: Validation Error

Caused by:
    In CommandEncoder::copy_texture_to_texture
    Copy error
    Source format (Rgba8UnormSrgb) and destination format (Rgba16Float) are not copy-compatible (they may only differ in srgb-ness)


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in exclusive system `bevy_render::renderer::render_system`!
thread 'Compute Task Pool (1)' panicked at <REDACTED>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.0/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
thread 'main' panicked at  <REDACTED>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.11/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

## Additional information

I'm attempting to replicate this in a small repo I can upload. I'll add a comment if I get it. But meanwhile I thought I could report on this!
Video Demo, the end of the video is when it panicked.
https://github.com/bevyengine/bevy/assets/72827992/b8ec5cf7-c070-4f6c-ae53-a5b8f3380c72

Thanks to the bevy devs for your hard work!

**Comment by franklinblanco** [comment]
Since I haven't been able to replicate the Bug anywhere else, I'll attach a video of what happens when I remove the material.
https://github.com/bevyengine/bevy/assets/72827992/e481aec0-d1dc-488c-b136-d4a8ea39d34e

**Comment by franklinblanco** [comment]
Apparently it gets fixed if I comment
`perceptual_roughness`
Seems like I'm setting perceptual roughness below the allowed threshold for the shader! Should we change anything? Maybe  panic on just creating a material with this specific roughness?

![Screenshot 2024-03-12 at 7 04 01 PM](https://github.com/bevyengine/bevy/assets/72827992/3a01550f-9a38-4215-a105-f5d7a4821a16)

![Screenshot 2024-03-12 at 7 05 04 PM](https://github.com/bevyengine/bevy/assets/72827992/5e7300b6-460f-432a-b56a-1c1bc4166521)

**Comment by franklinblanco** [comment]
Wow. I'm really lost and confused now.

So if I set the value, I get a panic.
![Screenshot 2024-03-12 at 7 09 31 PM](https://github.com/bevyengine/bevy/assets/72827992/b6ebffd3-4fbe-4ae0-a2de-0d117a037fd3)

But if I leave it as the default value, it doesn't panic? 

I tried 0.5, 1.0, 0.1, 0.05, 0.089. None worked
