### ISSUE TITLE
Android TV crash: TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictions

### ISSUE THREAD

**Issue by edisno** [bevyengine/bevy#12520]
## Bevy version

0.13

## \[Optional\] Relevant system information

SystemInfo { os: "Android 8.0.0 TPM171E", kernel: "3.10.79", cpu: "not available", core_count: "4", memory: "1.8 GiB" }

## What you did

Run an app on Android TV

## What went wrong

- what were you expecting?

The app should work

- what actually happened?

The app crashed

## Additional information

thread '<unnamed>' panicked at [...]wgpu-0.19.3/src/backend/wgpu_core.rs:3006:5: wgpu error: Validation Error Caused by: 
In Device::create_texture    note: label = point_light_shadow_map_texture`
Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictions

It works fine on my newer android Phone.

I know nothing about this, but believe it might be related to Depth24Plus vs Depth32Float support.

**Comment by quick0831** [comment]
Encounter the same issue on mobile

## Bevy version

0.15.2

## System information

`{ os: "Android 8.1.0 HTC Desire 12s", kernel: "3.18.71-perf-g13ca675", cpu: "not available", core_count: "8", memory: "2.8 GiB" }`

## What went wrong

I attempt to run [`android_example_native`](https://github.com/bevyengine/bevy/blob/v0.15.2/examples/mobile/src/lib.rs) but the app just stuck

`adb logcat | grep 'RustStdoutStderr\|bevy\|wgpu'`

```
02-08 03:41:11.128  2622  2693 I event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_diagnostic-0.15.2/SystemInfo { os: "Android 8.1.0 HTC Desire 12s", kernel: "3.18.71-perf-g13ca675", cpu: "not available", core_count: "8", memory: "2.8 GiB" }
02-08 03:41:11.550  2622  2693 I event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.15.2/src/AdapterInfo { name: "Adreno (TM) 505", vendor: 20803, device: 83887360, device_type: IntegratedGpu, driver: "?", driver_info: "?", backend: Vulkan }
02-08 03:41:12.421  2622  2693 E event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_gilrs-0.15.2/src/lFailed to start Gilrs. Gilrs does not support current platform.
02-08 03:41:12.587  2622  2693 W event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_pbr-0.15.2/src/ssaScreenSpaceAmbientOcclusionPlugin
 not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
02-08 03:41:12.589  2622  2693 I event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.15.2/src/sCreating new window "App" (0v1#4294967296)
02-08 03:41:12.836  2622  2705 E log event: Device::create_texture error: Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictionslog.target = "wgpu_core::device::global"; log.module_path = "wgpu_core::device::global"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-23.0.1/src/device/global.rs"; log.line = 332;
02-08 03:41:12.836  2622  2705 E log event: Handling wgpu errors as fatal by defaultlog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs"; log.line = 1219;
02-08 03:41:12.836  2622  2691 I RustStdoutStderr: thread 'Compute Task Pool (2)' panicked at /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1219:18:
02-08 03:41:12.836  2622  2691 I RustStdoutStderr: wgpu error: Validation Error
02-08 03:41:12.836  2622  2691 I RustStdoutStderr: 
02-08 03:41:12.836  2622  2691 I RustStdoutStderr: Caused by:
02-08 03:41:12.836  2622  2691 I RustStdoutStderr:   In Device::create_texture, label = 'point_light_shadow_map_texture'
02-08 03:41:12.836  2622  2691 I RustStdoutStderr:     Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictions
02-08 03:41:12.836  2622  2691 I RustStdoutStderr: 
02-08 03:41:12.837  2622  2691 I RustStdoutStderr: 
02-08 03:41:12.837  2622  2691 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
02-08 03:41:12.839  2622  2691 I RustStdoutStderr: Encountered a panic in system `bevy_pbr::render::light::prepare_lights`!
02-08 03:41:12.846  2622  2705 E log event: Device::create_texture error: Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictionslog.target = "wgpu_core::device::global"; log.module_path = "wgpu_core::device::global"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-23.0.1/src/device/global.rs"; log.line = 332;
02-08 03:41:12.846  2622  2705 E log event: Handling wgpu errors as fatal by defaultlog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs"; log.line = 1219;
02-08 03:41:12.846  2622  2691 I RustStdoutStderr: thread 'Compute Task Pool (2)' panicked at /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1219:18:
02-08 03:41:12.846  2622  2691 I RustStdoutStderr: wgpu error: Validation Error
02-08 03:41:12.846  2622  2691 I RustStdoutStderr: 
02-08 03:41:12.846  2622  2691 I RustStdoutStderr: Caused by:
02-08 03:41:12.846  2622  2691 I RustStdoutStderr:   In Device::create_texture, label = 'view_depth_texture'
02-08 03:41:12.846  2622  2691 I RustStdoutStderr:     Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictions
02-08 03:41:12.846  2622  2691 I RustStdoutStderr: 
02-08 03:41:12.846  2622  2691 I RustStdoutStderr: 
02-08 03:41:12.848  2622  2691 I RustStdoutStderr: Encountered a panic in system `bevy_core_pipeline::core_3d::prepare_core_3d_depth_textures`!
```

## Additional information

When I'm attempting to run my own test code, the app stuck at the loading screen

This time I use `cargo apk run` to build the app, but it seems irrelevant

`src/lib.rs`

```rs
use bevy::prelude::*;
use bevy::window::WindowMode;

#[bevy_main]
fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                resizable: false,
                mode: WindowMode::BorderlessFullscreen(MonitorSelection::Primary),
                // on iOS, gestures must be enabled.
                // This doesn't work on Android
                recognize_rotation_gesture: true,
                ..default()
            }),
            ..default()
        }))
        .add_systems(Startup, setup)
        .run();
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<ColorMaterial>>,
) {
    info!("Hello, world!");

    commands.spawn((
        Camera2d,
        // MSAA makes some Android devices panic, this is under investigation
        // https://github.com/bevyengine/bevy/issues/8229
        #[cfg(target_os = "android")]
        Msaa::Off,
    ));

    let color = Color::hsv(60.0, 0.95, 0.7);

    commands.spawn((
        Mesh2d(meshes.add(Circle::new(50.0))),
        MeshMaterial2d(materials.add(color)),
        Transform::from_xyz(0.0, 0.0, 0.0),
    ));
}
```

`adb logcat | grep 'RustStdoutStderr\|bevy\|wgpu'`

```
02-08 15:47:38.935  3752  3799 I event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_diagnostic-0.15.2/SystemInfo { os: "Android 8.1.0 HTC Desire 12s", kernel: "3.18.71-perf-g13ca675", cpu: "not available", core_count: "8", memory: "2.8 GiB" }
02-08 15:47:39.159  3752  3799 I event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.15.2/src/AdapterInfo { name: "Adreno (TM) 505", vendor: 20803, device: 83887360, device_type: IntegratedGpu, driver: "?", driver_info: "?", backend: Vulkan }
02-08 15:47:39.749  3752  3799 E event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_gilrs-0.15.2/src/lFailed to start Gilrs. Gilrs does not support current platform.
02-08 15:47:39.904  3752  3799 W event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_pbr-0.15.2/src/ssaScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
02-08 15:47:39.906  3752  3799 I event /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.15.2/src/sCreating new window "App" (0v1#4294967296)
02-08 15:47:40.027  3752  3799 E log event: Device::create_texture error: Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictionslog.target = "wgpu_core::device::global"; log.module_path = "wgpu_core::device::global"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-23.0.1/src/device/global.rs"; log.line = 332;
02-08 15:47:40.027  3752  3799 E log event: Handling wgpu errors as fatal by defaultlog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs"; log.line = 1219;
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: thread '<unnamed>' panicked at /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1219:18:
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: wgpu error: Validation Error
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: 
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: Caused by:
02-08 15:47:40.027  3752  3798 I RustStdoutStderr:   In Device::create_texture, label = 'view_depth_texture'
02-08 15:47:40.027  3752  3798 I RustStdoutStderr:     Texture usages TextureUsages(RENDER_ATTACHMENT) are not allowed on a texture of type Depth32Float due to downlevel restrictions
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: 
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: 
02-08 15:47:40.027  3752  3798 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
02-08 15:47:40.028  3752  3798 I RustStdoutStderr: Encountered a panic in system `bevy_core_pipeline::core_2d::prepare_core_2d_depth_textures`!
02-08 15:47:40.105  3752  3803 E log event: Device::create_render_pipeline error: Depth/stencil state is invalidlog.target = "wgpu_core::device::global"; log.module_path = "wgpu_core::device::global"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-23.0.1/src/device/global.rs"; log.line = 1357;
02-08 15:47:40.106  3752  3803 E log event: Handling wgpu errors as fatal by defaultlog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs"; log.line = 1102;
02-08 15:47:40.106  3752  3798 I RustStdoutStderr: thread 'Async Compute Task Pool (1)' panicked at /home/quick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1102:18:
02-08 15:47:40.106  3752  3798 I RustStdoutStderr: wgpu error: Validation Error
02-08 15:47:40.106  3752  3798 I RustStdoutStderr: 
02-08 15:47:40.106  3752  3798 I RustStdoutStderr: Caused by:
02-08 15:47:40.106  3752  3798 I RustStdoutStderr:   In Device::create_render_pipeline, label = 'sprite_pipeline'
02-08 15:47:40.106  3752  3798 I RustStdoutStderr:     Depth/stencil state is invalid
02-08 15:47:40.106  3752  3798 I RustStdoutStderr:       Format Depth32Float is not renderable
02-08 15:47:40.106  3752  3798 I RustStdoutStderr: 
02-08 15:47:40.106  3752  3798 I RustStdoutStderr: 
```

**Comment by quick0831** [comment]
However, it works on a newer device

`{ os: "Android 13 SM-A226B", kernel: "4.14.186-27218697", cpu: "not available", core_count: "8", memory: "3.5 GiB" }`
