### ISSUE TITLE
Bevy 0.13 Crash When Project is a Member of a Workspace

### ISSUE THREAD

**Issue by nametable** [bevyengine/bevy#12875]
## Bevy Version 

0.13.1

## Relevant system information

 - Rust version: `cargo 1.77.1 (e52e36006 2024-03-26)`
 - OS: Arch Linux
 - Kernel: `6.8.2-arch2-1`
 - GPU: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP]
 - CPU: AMD Ryzen 5 3600
 - AdapterInfo { name: "NVIDIA GeForce RTX 2070", vendor: 4318, device: 7938, device_type: DiscreteGpu, backend: Vulkan }

## What you did

I was trying to build my project, and realized it was always crashing. I then made a simple test example in my project which was also failing.

## What went wrong

I was not expecting thread panics and application crash. Instead I got these errors:
```
2024-04-04T16:58:18.060614Z  WARN log: error setting XSETTINGS; Xft options won't reload automatically    
2024-04-04T16:58:18.074765Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-04-04T16:58:18.075323Z  INFO log: Guessed window scale factor: 1.1666666666666667    
2024-04-04T16:58:18.167569Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 580 2048SP (RADV POLARIS10)", vendor: 4098, device: 28639, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 24.0.4-arch1.1", backend: Vulkan }
2024-04-04T16:58:18.633736Z  INFO log: Gamepad /dev/input/event12 (Logitech Gamepad F310) connected.    
2024-04-04T16:58:18.750336Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling Arch Linux", kernel: "6.8.2-arch2-1", cpu: "AMD Ryzen 5 3600 6-Core Processor", core_count: "6", memory: "47.0 GiB" }
2024-04-04T16:58:18.764816Z  INFO bevy_input::gamepad: Gamepad { id: 0 } Connected
thread 'Async Compute Task Pool (2)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/naga-0.19.2/src/back/glsl/mod.rs:1183:44:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Async Compute Task Pool (1)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.1/src/render_resource/pipeline_cache.rs:801:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'Async Compute Task Pool (0)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.1/src/render_resource/pipeline_cache.rs:702:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'Async Compute Task Pool (2)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.1/src/render_resource/pipeline_cache.rs:702:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'Async Compute Task Pool (0)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.1/src/render_resource/pipeline_cache.rs:801:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'Async Compute Task Pool (1)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.1/src/render_resource/pipeline_cache.rs:702:60:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
Encountered a panic in system `bevy_core_pipeline::upscaling::prepare_view_upscaling_pipelines`!
thread 'Compute Task Pool (4)' panicked at /home/*****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.1/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
```

## Additional information

I created a repo which reproduces the issue on my computer: 
https://github.com/nametable/bevy_workspace_crash_repro/tree/in-workspace

On `master` the program runs without crash, and on `in-workspace` the program crashes. No code change, no `Cargo.lock` change. Just moved the project into a workspace.

My current workaround is to not use `cargo` workspaces, however this does not make sense and is inconvenient.

**Comment by nametable** [comment]
I just repro'd this on my laptop too, so I don't think it depends on hardware:
 - AdapterInfo { name: "Intel(R) Xe Graphics (TGL GT2)", vendor: 32902, device: 39497, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 24.0.3-arch1.2", backend: Vulkan }

**Comment by pablo-lua** [comment]
Looks like code hit https://github.com/gfx-rs/wgpu/blob/trunk/naga/src/back/glsl/mod.rs#L1183 for some reason and caused a lot of errors because an `Mutex` panicked in another thread, so the source of the error is the thread and variables that we used in this another thread.

**Comment by nametable** [comment]
I can also repro this on M1 Mac with Bevy 0.13.2
```
2024-04-07T11:30:02.803992Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-04-07T11:30:03.277576Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-04-07T11:30:03.328209Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.2.1 ", kernel: "23.2.0", cpu: "Apple M1", core_count: "8", memory: "8.0 GiB" }
thread 'Compute Task Pool (3)' panicked at /Users/nametable/.cargo/registry/src/index.crates.io-6f17d22bba15001f/naga-0.19.2/src/back/glsl/mod.rs:1183:44:
internal error: entered unreachable code
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_core_pipeline::upscaling::prepare_view_upscaling_pipelines`!
thread 'Compute Task Pool (0)' panicked at /Users/nametable/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.13.2/src/pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
thread 'main' panicked at /Users/nametable/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by nametable** [comment]
When compiling in `release` mode the crash does not occur, either on Linux or MacOS, so its just when the binary is in a workspace and compiled in `debug`

**Comment by nametable** [comment]
Maybe the better question to ask is why is resulting binary different between inside or outside a workspace, even when the source and `Cargo.lock` has not changed?

**Comment by tehnarenok** [comment]
Try to add this line `resolver=2` in root Cargo.toml
```
[workspace]
resolver = "2"
```
https://bevyengine.org/learn/quick-start/getting-started/setup/#cargo-workspaces

**Comment by nametable** [comment]
Thanks! I'm not sure how I missed that :man_facepalming: . With that setting, it now does not crash during runtime.
