### ISSUE TITLE
Some KTX2 Images fail to load

### ISSUE THREAD

**Issue by DGriffin91** [bevyengine/bevy#13289]
## Bevy version Main d9d305dab5b3b7a12a634ea7adb5c5a4c6406ec1 and 0.13

When loading the KTX2 file I get the error:
```
thread 'Compute Task Pool (21)' panicked at \.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.19.4\src\util\device.rs:174:26:
range end index 1164112 out of range for slice of length 1163552
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_render::texture::image::Image>`!
thread 'Compute Task Pool (21)' panicked at \.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.13.2\src\pipelined_rendering.rs:49:67:
called `Result::unwrap()` on an `Err` value: RecvError
```

This is the source PNG (from [San Miguel](https://casual-effects.com/data/)):
![muros_b](https://github.com/bevyengine/bevy/assets/33357138/0c92c2d0-b695-471f-a922-8ced4a36e8e9)
This is the KTX2 file generated by [kram](https://github.com/alecazam/kram): 
[muros_b.zip](https://github.com/bevyengine/bevy/files/15258333/muros_b.zip)

I was able to successfully load and view the image in [NVIDIA Texture Tools Exporter](https://developer.nvidia.com/texture-tools-exporter). I also tried using NVIDIA Texture Tools Exporter to generate a KTX2 file from the PNG and got the same error.

The KTX2 file was generated with kram via: 
`kram encode -f bc7 -type 2d -srgb -i muros_b.png -o muros_b.ktx2`

**Comment by Braymatter** [comment]
I'm also running into this with several png images, loaded with the basis-universal feature enabled

**Comment by janhohenheim** [comment]
Blocked by: https://github.com/gfx-rs/wgpu/issues/7677

The workaround for this right now is to trim or pad the texture so its size is a power of two.
