### ISSUE TITLE
Shader examples crash randomly on startup

### ISSUE THREAD

**Issue by jonhor** [bevyengine/bevy#1359]
**Bevy version**

master (61c9a40fdedda31a686a24447688004615ac1ba7)

**Operating system & version**

windows 10 / macOS

**What you did**

run `cargo run --example hot_shader_reloading`

**What you expected to happen**

example should run successfully

**What actually happened**

example failed with error
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/bevy_render/src/pipeline/pipeline_compiler.rs:80:49```

**Additional information**

running the example multiple times gives a seemingly random distribution between the mentioned error state and successful startups

**Comment by visualcode-t** [comment]
I have the same problem (Windows 10 - 19042.782).

After experiencing the issue, I attempted to see how "random" it was. I found something odd, after running it 10,000 times (non-exaggeratory) I didn't receive a single crash. But, **EVERY** time I reboot, the crash happens the first time I run `cargo run`.

<details>
<summary>Back_trace</summary>

```
E:\bevy-master>cargo run --example hot_shader_reloading
    Finished dev [unoptimized + debuginfo] target(s) in 5.44s
     Running `target\debug\examples\hot_shader_reloading.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates\bevy_render\src\pipeline\pipeline_compiler.rs:80:49
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:217
   9: std::panicking::rust_panic_with_hook
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:526
  10: std::panicking::begin_panic_handler
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:437
  11: core::panicking::panic_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:85
  12: core::panicking::panic
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libcore\panicking.rs:50
  13: core::option::Option<bevy_render::shader::shader::Shader*>::unwrap<bevy_render::shader::shader::Shader*>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\macros\mod.rs:10
  14: bevy_render::pipeline::pipeline_compiler::PipelineCompiler::compile_shader
             at .\crates\bevy_render\src\pipeline\pipeline_compiler.rs:80
  15: bevy_render::pipeline::pipeline_compiler::PipelineCompiler::compile_pipeline
             at .\crates\bevy_render\src\pipeline\pipeline_compiler.rs:137
  16: bevy_render::draw::DrawContext::set_pipeline
             at .\crates\bevy_render\src\draw.rs:179
  17: bevy_render::pipeline::render_pipelines::draw_render_pipelines_system
             at .\crates\bevy_render\src\pipeline\render_pipelines.rs:139
  18: core::ops::function::Fn::call<fn(bevy_render::draw::DrawContext, bevy_ecs::resource::resource_query::ResMut<bevy_render::renderer::render_resource::render_resource_bindings::RenderResourceBindings>, bevy_ecs::resource::resource_query::Res<bevy_render::ren
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:72
  19: core::ops::function::impls::{{impl}}::call_mut<tuple<bevy_render::draw::DrawContext, bevy_ecs::resource::resource_query::ResMut<bevy_render::renderer::render_resource::render_resource_bindings::RenderResourceBindings>, bevy_ecs::resource::resource_query::
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:253
  20: bevy_ecs::system::into_system::{{impl}}::system::{{closure}}<fn(bevy_render::draw::DrawContext, bevy_ecs::resource::resource_query::ResMut<bevy_render::renderer::render_resource::render_resource_bindings::RenderResourceBindings>, bevy_ecs::resource::resou
             at .\crates\bevy_ecs\src\system\into_system.rs:237
  21: alloc::boxed::{{impl}}::call_mut<tuple<mut bevy_ecs::system::into_system::SystemState*, bevy_ecs::core::world::World*, bevy_ecs::resource::resources::Resources*>,FnMut<tuple<mut bevy_ecs::system::into_system::SystemState*, bevy_ecs::core::world::World*, b
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\boxed.rs:1088
  22: bevy_ecs::system::into_system::{{impl}}::run_unsafe<tuple<>>
             at .\crates\bevy_ecs\src\system\into_system.rs:125
  23: bevy_ecs::schedule::stage_executor::{{impl}}::run_systems::{{closure}}::{{closure}}
             at .\crates\bevy_ecs\src\schedule\stage_executor.rs:374
  24: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
  25: async_executor::{{impl}}::spawn::{{closure}}<tuple<>,core::future::from_generator::GenFuture<generator-0>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:138
  26: core::future::from_generator::{{impl}}::poll<generator-0>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\future\mod.rs:78
  27: async_task::raw::RawTask<core::future::from_generator::GenFuture<generator-0>, tuple<>, closure-0>::run<core::future::from_generator::GenFuture<generator-0>,tuple<>,closure-0>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\raw.rs:489
  28: async_task::runnable::Runnable::run
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\runnable.rs:309
  29: async_executor::Executor::try_tick
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:175
  30: bevy_tasks::task_pool::TaskPool::scope<closure-0,tuple<>>
             at .\crates\bevy_tasks\src\task_pool.rs:214
  31: bevy_ecs::schedule::stage_executor::ParallelSystemStageExecutor::run_systems
             at .\crates\bevy_ecs\src\schedule\stage_executor.rs:302
  32: bevy_ecs::schedule::stage_executor::{{impl}}::execute_stage
             at .\crates\bevy_ecs\src\schedule\stage_executor.rs:452
  33: bevy_ecs::schedule::stage::SystemStage::run_once
             at .\crates\bevy_ecs\src\schedule\stage.rs:103
  34: bevy_ecs::schedule::stage::{{impl}}::run
             at .\crates\bevy_ecs\src\schedule\stage.rs:137
  35: bevy_ecs::schedule::Schedule::run_once
             at .\crates\bevy_ecs\src\schedule\mod.rs:149
  36: bevy_ecs::schedule::{{impl}}::run
             at .\crates\bevy_ecs\src\schedule\mod.rs:189
  37: bevy_ecs::schedule::Schedule::initialize_and_run
             at .\crates\bevy_ecs\src\schedule\mod.rs:156
  38: bevy_app::app::App::update
             at .\crates\bevy_app\src\app.rs:56
  39: bevy_winit::winit_runner_with::{{closure}}
             at .\crates\bevy_winit\src\lib.rs:441
  40: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-1>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:203
  41: alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\boxed.rs:1088
  42: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:245
  43: std::panic::{{impl}}::call_once<tuple<>,closure-0>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  44: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
  45: winit::platform_impl::platform::window::TASKBAR_LIST::__getit
  46: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
  47: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  48: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  49: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:239
  50: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::move_state_to<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:341
  51: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::main_events_cleared<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:227
  52: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:676
  53: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1967
  54: std::panic::{{impl}}::call_once<isize,closure-0>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  55: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:348
  56: winit::platform_impl::platform::window::TASKBAR_LIST::__getit
  57: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:325
  58: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  59: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  60: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple<>>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:2151
  61: DefSubclassProc
  62: DefSubclassProc
  63: CallWindowProcW
  64: DispatchMessageW
  65: SendMessageTimeoutW
  66: KiUserCallbackDispatcher
  67: NtUserDispatchMessage
  68: DispatchMessageW
  69: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-1>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:218
  70: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:188
  71: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
             at C:\Users\Visua\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\event_loop.rs:154
  72: bevy_winit::run<closure-1>
             at .\crates\bevy_winit\src\lib.rs:139
  73: bevy_winit::winit_runner_with
             at .\crates\bevy_winit\src\lib.rs:449
  74: bevy_winit::winit_runner
             at .\crates\bevy_winit\src\lib.rs:179
  75: core::ops::function::Fn::call<fn(bevy_app::app::App),tuple<bevy_app::app::App>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:72
  76: alloc::boxed::{{impl}}::call<tuple<bevy_app::app::App>,Fn<tuple<bevy_app::app::App>>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\boxed.rs:1095
  77: bevy_app::app::App::run
             at .\crates\bevy_app\src\app.rs:67
  78: bevy_app::app_builder::AppBuilder::run
             at .\crates\bevy_app\src\app_builder.rs:49
  79: hot_shader_reloading::main
             at .\examples\shader\hot_shader_reloading.rs:16
  80: std::rt::lang_start::{{closure}}<tuple<>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  81: std::rt::lang_start_internal::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:52
  82: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:348
  83: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panicking.rs:325
  84: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\panic.rs:394
  85: std::rt::lang_start_internal
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9\/src\libstd\rt.rs:51
  86: std::rt::lang_start<tuple<>>
             at C:\Users\Visua\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
  87: main
  88: invoke_main
             at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  89: __scrt_common_main_seh
             at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  90: BaseThreadInitThunk
  91: RtlUserThreadStart
```
</details>

**Comment by bjorn3** [comment]
Panic happens at https://github.com/bevyengine/bevy/blob/bff44f76ec8a532b0cac88fa02cc2583a2e860e1/crates/bevy_render/src/pipeline/pipeline_compiler.rs#L80

**Comment by jh2804** [comment]
After some additional testing I discovered varying behavior depending on the platform, which might come down to different caching strategies in  `shaderc` / `bevy-glsl-to-spirv`. 

#### Windows

The error only occurs the first time the shader has to be compiled / loaded? This is consistent with visualcode-t results.

#### macOS (arm64)

The error can occur every time the example is run, even if the shader files were not modified.

**Comment by cart** [comment]
Yeah this feels like a shader io timing issue to me. Possibly related to our recent "incrementalize rendering" efforts. Or maybe it has just always been a problem with this example (which is relatively new). `hot_shader_reloading` is the only example that loads a shader from disk. I'm guessing we don't hit this on any of the other shader examples.

**Comment by jh2804** [comment]
You are right. I did some debugging and by the time `compile_pipeline` and `compile_shader` are called, the whole asset loading call chain (`load_async`, `load`, `create_asset_in_load_context`, sending `AssetLifecycleEvent::Create` to update the asset store) hasn't quite finished.  A possible solution could be to create a special synchronization point for required shader assets in the pipeline compiler. 

Sorry if this is all obvious information :sweat_smile:.

**Comment by jh2804** [comment]
I think another solution could be to keep track of all pipelines and their shader dependencies, listening to `AssetEvent::Created` events from `Assets<Shader>` and only starting the compilation once required shaders are in the asset store.

**Comment by mtsr** [comment]
Definitely related to loading shaders from disk. Any time I modify a shader, it crashes the first time and works fine the second time. Hot shader reloading still works fine, when modifying shaders while running.

**Comment by gajop** [comment]
This is my current workaround, probably similar to what @jh2804  is suggesting.

```rust
#[derive(Default)]
struct AssetsLoading {
    vertex_shader: Handle<Shader>,
    fragment_shader: Handle<Shader>,
    loaded: bool,
}

fn setup_asset_loading(asset_server: Res<AssetServer>, mut loading: ResMut<AssetsLoading>) {
    asset_server.watch_for_changes().unwrap();

    let vertex_shader = asset_server.load::<Shader, _>("shaders/shader.vert");
    let fragment_shader = asset_server.load::<Shader, _>("shaders/shader.frag");

    loading.fragment_shader = fragment_shader;
    loading.vertex_shader = vertex_shader;
}

fn check_assets_ready(
    asset_server: ResMut<AssetServer>,
    mut loading: ResMut<AssetsLoading>,
    mut commands: Commands,
    mut pipelines: ResMut<Assets<PipelineDescriptor>>,
    mut meshes: ResMut<Assets<Mesh>>,
    mut render_graph: ResMut<RenderGraph>,
) {
    if loading.loaded {
        return;
    }

    if asset_server.get_load_state(loading.fragment_shader.clone()) != LoadState::Loaded
        || asset_server.get_load_state(loading.vertex_shader.clone()) != LoadState::Loaded
    {
        return;
    }

    loading.loaded = true;

    let pipeline_handle = pipelines.add(PipelineDescriptor::default_config(ShaderStages {
        vertex: loading.vertex_shader.clone(),
        fragment: Some(loading.fragment_shader.clone()),
    }));
}
```

**Comment by mockersf** [comment]
shaders are not compiled before being loaded anymore
