### ISSUE TITLE
Integrated Intel graphics + GL backend crashes 3d scenes

### ISSUE THREAD

**Issue by Trashtalk217** [bevyengine/bevy#13627]
## Bevy version

Main, commit 4b996c75aba325e004d18903b83ab6767688cea5

## Relevant system information

Rust version 1.78.0, Linux manjaro. Relevant rendering information: 

```ignore
INFO bevy_render::renderer: AdapterInfo { name: "Mesa Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```

See also the logs.

I will test this later with wgpu.

## What you did

I ran `cargo run --example 3d_scene` on the latest commit.

## What went wrong

It threw a bunch of errors and crashed.

## Additional information

Logs:
```
2024-06-01T20:03:13.864539Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 24.0.1 Manjaro Linux", kernel: "6.9.2-1-MANJARO", cpu: "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz", core_count: "4", memory: "7.6 GiB" }
2024-06-01T20:03:13.915181Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
2024-06-01T20:03:13.915818Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1.6666666666666667    
2024-06-01T20:03:14.099046Z  INFO bevy_render::renderer: AdapterInfo { name: "Mesa Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
2024-06-01T20:03:14.958217Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
2024-06-01T20:03:16.871515Z ERROR wgpu_core::device::global: Device::create_render_pipeline error: Internal error in ShaderStages(FRAGMENT) shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias    
2024-06-01T20:03:16.871616Z ERROR wgpu::backend::wgpu_core: Shader translation error for stage ShaderStages(FRAGMENT): gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias    
2024-06-01T20:03:16.871656Z ERROR wgpu::backend::wgpu_core: Please report it to https://github.com/gfx-rs/wgpu    
2024-06-01T20:03:16.871723Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread 'Async Compute Task Pool (1)' panicked at /home/******/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.4/src/backend/wgpu_core.rs:3006:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in ShaderStages(FRAGMENT) shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread '<unnamed>' panicked at /home/******/Programming/bevy/crates/bevy_render/src/render_resource/pipeline_cache.rs:640:28:
index out of bounds: the len is 0 but the index is 4
Encountered a panic in system `bevy_render::renderer::render_system`!
```
My guess is that my lower-end GL hardware is the problem and I should install some Vulkan drivers, but it's probably still worth reporting.

**Comment by alice-i-cecile** [comment]
Can you double-check this on `0.13.3` to double-check that this isn't a regression for us?

**Comment by Trashtalk217** [comment]
I double-checked 0.13.2 (which I believe is the last version) and got precisely the same error. This is not a regression.

**Comment by Trashtalk217** [comment]
I installed `vulkan-intel` from the Official Repositories which has solved the issue.

**Comment by alice-i-cecile** [comment]
Awesome. I'm glad to have this documented in our issues, but I'm going to close this as "won't fix". I don't think that we make any promises about GL support for our rendering stack by default.
