### ISSUE TITLE
Panic when `PbrPlugin.add_default_deferred_lighting_plugin = false`

### ISSUE THREAD

**Issue by eero-lehtinen** [bevyengine/bevy#14226]
## Bevy version

latest ec1aa48fc

## Relevant system information
```
rust 1.79
SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.9.7-arch1-1", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "555.58.02", backend: Vulkan }
```

## What you did

Change `PbrPlugin` settings in 3d_scene.rs example and run it:
```rs
//! A simple 3D scene with light shining over a cube sitting on a plane.

use bevy::{pbr::PbrPlugin, prelude::*};

fn main() {
    App::new()
        .add_plugins(DefaultPlugins.set(PbrPlugin {
            prepass_enabled: true,
            add_default_deferred_lighting_plugin: false,
            use_gpu_instance_buffer_builder: true,
        }))
        .add_systems(Startup, setup)
        .run();
}

/// set up a simple 3D scene
fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    // circular base
    commands.spawn(PbrBundle {
        mesh: meshes.add(Circle::new(4.0)),
        material: materials.add(Color::WHITE),
        transform: Transform::from_rotation(Quat::from_rotation_x(-std::f32::consts::FRAC_PI_2)),
        ..default()
    });
    // cube
    commands.spawn(PbrBundle {
        mesh: meshes.add(Cuboid::new(1.0, 1.0, 1.0)),
        material: materials.add(Color::srgb_u8(124, 144, 255)),
        transform: Transform::from_xyz(0.0, 0.5, 0.0),
        ..default()
    });
    // light
    commands.spawn(PointLightBundle {
        point_light: PointLight {
            shadows_enabled: true,
            ..default()
        },
        transform: Transform::from_xyz(4.0, 8.0, 4.0),
        ..default()
    });
    // camera
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(-2.5, 4.5, 9.0).looking_at(Vec3::ZERO, Vec3::Y),
        ..default()
    });
}
```

## What went wrong

A panic happens.

## Additional information

```shell
❯ cargo run --example 3d_scene
   Compiling bevy v0.15.0-dev (/home/eero/repos/bevy2)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.60s
     Running `target/debug/examples/3d_scene`
2024-07-08T19:03:31.431116Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux rolling EndeavourOS", kernel: "6.9.7-arch1-1", cpu: "AMD Ryzen 7 5800X3D 8-Core Processor", core_count: "8", memory: "31.3 GiB" }
2024-07-08T19:03:31.513257Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "555.58.02", backend: Vulkan }
thread 'main' panicked at /home/eero/repos/bevy2/crates/bevy_render/src/render_graph/graph.rs:154:26:
InvalidNode(DeferredLightingPass)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:262:26:
cannot access a Thread Local Storage value during or after destruction: AccessError
fatal runtime error: failed to initiate panic, error 5
fish: Job 1, 'cargo run --example 3d_scene' terminated by signal SIGABRT (Abort)
```

**Comment by eero-lehtinen** [comment]
Seems to work nowadays.
