### ISSUE TITLE
AssertionFailed in std::sync::once when starting app on release

### ISSUE THREAD

**Issue by lynn2910** [bevyengine/bevy#14222]
## Bevy version

0.14

## Relevant system information

Cargo version: cargo 1.79.0 (ffa9cf99a 2024-06-03)
OS: Windows 11 (build 22631.3810)

Adapter info:
```ignore
AdapterInfo { name: "NVIDIA GeForce RTX 4060 Laptop GPU", vendor: 4318, device: 10400, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "555.99", backend: Vulkan }
```

## What you did

I cloned the bevy template  given for the jam (https://github.com/TheBevyFlock/bevy-template)

After cloning it, I simply ran it on release mode

## What went wrong

I got the following output:
```
thread 'main' panicked at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\std\src\sync\once.rs:208:20:
assertion failed: state_and_queue.addr() & STATE_MASK == RUNNING
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\bevy_template.exe` (exit code: 101)
```

## Additional information

The error occurs only on release, it doesn't trigger on debug

<details>
  <summary>Backtrace:</summary>

```
thread 'main' panicked at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081\library\std\src\sync\once.rs:208:20:
assertion failed: state_and_queue.addr() & STATE_MASK == RUNNING
stack backtrace:
   0:     0x7ffa14a43c48 - std::backtrace_rs::backtrace::dbghelp64::trace
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
   1:     0x7ffa14a43c48 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ffa14a43c48 - std::sys_common::backtrace::_print_fmt
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\sys_common\backtrace.rs:68
   3:     0x7ffa14a43c48 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\sys_common\backtrace.rs:44
   4:     0x7ffa14a74f09 - core::fmt::rt::Argument::fmt
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\fmt\rt.rs:165
   5:     0x7ffa14a74f09 - core::fmt::write
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\fmt\mod.rs:1157
   6:     0x7ffa14a3a3e1 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\io\mod.rs:1832
   7:     0x7ffa14a43a26 - std::sys_common::backtrace::print
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\sys_common\backtrace.rs:34
   8:     0x7ffa14a46b88 - std::panicking::default_hook::closure$1
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:271
   9:     0x7ffa14a467f7 - std::panicking::default_hook
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:298
  10:     0x7ffa14a47188 - std::panicking::rust_panic_with_hook
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:795
  11:     0x7ffa14a47009 - std::panicking::begin_panic_handler::closure$0
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:656
  12:     0x7ffa14a445bf - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\sys_common\backtrace.rs:171
  13:     0x7ffa14a46cf8 - std::panicking::begin_panic_handler
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
  14:     0x7ffa14a9d7d4 - core::panicking::panic_fmt
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
  15:     0x7ffa14a9d89d - core::panicking::panic
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:146
  16:     0x7ffa14a9c9b0 - std::sys::sync::once::queue::Once::call
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\sys\sync\once\queue.rs:190
  17:     0x7ff65781db5c - _guard_xfg_dispatch_icall_nop
  18:     0x7ff65781009f - __ImageBase
  19:     0x7ff65780cfc5 - __ImageBase
  20:     0x7ff6577de0ba - __ImageBase
  21:     0x7ff9afbd3e93 - bevy_app::app::App::add_boxed_plugin::hdf22ae67fccd9396
  22:     0x7ff6577d8b1c - __ImageBase
  23:     0x7ff9afbd3e93 - bevy_app::app::App::add_boxed_plugin::hdf22ae67fccd9396
  24:     0x7ff65781b226 - <bevy_template::GamePlugin as bevy_app::plugin::Plugin>::build::h998de65a376608c8
  25:     0x7ff9afbd3e93 - bevy_app::app::App::add_boxed_plugin::hdf22ae67fccd9396
  26:     0x7ff65781c66d - <bevy_template::GamePlugin as bevy_app::plugin::Plugin>::build::h998de65a376608c8
  27:     0x7ff65781b5f6 - <bevy_template::GamePlugin as bevy_app::plugin::Plugin>::build::h998de65a376608c8
  28:     0x7ff65781b60c - <bevy_template::GamePlugin as bevy_app::plugin::Plugin>::build::h998de65a376608c8
  29:     0x7ffa14a2bb9e - std::rt::lang_start_internal
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\rt.rs:141
  30:     0x7ff65781c9ec - main
  31:     0x7ff65781d1ac - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  32:     0x7ff65781d1ac - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  33:     0x7ffa631c257d - BaseThreadInitThunk
  34:     0x7ffa6432af28 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\bevy_template.exe` (exit code: 101)
```
</details>

**Comment by alice-i-cecile** [comment]
>  21:     0x7ff9afbd3e93 - bevy_app::app::App::add_boxed_plugin::hdf22ae67fccd9396

This is the most interesting line in the backtrace for me. I have no idea what's going on here though: [`Once`](https://doc.rust-lang.org/std/sync/struct.Once.html) should generally not be panicking unless something really weird is going on, and release-mode only is particularly bizarre.

**Comment by lynn2910** [comment]
Updating the code fixed it (by simply getting the last commits), but it wasn't a regular build issue like needing to do `cargo clean`. Not sure what caused the original problem.
