### ISSUE TITLE
3D Rendering / Visibility range web example panicked

### ISSUE THREAD

**Issue by s-mayrh** [bevyengine/bevy#14473]
## Bevy version

WASM build currently hosted at https://bevyengine.org/examples/3d-rendering/visibility-range/
Likely 0.14

## Relevant system information

Raspberry Pi 4 Model B Rev 1.4
CPU: 4 × ARM Cortex-A72 @ 2.0 GHz
GPU: Broadcom VideoCore VI (VC6/V3D 4.2.14) @ 600 MHz
RAM: 8 GiB
Video memory: 7807 MB, Unified memory: yes (from glxinfo)

stable-aarch64-unknown-linux-gnu
OS: Manjaro ARM

All package versions are **the latest from my distribution**:

firefox 123.0-1
chromium 122.0.6261.69-1

kernel-release: 6.6.33-2-MANJARO-RPI4
mesa 24.0.2-1
mesa-utils 9.0.0-3
vulkan-broadcom 24.0.2-1
vulkan-mesa-layers 24.0.2-1
vulkan-headers 1:1.3.276-1
vulkan-icd-loader 1:1.3.276-1
vulkan-tools 1:1.3.269-1

## What you did

I opened the example for 3D Rendering / Visibility range on the Bevy Website 

## What went wrong

It hangs after loading, no mesh displayed

## Additional information

![Screenshot 2024-07-25 at 14-56-09 Visibility range](https://github.com/user-attachments/assets/2830a4d7-05b0-40dd-aba2-2d9a23f2d729)

Log from Firefox:
```
ERROR  Device::create_render_pipeline error: Error matching ShaderStages(VERTEX) shader requirements against the pipeline log.target = "wgpu_core::device::global";
log.module_path = "wgpu_core::device::global";
log.file = "/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/device/global.rs";
log.line = 1636; wasm_example.js:435:21
ERROR  Handling wgpu errors as fatal by default log.target = "wgpu::backend::wgpu_core";
log.module_path = "wgpu::backend::wgpu_core";
log.file = "/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs";
log.line = 2995; wasm_example.js:435:21
panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Error matching ShaderStages(VERTEX) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 12 } is not available in the pipeline layout
    Buffer structure size 1024, added to one element of an unbound array, if it's the last field, ended up greater than the given `min_binding_size`



Stack:

__wbg_get_imports/imports.wbg.__wbg_new_abda76e883ba8a5f@https://bevy-webgl2-examples.pages.dev/3D%20Rendering/visibility-range/wasm_example.js:1842:21
@:wasm-function[53645]:0x127dc03
@:wasm-function[15632]:0xfc857d
@:wasm-function[28857]:0x11cd8ee
@:wasm-function[15494]:0xfc1827
@:wasm-function[24188]:0x10e774d
@:wasm-function[572]:0x1f4fe3
@:wasm-function[15112]:0xf927e2
@:wasm-function[52948]:0x1279765
@:wasm-function[2039]:0x6ffe35
@:wasm-function[14792]:0xf5019c
@:wasm-function[4654]:0x9d194b
@:wasm-function[10823]:0xdd460d
@:wasm-function[6864]:0xbe0fc3
@:wasm-function[3049]:0x809fe5
@:wasm-function[5038]:0xa295d0
@:wasm-function[32277]:0x11fc9a7
@:wasm-function[32065]:0x11fa99d
__wbg_adapter_45@https://bevy-webgl2-examples.pages.dev/3D%20Rendering/visibility-range/wasm_example.js:229:10
real@https://bevy-webgl2-examples.pages.dev/3D%20Rendering/visibility-range/wasm_example.js:210:20


wasm_example.js:1858:21
Uncaught RuntimeError: unreachable executed
    __wbg_adapter_45 https://bevy-webgl2-examples.pages.dev/3D Rendering/visibility-range/wasm_example.js:229
    real https://bevy-webgl2-examples.pages.dev/3D Rendering/visibility-range/wasm_example.js:210

Missing resource in locale de: devtools/client/toolbox.ftl 
```
Log from Chromium:
```
ERROR  Device::create_render_pipeline error: Error matching ShaderStages(VERTEX) shader requirements against the pipeline log.target = "wgpu_core::device::global";log.module_path = "wgpu_core::device::global";log.file = "/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/device/global.rs";log.line = 1636;
wasm_example.js:435 ERROR  Handling wgpu errors as fatal by default log.target = "wgpu::backend::wgpu_core";log.module_path = "wgpu::backend::wgpu_core";log.file = "/Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs";log.line = 2995;
wasm_example.js:1858 panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Error matching ShaderStages(VERTEX) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 12 } is not available in the pipeline layout
    Buffer structure size 1024, added to one element of an unbound array, if it's the last field, ended up greater than the given `min_binding_size`



Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (https://bevy-webgl2-examples.pages.dev/3D%20Rendering/visibility-range/wasm_example.js:1842:21)
    at wasm://wasm/05f39d3a:wasm-function[53645]:0x127dc03
    at wasm://wasm/05f39d3a:wasm-function[15632]:0xfc857d
    at wasm://wasm/05f39d3a:wasm-function[28857]:0x11cd8ee
    at wasm://wasm/05f39d3a:wasm-function[15494]:0xfc1827
    at wasm://wasm/05f39d3a:wasm-function[24188]:0x10e774d
    at wasm://wasm/05f39d3a:wasm-function[572]:0x1f4fe3
    at wasm://wasm/05f39d3a:wasm-function[15112]:0xf927e2
    at wasm://wasm/05f39d3a:wasm-function[52948]:0x1279765
    at wasm://wasm/05f39d3a:wasm-function[2039]:0x6ffe35


imports.wbg.__wbg_error_f851667af71bcfc6 @ wasm_example.js:1858
05f39d3a:0xfc85a3 Uncaught RuntimeError: unreachable
    at 05f39d3a:0xfc85a3
    at 05f39d3a:0x11cd8ee
    at 05f39d3a:0xfc1827
    at 05f39d3a:0x10e774d
    at 05f39d3a:0x1f4fe3
    at 05f39d3a:0xf927e2
    at 05f39d3a:0x1279765
    at 05f39d3a:0x6ffe35
    at 05f39d3a:0xf5019c
    at 05f39d3a:0x9d194b
/assets/examples/models/FlightHelmet/FlightHelmet_Materials_LensesMat_BaseColor.png.meta:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
```

**Comment by rparrett** [comment]
Seeing the same with
```rust
AdapterInfo { name: "ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Unspecified Version)", vendor: 4203, device: 0, device_type: IntegratedGpu, driver: "WebGL 2.0 (OpenGL ES", driver_info: "3.0 Chromium)", backend: Gl }
 ```

**Comment by 4ry1337** [comment]
#23035 same
