### ISSUE TITLE
`Slab not found` error when running the `loading_screen` example.

### ISSUE THREAD

**Issue by Olle-Lukowski** [bevyengine/bevy#14845]
## Bevy version

current main

## Relevant system information

I am on the latest stable version of macOS, latest stable rust too.

```ignore
AdapterInfo { name: "Apple M3", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

Run `cargo r --example loading_screen`, then, press 1, wait for load, press 2, wait for load, press 1 again, crash!

## What went wrong

On the bevy website this seems to work properly, not sure if its a regression in main, or a macOS specific issue...

Full output:
```
2024-08-21T08:15:31.197248Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.6.1 ", kernel: "23.6.0", cpu: "Apple M3", core_count: "8", memory: "16.0 GiB" }
2024-08-21T08:15:31.277083Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M3", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-08-21T08:15:31.685286Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
thread 'Compute Task Pool (3)' panicked at crates/bevy_render/src/mesh/allocator.rs:674:21:
internal error: entered unreachable code: Slab not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::mesh::allocator::allocate_and_free_meshes`!
```

## Additional information
Decided to try it on 0.14.1, and there it works fine. So it seems like a regression, not sure if it is macOS specific, but for now I'll tag it as such.

**Comment by LikeLakers2** [comment]
Doesn't appear to be MacOS-specific? I tried replicating it on my machine, and got the crash too:

```log
2024-08-21T08:54:45.861166Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 10 Home", kernel: "19045", cpu: "AMD Ryzen 5 1400 Quad-Core Processor", core_count: "4", memory: "16.0 GiB" }
2024-08-21T08:54:46.482231Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3060", vendor: 4318, device: 9476, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "552.12", backend: Vulkan }
2024-08-21T08:54:47.719371Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
thread 'Compute Task Pool (1)' panicked at crates\bevy_render\src\mesh\allocator.rs:674:21:
internal error: entered unreachable code: Slab not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::mesh::allocator::allocate_and_free_meshes`!
```

This was on commit 6e2f96f2224032e04e77b993ad4c06d76d49039f, compiled using `rustc 1.80.1 (3f5fd8dd4 2024-08-06)` with the `stable-x86_64-pc-windows-msvc` toolchain.

**Comment by BenjaminBrienen** [comment]
Works perfectly for me
```
     Running `target\debug\examples\loading_screen.exe`
2025-01-07T18:33:33.847956Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "26100", cpu: "12th Gen Intel(R) Core(TM) i7-12700H", core_count: "14", memory: "31.7 GiB" }
2025-01-07T18:33:34.229329Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) Iris(R) Xe Graphics", vendor: 32902, device: 18086, device_type: IntegratedGpu, driver: "Intel Corporation", driver_info: "101.6325", backend: Vulkan }
2025-01-07T18:33:35.545722Z  INFO bevy_winit::system: Creating new window App (0v1)
2025-01-07T18:38:33.439022Z  INFO bevy_window::system: No windows are open, exiting    
2025-01-07T18:38:33.447552Z  INFO bevy_winit::system: Closing window 0v1
2025-01-07T18:38:33.465944Z  INFO bevy_window::system: No windows are open, exiting
```

**Comment by brianreavis** [comment]
This issue should be closed because it was fixed in https://github.com/bevyengine/bevy/pull/14560
