### ISSUE TITLE
Picking sprite backend will panic with Ord violation

### ISSUE THREAD

**Issue by mgi388** [bevyengine/bevy#15258]
I discovered a panic in `bevy_picking_sprite` but the same code now exists in `main` due to the upstreaming, so I'm reporting an issue per [Discord request].

[Discord request]: https://discord.com/channels/691052431525675048/1236111180624297984/1285478171839565835

## Bevy version

`main`. I can provide more system information if requested, but I don't think it's relevant.

## What you did

Interacted with a sprite causing the sprite picking backend to run. Must have an invalid transform with NaNs.

## What went wrong

Panic.

```
thread 'Compute Task Pool (1)' panicked at library/core/src/slice/sort/shared/smallsort.rs:848:5:
Ord violation
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::slice::sort::shared::smallsort::panic_on_ord_violation
   3: core::slice::sort::shared::smallsort::bidirectional_merge
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/shared/smallsort.rs:841:13
   4: core::slice::sort::shared::smallsort::small_sort_general_with_scratch
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/shared/smallsort.rs:289:9
   5: core::slice::sort::stable::quicksort::quicksort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/quicksort.rs:79:9
   6: core::slice::sort::stable::quicksort::quicksort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/quicksort.rs:79:9
   7: core::slice::sort::stable::quicksort::quicksort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/quicksort.rs:79:9
   8: core::slice::sort::stable::drift::stable_quicksort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/drift.rs:272:5
   9: core::slice::sort::stable::drift::logical_merge
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/drift.rs:211:13
  10: core::slice::sort::stable::drift::sort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/drift.rs:96:28
  11: core::slice::sort::stable::driftsort_main
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/mod.rs:86:5
  12: core::slice::sort::stable::sort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/slice/sort/stable/mod.rs:47:5
  13: alloc::slice::stable_sort
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/alloc/src/slice.rs:867:5
  14: alloc::slice::<impl [T]>::sort_by
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/alloc/src/slice.rs:284:9
  15: bevy_picking_sprite::sprite_picking
             at /me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_picking_sprite-0.20.0/src/lib.rs:57:5
  16: core::ops::function::FnMut::call_mut
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/ops/function.rs:166:5
  17: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/524d806c62a82ecc0cf8634b94997ae506f4d6f9/library/core/src/ops/function.rs:294:13
  18: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6) .> Out>>::run::call_inner
             at /me/bevy/crates/bevy_ecs/src/system/function_system.rs:710:21
  19: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1,F2,F3,F4,F5,F6) .> Out>>::run
             at /me/bevy/crates/bevy_ecs/src/system/function_system.rs:713:17
  20: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /me/bevy/crates/bevy_ecs/src/system/function_system.rs:534:19
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_picking_sprite::sprite_picking`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

## Additional information

Original report: https://discord.com/channels/691052431525675048/1236111180624297984/1285475521697808404

**Comment by Victoronz** [comment]
The reason for the `Ord` violation is that NaNs are being compared equal to everything in this `sort_by` call, which does not form a total order.
This is fixable by wrapping the two floats in `FloatOrd` and using the normal `cmp` function instead.
This will order NaNs as less than every other value. Whether this is actually "correct" behavior for sprites I do not know, I am not familiar with sprite code.

**Comment by jnhyatt** [comment]
@mgi388 If you wouldn't mind checking your specific scenario against #15267 to verify it no longer panics, I'd appreciate it 🙂
