### ISSUE TITLE
`examples/ui/relative_cursor_position.rs` crashes if window is shrunk

### ISSUE THREAD

**Issue by shiki-saiki** [bevyengine/bevy#15661]
## Bevy version

v0.14.2

## \[Optional\] Relevant system information

OS: Windows 11

```
AdapterInfo { name: "AMD Radeon RX 6600", vendor: 4098, device: 29695, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "23.10.2 (AMD proprietary shader compiler)", backend: Vulkan }
```

## What you did

Run the example `relative_cursor_position`.

## What went wrong

If the window is shrunk small enough, it crashes.

## Additional information

```
ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at C:\dev\rust\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.20.1\src\backend\wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(104, 1, Vulkan)>`
    In a set_viewport command
    Viewport has invalid rect Rect { x: 200.0, y: 100.0, w: 600.0, h: 600.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target (1280, 625, 1)
```

**Comment by BenjaminBrienen** [comment]
```
     Running `target\debug\examples\relative_cursor_position.exe`
2024-10-26T23:13:21.207246Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "22631", cpu: "12th Gen Intel(R) Core(TM) i7-12700H", core_count: "14", memory: "31.7 GiB" }
2024-10-26T23:13:21.587930Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2060", vendor: 4318, device: 7944, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "561.09", backend: Vulkan }
2024-10-26T23:13:22.657612Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
2024-10-26T23:13:54.944161Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at C:\Users\BenjaminBrienen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-22.1.0\src\backend\wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In RenderPass::end
    In a set_viewport command
      Viewport has invalid rect Rect { x: 200.0, y: 100.0, w: 425.0, h: 294.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target (425, 294, 1)     


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::renderer::render_system`!
```

**Comment by BenjaminBrienen** [comment]
This happens even if the window is made slightly smaller
```
     Running `target\debug\examples\relative_cursor_position.exe`
2024-10-26T23:15:46.235519Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "22631", cpu: "12th Gen Intel(R) Core(TM) i7-12700H", core_count: "14", memory: "31.7 GiB" }
2024-10-26T23:15:46.621190Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 2060", vendor: 4318, device: 7944, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "561.09", backend: Vulkan }
2024-10-26T23:15:47.494352Z  INFO bevy_winit::system: Creating new window "App" (0v1#4294967296)
2024-10-26T23:15:52.683968Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread '<unnamed>' panicked at C:\Users\BenjaminBrienen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-22.1.0\src\backend\wgpu_core.rs:3411:5:
wgpu error: Validation Error

Caused by:
  In RenderPass::end
    In a set_viewport command
      Viewport has invalid rect Rect { x: 200.0, y: 100.0, w: 600.0, h: 600.0 }; origin and/or size is less than or equal to 0, and/or is not contained in the render target (1230, 661, 1)    


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::renderer::render_system`!
```

**Comment by BenjaminBrienen** [comment]
Not fixed with #15988

**Comment by BenjaminBrienen** [comment]
I think the Camera Viewport needs to be updated when the window is resized.

**Comment by BenjaminBrienen** [comment]
Spawning the Camera2d with a Transform bundle instead allows resizing to work.

```rs
    commands.spawn((
        Camera2d,
        Transform::from_xyz(0., 0., 0.).looking_at(Vec3::ZERO, Vec3::Y),
    ));
```

![Image](https://github.com/user-attachments/assets/430257e4-ec97-4245-9b3f-2140280d7f38)
