### ISSUE TITLE
Bevy 0.14.2 android game with simple rendering logic crashes at start

### ISSUE THREAD

**Issue by wentao** [bevyengine/bevy#16764]
## Bevy version

0.14.2

## \[Optional\] Relevant system information

cargo 1.82.0 (8f40fc59f 2024-08-21)

```ignore
Adapter Gl AdapterInfo { name: "Android Emulator OpenGL ES Translator (Apple M1 Max)", vendor: 4203, device: 0, device_type: IntegratedGpu, driver: "OpenGL ES", driver_info: "3.0 (4.1 Metal - 88.1)", backend: Gl }log.target = "wgpu_core::instance"; log.module_path = "wgpu_core::instance"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/instance.rs"; log.line = 796;
```

## What you did

I setup a simple android project at https://github.com/80gen/bevy_ios_bug/tree/main/platforms/android/mini_android with main game code located at https://github.com/80gen/bevy_ios_bug/blob/main/crates/game/src/lib.rs

## What went wrong

The game crashes at start with the following error log

```ignore
wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.568 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.584 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.584 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.589 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.589 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.595 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `Cube` rather than `CubeArray`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.596 10064-10142 log event               com.egen.mini                        E  wgpu-hal heuristics assumed that the view dimension will be equal to `D2` rather than `D2Array`.
`D2` textures with `depth_or_array_layers == 1` are assumed to have view dimension `D2`
`D2` textures with `depth_or_array_layers > 1` are assumed to have view dimension `D2Array`
`D2` textures with `depth_or_array_layers == 6` are assumed to have view dimension `Cube`
`D2` textures with `depth_or_array_layers > 6 && depth_or_array_layers % 6 == 0` are assumed to have view dimension `CubeArray`log.target = "wgpu_hal::gles"; log.module_path = "wgpu_hal::gles"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/mod.rs"; log.line = 421;
2024-12-11 00:37:13.604 10064-10141 log event               com.egen.mini                        I  Only vertex shader is present. Creating an empty fragment shaderlog.target = "wgpu_hal::gles::device"; log.module_path = "wgpu_hal::gles::device"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs"; log.line = 401;
2024-12-11 00:37:14.604 10064-10138 RustStdoutStderr        com.egen.mini                        I  thread '<unnamed>' panicked at /Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs:1462:50:
2024-12-11 00:37:14.607 10064-10138 RustStdoutStderr        com.egen.mini                        I  Could not lock adapter context. This is most-likely a deadlock.
2024-12-11 00:37:14.607 10064-10138 RustStdoutStderr        com.egen.mini                        I  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-12-11 00:37:14.608 10064-10138 RustStdoutStderr        com.egen.mini                        I  Encountered a panic in system `bevy_render::renderer::render_system`!
2024-12-11 00:37:16.313 10064-10141 log event               com.egen.mini                        W  	Link: WARNING: Output of vertex shader '_vs2fs_location0' not read by fragment shader
WARNING: Output of vertex shader '_vs2fs_location7' not read by fragment shader
WARNING: Output of vertex shader '_vs2fs_location4' not read by fragment shader
log.target = "wgpu_hal::gles::device"; log.module_path = "wgpu_hal::gles::device"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/device.rs"; log.line = 430;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Device::create_render_pipeline error: Internal error in ShaderStages(FRAGMENT) shader: The selected version doesn't support Features(CUBE_TEXTURES_ARRAY)log.target = "wgpu_core::device::global"; log.module_path = "wgpu_core::device::global"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/device/global.rs"; log.line = 1636;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Shader translation error for stage ShaderStages(FRAGMENT): The selected version doesn't support Features(CUBE_TEXTURES_ARRAY)log.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs"; log.line = 1179;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Please report it to https://github.com/gfx-rs/wgpulog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs"; log.line = 1180;
2024-12-11 00:37:16.352 10064-10141 log event               com.egen.mini                        E  Handling wgpu errors as fatal by defaultlog.target = "wgpu::backend::wgpu_core"; log.module_path = "wgpu::backend::wgpu_core"; log.file = "/Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs"; log.line = 2995;
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  thread 'Async Compute Task Pool (0)' panicked at /Users/[...]/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  wgpu error: Validation Error
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  Caused by:
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I      In Device::create_render_pipeline
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I        note: label = `pbr_opaque_mesh_pipeline`
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I      Internal error in ShaderStages(FRAGMENT) shader: The selected version doesn't support Features(CUBE_TEXTURES_ARRAY)
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  
2024-12-11 00:37:16.352 10064-10138 RustStdoutStderr        com.egen.mini                        I  
2024-12-11 00:37:19.831 10064-10070 com.egen.mini           com.egen.mini                        I  Thread[3,tid=10070,WaitingInMainSignalCatcherLoop,Thread*=0xb400007ab278eb20,peer=0x12d803f8,"Signal Catcher"]: reacting to signal 3
2024-12-11 00:37:19.831 10064-10070 com.egen.mini           com.egen.mini                        I  
2024-12-11 00:37:19.935 10064-10070 com.egen.mini           com.egen.mini                        I  Wrote stack traces to tombstoned

**Comment by wentao** [comment]
I also submitted the same bug to wgpu https://github.com/gfx-rs/wgpu/issues/6701

**Comment by mockersf** [comment]
Is it something you can reproduce on an actual device?

From your log it's picking the OpenGL backend. I have the same issue if I run in the emulator on macOS, but forcing it to use vulkan makes it work. Vulkan detection works correctly on actual devices

**Comment by wentao** [comment]
> Is it something you can reproduce on an actual device?
> 
> From your log it's picking the OpenGL backend. I have the same issue if I run in the emulator on macOS, but forcing it to use vulkan makes it work. Vulkan detection works correctly on actual devices

Tested on actual device and it worked! So is this only affecting emulators? Is there a way to enforce emulator to use Vulkan?

**Comment by falloutmastermix-lgtm** [comment]
> Is it something you can reproduce on an actual device?
> 
> From your log it's picking the OpenGL backend. I have the same issue if I run in the emulator on macOS, but forcing it to use vulkan makes it work. Vulkan detection works correctly on actual devices

How do I make it work only on Vulkan on Android in mac emulator? I still get an error.

// Create plugins with conditional backend selection
let mut plugins = DefaultPlugins
.set(WindowPlugin {
primary_window: Some(Window {
title: "App".into(),
resolution: WindowResolution::new(400.0, 800.0),
..default()
}),
..default()
});

// If Android, add Vulkan
#[cfg(target_os = "android")]
{
plugins = plugins.set(RenderPlugin {
render_creation: RenderCreation::Automatic(WgpuSettings {
backends: Some(Backends::VULKAN),
..default()
}),
..default()
}); 
} 


.add_plugins(plugins)
