### ISSUE TITLE
(Android) Crash when there's more than eight touches at once.

### ISSUE THREAD

**Issue by BUGO07** [bevyengine/bevy#16798]
Bevy version: 0.15,
Android version: 14 (OneUI 6.1)

```
12-13 13:28:11.510 32446 32479 I RustStdoutStderr: thread '<unnamed>' panicked at /home/bugo07/.cargo/registry/src/index.crates.io-6f17d22bba15001f/android-activity-0.6.0/src/game_activity/input.rs:136:13:
12-13 13:28:11.510 32446 32479 I RustStdoutStderr: Pointer index 8 is out of bounds
12-13 13:28:11.510 32446 32479 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BUGO07** [comment]
it doesn't just close the app too, it's a full crash, doesn't start back up unless removed from recent apps and reran.

**Comment by BUGO07** [comment]
there's this error when i try to rerun the app without closing if from recent apps
```
12-13 13:42:57.798  5089  5244 I RustStdoutStderr: thread '<unnamed>' panicked at /home/bugo07/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.15.0/src/lib.rs:142:14:
12-13 13:42:57.798  5089  5244 I RustStdoutStderr: Failed to build event loop: RecreationAttempt
```

**Comment by BUGO07** [comment]
SystemInfo { os: "Android 14 SM-S711B", kernel: "5.10.198-android12-9-29559365-abS711BXXS5DXI3", cpu: "not available", core_count: "8", memory: "7.1 GiB" }

**Comment by BUGO07** [comment]
this is probably important and i left it out but im using GameActivity with cargo-ndk (just like the android_example)

**Comment by mockersf** [comment]
the panic is from https://github.com/rust-mobile/android-activity/blob/main/android-activity/src/game_activity/input.rs#L136

```rust
    pub fn pointer_at_index(&self, index: usize) -> Pointer<'_> {
        if index >= self.pointer_count() {
            panic!("Pointer index {} is out of bounds", index);
        }
        Pointer {
            inner: PointerImpl { event: self, index },
        }
    }
```

it's called by wind there: https://github.com/rust-windowing/winit/blob/4d5e68c6e23d9633051ed9c1382eb8bd978751f1/src/platform_impl/android/mod.rs#L331

```rust
motion_event.pointer_at_index(motion_event.pointer_index())
```

`pointer_count()` is:
```rust
    pub fn pointer_count(&self) -> usize {
        self.ga_event.pointerCount as usize
    }
```

and `index` is:
```rust
    pub fn pointer_index(&self) -> usize {
        let action = self.ga_event.action as u32;
        let index = (action & ndk_sys::AMOTION_EVENT_ACTION_POINTER_INDEX_MASK)
            >> ndk_sys::AMOTION_EVENT_ACTION_POINTER_INDEX_SHIFT;
        index as usize
    }
```

not sure why those would crash... but nothing we can do on Bevy side, it's either on `winit` or on `android-activity` side

**Comment by BUGO07** [comment]
Yeah I made an issue on android-activity GitHub aswell

**Comment by BUGO07** [comment]
It may even me because of ndk, I'll see what they say on the android-activity gh

**Comment by mockersf** [comment]
https://github.com/rust-mobile/android-activity/issues/175
