### ISSUE TITLE
`mixed_lighting` example crashed

### ISSUE THREAD

**Issue by lomirus** [bevyengine/bevy#16880]
## Bevy version

main@b9123e74b6838b58c33badff73d176441f8a33cc

## Relevant system information

```ignore
SystemInfo { os: "MacOS 15.1.1 Sequoia", kernel: "24.1.0", cpu: "Apple M1 Pro", core_count: "10", memory: "32.0 GiB" }
AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
```

## What you did

```
cargo run --release --features="jpeg"  --example mixed_lighting
```

## What went wrong

```
2024-12-18T08:21:02.715543Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 15.1.1 Sequoia", kernel: "24.1.0", cpu: "Apple M1 Pro", core_count: "10", memory: "32.0 GiB" }
2024-12-18T08:21:02.798478Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-12-18T08:21:02.996983Z  INFO bevy_winit::system: Creating new window "Bevy Mixed Lighting Example" (0v1#4294967296)
2024-12-18 16:21:03.068 mixed_lighting[49124:70427179] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-18 16:21:03.068 mixed_lighting[49124:70427179] +[IMKInputSession subclass]: chose IMKInputSession_Modern
2024-12-18T08:21:04.134997Z ERROR wgpu_hal::metal::device: Resource limit exceeded: StageInfo { stage: Fragment, counters: ResourceData { buffers: 13, textures: 51, samplers: 28 }, pc_buffer: None, pc_limit: 0, sizes_buffer: Some(12), need_sizes_buffer: true, resources: {ResourceBinding { group: 0, binding: 0 }: BindTarget { buffer: Some(0), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 1 }: BindTarget { buffer: Some(1), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 2 }: BindTarget { buffer: None, texture: Some(0), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 3 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(0)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 5 }: BindTarget { buffer: None, texture: Some(1), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 6 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(1)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 8 }: BindTarget { buffer: Some(2), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 9 }: BindTarget { buffer: Some(3), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 10 }: BindTarget { buffer: Some(4), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 11 }: BindTarget { buffer: Some(5), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 12 }: BindTarget { buffer: Some(6), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 13 }: BindTarget { buffer: Some(7), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 15 }: BindTarget { buffer: Some(8), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 16 }: BindTarget { buffer: None, texture: Some(2), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 17 }: BindTarget { buffer: None, texture: Some(3), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 18 }: BindTarget { buffer: None, texture: Some(11), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 19 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(2)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 20 }: BindTarget { buffer: Some(9), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 21 }: BindTarget { buffer: None, texture: Some(19), sampler: None, binding_array_size: Some(8), mutable: false }, ResourceBinding { group: 0, binding: 22 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(3)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 23 }: BindTarget { buffer: None, texture: Some(27), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 24 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(4)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 29 }: BindTarget { buffer: None, texture: Some(28), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 30 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(5)), binding_array_size: None, mutable: false }, ResourceBinding { group: 1, binding: 0 }: BindTarget { buffer: Some(10), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 1, binding: 4 }: BindTarget { buffer: None, texture: Some(29), sampler: None, binding_array_size: Some(16), mutable: false }, ResourceBinding { group: 1, binding: 5 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(6)), binding_array_size: Some(16), mutable: false }, ResourceBinding { group: 2, binding: 0 }: BindTarget { buffer: Some(11), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 1 }: BindTarget { buffer: None, texture: Some(45), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 2 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(22)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 3 }: BindTarget { buffer: None, texture: Some(46), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 4 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(23)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 5 }: BindTarget { buffer: None, texture: Some(47), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 6 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(24)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 7 }: BindTarget { buffer: None, texture: Some(48), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 8 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(25)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 9 }: BindTarget { buffer: None, texture: Some(49), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 10 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(26)), binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 11 }: BindTarget { buffer: None, texture: Some(50), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 2, binding: 12 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(27)), binding_array_size: None, mutable: false }} }
2024-12-18T08:21:04.135179Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (2)' panicked at /Users/mirus/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-23.0.1/src/backend/wgpu_core.rs:1034:18:
wgpu error: Validation Error

Caused by:
  In Device::create_pipeline_layout
    Not enough memory left.


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread '<unnamed>' panicked at /Users/mirus/Projects/github/bevy/crates/bevy_render/src/render_resource/pipeline_cache.rs:580:28:
index out of bounds: the len is 0 but the index is 6
Encountered a panic in system `bevy_render::renderer::render_system`!
```

**Comment by rparrett** [comment]
Confirmed that this is fixed by #16890
