### ISSUE TITLE
ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default

### ISSUE THREAD

**Issue by webdev3614** [bevyengine/bevy#16960]
bevy version 0.15.0

My bevy project run on window 10.
My PC has a GPU and I have installed Graphics driver.

but following errors is fired.

2024-12-24T20:56:29.864250Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    
thread 'main' panicked at C:\Users\1\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-23.0.1\src\backend\wgpu_core.rs:891:18:
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group_layout, label = 'build mesh uniforms direct bind group layout'
    Too many bindings of type StorageBuffers in Stage ShaderStages(COMPUTE), limit is 2, count was 4. Check the limit `max_storage_buffers_per_shader_stage` passed to `Adapter::request_device`

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\normalmap.exe` (exit code: 101)

**Comment by webdev3614** [comment]
ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default

**Comment by GoodErnest64** [comment]
I have the same issue with a Geforce 820m GPU. I'm guessing it has something to do with our gpus lacking support since it also gave me this warning : 
`WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: Limits::max_storage_textures_per_shader_stage is less than 5.`
is it fixable ? does it have something to with vulkan maybe ?

**Comment by BenjaminBrienen** [comment]
@webdev3614 please add your SystemInfo and AdapterInfo to the issue description.

**Comment by webdev3614** [comment]
I downgraded my bevy version.
Then the project worked fine.
Thanks for your attention.

**Comment by HarryPeach** [comment]
Also having this issue on Bevy 1.16.1

```2025-07-11T12:03:55.795410Z ERROR wgpu::backend::wgpu_core: Handling wgpu errors as fatal by default    

thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wgpu-24.0.5/src/backend/wgpu_core.rs:1079:26:
wgpu error: Validation Error

Caused by:
  In Device::create_bind_group_layout, label = 'build mesh uniforms GPU early occlusion culling bind group layout'
    Too many bindings of type StorageBuffers in Stage ShaderStages(COMPUTE), limit is 8, count was 9. Check the limit `max_storage_buffers_per_shader_stage` passed to `Adapter::request_device`


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
