### ISSUE TITLE
mixed lighting example breaks with Res<InputFocus>

### ISSUE THREAD

**Issue by ChristopherBiscardi** [bevyengine/bevy#16961]
## Bevy version

f9c8f511f

## \[Optional\] Relevant system information

```
❯ cargo run --example mixed_lighting --features=jpeg
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/examples/mixed_lighting`
2024-12-24T22:32:20.317361Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "MacOS 14.2.1 Sonoma", kernel: "23.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
2024-12-24T22:32:20.423610Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2024-12-24T22:32:20.973867Z  INFO bevy_winit::system: Creating new window "Bevy Mixed Lighting Example" (0v1#4294967296)
thread '<unnamed>' panicked at /Users/chris/tmp/bevy/crates/bevy_ecs/src/system/function_system.rs:216:28:
bevy_winit::accessibility::update_accessibility_nodes could not access system parameter Res<InputFocus>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

## What you did

```
cargo run --example mixed_lighting --features=jpeg
```

## What went wrong

Application starts, window renders some part of the couch scene, then crashes. Varying amounts of progress. Sometimes it even succeeds without issue (rarely)

## Additional information

The issue is intermittent, but happens more often than not. Sometimes it is fine.

https://github.com/user-attachments/assets/bf4bd74d-f0da-40e9-a41c-348440257a63

**Comment by eero-lehtinen** [comment]
This happens to me every time on every example after focusing to another window and back to the bevy app window.

```
❯ cargo run --example fog
   Compiling bevy v0.15.0-dev (D:\repos\bevy)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 7.00s
     Running `target\debug\examples\fog.exe`
2024-12-31T01:39:36.702774Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 11 Pro", kernel: "26100", cpu: "AMD Ryzen 7 
5800X3D 8-Core Processor", core_count: "8", memory: "31.9 GiB" }
2024-12-31T01:39:36.785208Z ERROR wgpu_hal::vulkan::instance: GENERAL [Loader Message (0x0)]
        loader_add_layer_properties: Multiple 'layer' nodes are deprecated starting in file version "1.0.1".  Please use 'layers' : [] array instead in C:\ProgramData\GOG
.com\Galaxy\redists\overlay\injected\galaxy_overlay_vklayer_x64.json.
2024-12-31T01:39:36.785353Z ERROR wgpu_hal::vulkan::instance:   objects: (type: INSTANCE, hndl: 0x26381cf5630, name: ?)    
2024-12-31T01:39:37.031406Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce RTX 3070 Ti", vendor: 4318, device: 9346, device_type: DiscreteGpu, driver: "
NVIDIA", driver_info: "566.36", backend: Vulkan }
2024-12-31T01:39:37.790243Z  INFO bevy_winit::system: Creating new window App (0v1)
thread 'main' panicked at D:\repos\bevy\crates\bevy_ecs\src\system\function_system.rs:216:28:
bevy_winit::accessibility::update_accessibility_nodes could not access system parameter Res<InputFocus>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
error: process didn't exit successfully: `target\debug\examples\fog.exe` (exit code: 101)
```

**Comment by viridia** [comment]
I have a theory about why this is happening, and I am not sure what the correct solution is. I seem to recall that the "could not access system parameter" error is what happens when you try to inject a Resource that doesn't exist.

Thing is, the `InputFocus` resource is supposed to be optional - that is, if your game doesn't use input focus, then you shouldn't be required to initialize it or even depend on the `bevy_input_focus` crate. However, a11y now depends on `bevy_input_focus`, so anyone who installs the a11y plugin needs to have that resource initialized (either that, or we change a11y to injection that resource optionally).

The plugin which registers the `InputFocus` resource also installs a number of observers and a system which people may not want. These handle the bubbling of keyboard and button events. If you aren't using bubbling, then you shouldn't have to install these.

The "right" solution here would be to have a system of plugin dependencies: that is, a11y could depend on just the parts of bevy input focus that it needs, and users could depend on the parts they need, and if both a11y and the user installed the same plugins they would be deduped. But we don't have that ability yet.
