### ISSUE TITLE
2D examples are broken

### ISSUE THREAD

**Issue by CleanCut** [bevyengine/bevy#1724]
## Bevy version
45b2db70705da24a89426e6b6e77d603a3983025

## Operating system & version

macOS Big Sur 11.2.3

## What you did

Run a 2d example with a window.  For example `contributors`, `sprite` or `text2d`.

(Examples without windows like `custom_loop` seem to work, and so do 3D examples like `3d_scene` and `load_gltf`).

```shell
$ cargo run --example sprite
```

## What you expected to happen

The example should run.

## What actually happened

```
   Compiling bevy v0.4.0 (/Users/nathan/bv/bevy)
    Finished dev [unoptimized + debuginfo] target(s) in 14.82s
     Running `target/debug/examples/sprite`
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    buffer binding size 64 is less than minimum 80


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:1896:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

<details><summary>With `RUST_BACKTRACE=1`</summary>
<p>

```
$ RUST_BACKTRACE=1 cargo run --example sprite
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/examples/sprite`
wgpu error: Validation Error

Caused by:
    In Device::create_bind_group
    buffer binding size 64 is less than minimum 80


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:1896:5
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
   1: wgpu::backend::direct::default_error_handler
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:1896:5
   2: core::ops::function::Fn::call
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1342:9
   4: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:1883:9
   5: wgpu::backend::direct::Context::handle_error
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:109:9
   6: <wgpu::backend::direct::Context as wgpu::Context>::device_create_bind_group
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/backend/direct.rs:929:13
   7: wgpu::Device::create_bind_group
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.0/src/lib.rs:1535:17
   8: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::create_bind_group
             at ./crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:583:35
   9: bevy_render::renderer::render_resource::render_resource_bindings::RenderResourceBindings::update_bind_group
             at ./crates/bevy_render/src/renderer/render_resource/render_resource_bindings.rs:184:17
  10: <bevy_render::render_graph::nodes::pass_node::PassNode<Q> as bevy_render::render_graph::node::Node>::prepare::{{closure}}::{{closure}}
             at ./crates/bevy_render/src/render_graph/nodes/pass_node.rs:180:45
  11: std::collections::hash::map::Entry<K,V>::or_insert_with
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/collections/hash/map.rs:2218:43
  12: <bevy_render::render_graph::nodes::pass_node::PassNode<Q> as bevy_render::render_graph::node::Node>::prepare::{{closure}}
             at ./crates/bevy_render/src/render_graph/nodes/pass_node.rs:172:47
  13: bevy_ecs::world::World::resource_scope
             at ./crates/bevy_ecs/src/world/mod.rs:665:22
  14: <bevy_render::render_graph::nodes::pass_node::PassNode<Q> as bevy_render::render_graph::node::Node>::prepare
             at ./crates/bevy_render/src/render_graph/nodes/pass_node.rs:131:9
  15: bevy_render::render_graph::graph::RenderGraph::prepare
             at ./crates/bevy_render/src/render_graph/graph.rs:285:13
  16: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph::{{closure}}
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:105:13
  17: bevy_ecs::world::World::resource_scope
             at ./crates/bevy_ecs/src/world/mod.rs:665:22
  18: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:104:9
  19: bevy_wgpu::wgpu_renderer::WgpuRenderer::update
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:121:9
  20: bevy_wgpu::get_wgpu_render_system::{{closure}}
             at ./crates/bevy_wgpu/src/lib.rs:112:9
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1335:9
  22: <bevy_ecs::system::exclusive_system::ExclusiveSystemFn as bevy_ecs::system::exclusive_system::ExclusiveSystem>::run
             at ./crates/bevy_ecs/src/system/exclusive_system.rs:41:9
  23: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/stage.rs:663:21
  24: bevy_ecs::schedule::Schedule::run_once
             at ./crates/bevy_ecs/src/schedule/mod.rs:201:13
  25: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/mod.rs:219:21
  26: bevy_app::app::App::update
             at ./crates/bevy_app/src/app.rs:58:9
  27: bevy_winit::winit_runner_with::{{closure}}
             at ./crates/bevy_winit/src/lib.rs:485:17
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1335:9
  29: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:71:9
  30: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:173:21
  31: winit::platform_impl::platform::app_state::AppState::cleared
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/app_state.rs:331:13
  32: winit::platform_impl::platform::observer::control_flow_end_handler
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/observer.rs:135:13
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <unknown>
  42: <unknown>
  43: <() as objc::message::MessageArguments>::invoke
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  44: objc::message::platform::send_unverified
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  45: objc::message::send_message
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
  46: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:106:25
  47: winit::platform_impl::platform::event_loop::EventLoop<T>::run
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/macos/event_loop.rs:93:9
  48: winit::event_loop::EventLoop<T>::run
             at /Users/nathan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  49: bevy_winit::run
             at ./crates/bevy_winit/src/lib.rs:171:5
  50: bevy_winit::winit_runner_with
             at ./crates/bevy_winit/src/lib.rs:493:9
  51: bevy_winit::winit_runner
             at ./crates/bevy_winit/src/lib.rs:211:5
  52: core::ops::function::Fn::call
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  53: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1342:9
  54: bevy_app::app::App::run
             at ./crates/bevy_app/src/app.rs:68:9
  55: bevy_app::app_builder::AppBuilder::run
             at ./crates/bevy_app/src/app_builder.rs:48:9
  56: sprite::main
             at ./examples/2d/sprite.rs:4:5
  57: core::ops::function::FnOnce::call_once
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

## Additional information

Same error using stable (`rustc 1.50.0 (cb75ad5db 2021-02-10)`) or nightly (`rustc 1.53.0-nightly (f82664191 2021-03-21)`)

**Comment by rparrett** [comment]
Duplicate of #1706

**Comment by CleanCut** [comment]
Closing in favor of #1706
