### ISSUE TITLE
"custom_loop" example does not work with default plugins

### ISSUE THREAD

**Issue by CleanCut** [bevyengine/bevy#1729]
I would like to do something like the `custom_loop` example, but with a window and normal plugins.

Adding default plugins [between lines 25 and 26](https://github.com/bevyengine/bevy/blob/42924d22272fb0a38a01bab1116ad7b6f8865e8a/examples/app/custom_loop.rs#L25-L26) breaks the example:

```diff
--- a/examples/app/custom_loop.rs
+++ b/examples/app/custom_loop.rs
@@ -23,6 +23,7 @@ fn print_system(input: Res<Input>) {
 fn main() {
     App::build()
         .insert_resource(Input(String::new()))
+        .add_plugins(DefaultPlugins)
         .set_runner(my_runner)
         .add_system(print_system.system())
         .run();
```

The result is a crash the first time `app.update()` is called:

```
thread 'main' panicked at 'Window swapchain node refers to a non-existent window.', /Users/nathan/.cargo/git/checkouts/bevy-f7ffde730c324c74/b6be8a5/crates/bevy_render/src/render_graph/nodes/window_swapchain_node.rs:51:14
```

<details><summary>Here is the output with `RUST_BACKTRACE=1` (click to expand)</summary>
<p>

```
$ RUST_BACKTRACE=1 cargo run --example custom_loop
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/examples/custom_loop`
Type stuff into the console
aosenuth
You typed: aosenuth
thread 'main' panicked at 'Window texture node refers to a non-existent window.', crates/bevy_render/src/render_graph/nodes/window_texture_node.rs:54:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1260:5
   3: core::option::Option<T>::expect
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: <bevy_render::render_graph::nodes::window_texture_node::WindowTextureNode as bevy_render::render_graph::node::Node>::update
             at ./crates/bevy_render/src/render_graph/nodes/window_texture_node.rs:52:22
   5: bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute
             at ./crates/bevy_wgpu/src/renderer/wgpu_render_graph_executor.rs:75:25
   6: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph::{{closure}}
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:115:13
   7: bevy_ecs::world::World::resource_scope
             at ./crates/bevy_ecs/src/world/mod.rs:665:22
   8: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:104:9
   9: bevy_wgpu::wgpu_renderer::WgpuRenderer::update
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:121:9
  10: bevy_wgpu::get_wgpu_render_system::{{closure}}
             at ./crates/bevy_wgpu/src/lib.rs:112:9
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1335:9
  12: <bevy_ecs::system::exclusive_system::ExclusiveSystemFn as bevy_ecs::system::exclusive_system::ExclusiveSystem>::run
             at ./crates/bevy_ecs/src/system/exclusive_system.rs:41:9
  13: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/stage.rs:663:21
  14: bevy_ecs::schedule::Schedule::run_once
             at ./crates/bevy_ecs/src/schedule/mod.rs:201:13
  15: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/mod.rs:219:21
  16: bevy_app::app::App::update
             at ./crates/bevy_app/src/app.rs:58:9
  17: custom_loop::my_runner
             at ./examples/app/custom_loop.rs:15:9
  18: core::ops::function::Fn::call
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  19: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1342:9
  20: bevy_app::app::App::run
             at ./crates/bevy_app/src/app.rs:68:9
  21: bevy_app::app_builder::AppBuilder::run
             at ./crates/bevy_app/src/app_builder.rs:48:9
  22: custom_loop::main
             at ./examples/app/custom_loop.rs:24:5
  23: core::ops::function::FnOnce::call_once
             at /Users/nathan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
-[_MTLCommandEncoder dealloc]:131: failed assertion `Command encoder released without endEncoding'
[1]    52012 abort      RUST_BACKTRACE=1 cargo run --example custom_loop
```

</p>
</details>

See also [this discussion](https://github.com/bevyengine/bevy/discussions/1723).

**Comment by rparrett** [comment]
Related: #1377

**Comment by CleanCut** [comment]
@rparrett That's super relevant, thanks!

It looks like @codec-abc found the core issue already in https://github.com/bevyengine/bevy/issues/1377#issuecomment-772110096

> Okay after digging some more and a lot of help from the Discord people, the reason why it is crashing is because if I use my own runner I overwrite the one set by winit which take care to manage the rendering context, the input is so on.
>
> So basically, setting a custom loop runner work as intended but I cannot run a Bevy instance externally in a WASM context I need winit to set up a few things to get the 3D, input and so on to work. Unfortunately, I didn't found a way to let the winit plugin yield control to me so I can run the event loop myself.

So in essence, you _can't_ actually use a custom runner unless you omit most of Bevy's functionality, because adding a custom runner replaces the custom winit runner that processes rendering and input (just minor stuff 😝).

What's a good way to solve this?

The only thing that comes to my mind is to find some way to _add_ new logic, rather than _replace_ it. Think: a chain of functions to be run in sequence _by_ the runner (rather than _replacing_ the runner)?  Would that be a viable approach?

**Comment by CleanCut** [comment]
I shouldn't split this discussion between two issues. I'm going to close this in favor of #1377 and re-post my comment over there, so let's pick up the discussion on the other issue.
