### ISSUE TITLE
multiple_windows example panics

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#1736]
## Bevy version

47004dfcb415a049e4c6e68fdf56c26de72f51a1
bisected to first bad commit: 284889c64b2a4a4f67018e42a14062392edbd0aa

## Operating system & version

macOS, discord says windows is affected also

## What you did

`cargo run --example multiple_windows`

## What actually happened

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/window/multiple_windows.rs:75:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
             at /Users/robparrett/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:386:21
   4: multiple_windows::setup_pipeline
             at ./examples/window/multiple_windows.rs:71:21
   5: core::ops::function::Fn::call
             at /Users/robparrett/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
   6: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
             at /Users/robparrett/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:247:13
   7: <Func as bevy_ecs::system::into_system::SystemParamFunction<(),Out,(F0,F1,F2,F3,F4,F5),()>>::run
             at ./crates/bevy_ecs/src/system/into_system.rs:189:21
```

## Additional information

Any additional information you would like to add such as screenshots, logs, etc.

**Comment by alice-i-cecile** [comment]
Adding to 0.5: this shouldn't have slipped past CI (see #1730).

**Comment by rparrett** [comment]
Fix incoming

**Comment by rparrett** [comment]
Scratch that, was a bit too eager.

There seems to be an obvious transcription issue in the example
```rs
SystemSet::on_enter(AppState::CreateWindow).with_system(setup_pipeline.system())
```
Where that should be `AppState::Setup`, but the example still panics after fixing.

**Comment by rparrett** [comment]
Oops. This is a duplicate of #1709. 

Search for `multiple_windows` didn't turn that up.
