### ISSUE TITLE
.add_default_plugins() crashes (wayland?)

### ISSUE THREAD

**Issue by donpdonp** [bevyengine/bevy#200]
Ubuntu 18.04 Thinkpad using wayland, which has caused problems with wgpu before, so I suspect thats whats happening here, but not sure.

```
use bevy::prelude::*;

fn main() {
    App::build().add_default_plugins().run();
}
```

```
$ RUST_BACKTRACE=1 cargo run
   Compiling vorph v0.1.0 (/home/donp/projects/bevy/vorph)
    Finished dev [unoptimized + debuginfo] target(s) in 11.71s
     Running `target/debug/vorph`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.1.0/src/wgpu_renderer.rs:22:23
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: core::option::Option<T>::unwrap
             at /home/donp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34
  15: bevy_wgpu::wgpu_renderer::WgpuRenderer::new::{{closure}}
             at /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.1.0/src/wgpu_renderer.rs:22
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/donp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  17: pollster::block_on
             at /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.0/src/lib.rs:64
  18: bevy_wgpu::wgpu_render_system
             at /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.1.0/src/lib.rs:35
  19: <bevy_wgpu::WgpuPlugin as bevy_app::plugin::Plugin>::build
             at /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.1.0/src/lib.rs:22
  20: bevy_app::app_builder::AppBuilder::add_plugin
             at /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.1.0/src/app_builder.rs:235
  21: <bevy_app::app_builder::AppBuilder as bevy::add_default_plugins::AddDefaultPlugins>::add_default_plugins
             at /home/donp/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy-0.1.2/src/add_default_plugins.rs:33
  22: vorph::main
             at src/main.rs:4
  23: std::rt::lang_start::{{closure}}
             at /home/donp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  25: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  26: std::panicking::try
             at src/libstd/panicking.rs:274
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  29: std::rt::lang_start
             at /home/donp/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  30: main
  31: __libc_start_main
  32: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by PravinKumar95** [comment]
The issue may be due to winit both wgpu and bevy uses. I read somewhere it causes issues in wayland based systems but not sure

**Comment by Moxinilian** [comment]
Whenever you have time, feel free to tell us if this is still an issue. wgpu has been updated to the 0.6 release since and it might have fixed this issue.

**Comment by donpdonp** [comment]
I rebuilt with 0.3 and it runs.. right up until wgpu cannot find vulkan drivers (I only have opengl and that support is still in progress). I think bevy is fixed now at any rate. thanks!
