### ISSUE TITLE
Failed to access two mut components in one system with two querys

### ISSUE THREAD

**Issue by ChenhuiZhang** [bevyengine/bevy#2198]
Hi,

I'm try to build a simple movement game to learn bevy, it almost work, but I met an error when do something in this way:

```rust
fn ai_system(
    mut monster_query: Query<(&Monster, &mut Speed, &Transform)>,
    mut hunter_query: Query<(&Hunter, &mut Speed, &Transform, &AI)>,
) {}
```

But below code works:
```rust
fn ai_system(
    monster_query: Query<(&Monster, &Transform)>,
    mut hunter_query: Query<(&Hunter, &mut Speed, &Transform, &AI)>,
) {}
```

The compile pass, but when I run the demo, it panic with:

```
 Running `target/debug/hunting`
thread 'main' panicked at 'Query<(&hunting::Hunter, &mut hunting::Speed, &bevy_transform::components::transform::Transform, &hunting::AI), ()> in system &hunting::ai_system accesses component(s) hunting::Speed in a way that conflicts with a previous system parameter. Allowing this would break Rust's mutability rules. Consider merging conflicting Queries into a QuerySet.', /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:147:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:435:5
   2: bevy_ecs::system::system_param::assert_component_access_compatibility
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:147:5
   3: <bevy_ecs::query::state::QueryState<Q,F> as bevy_ecs::system::system_param::SystemParamState>::init
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:86:9
   4: <(P0,P1) as bevy_ecs::system::system_param::SystemParamState>::init
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/system_param.rs:998:21
   5: <bevy_ecs::system::into_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::initialize
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/system/into_system.rs:166:33
   6: bevy_ecs::schedule::stage::SystemStage::initialize_systems
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/stage.rs:396:13
   7: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/stage.rs:751:13
   8: bevy_ecs::schedule::Schedule::run_once
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/mod.rs:201:13
   9: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.5.0/src/schedule/mod.rs:219:21
  10: bevy_app::app::App::update
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app.rs:58:9
  11: bevy_winit::winit_runner_with::{{closure}}
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.5.0/src/lib.rs:485:17
  12: winit::platform_impl::platform::sticky_exit_callback
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  13: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:303:17
  14: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:398:9
  15: winit::platform_impl::platform::EventLoop<T>::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652:56
  16: winit::event_loop::EventLoop<T>::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  17: bevy_winit::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.5.0/src/lib.rs:171:5
  18: bevy_winit::winit_runner_with
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.5.0/src/lib.rs:493:9
  19: bevy_winit::winit_runner
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.5.0/src/lib.rs:211:5
  20: core::ops::function::Fn::call
             at /home/chenhuiz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70:5
  21: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/chenhuiz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1560:9
  22: bevy_app::app::App::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app.rs:68:9
  23: bevy_app::app_builder::AppBuilder::run
             at /home/chenhuiz/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.5.0/src/app_builder.rs:49:9
  24: hunting::main
             at ./src/main.rs:145:5
  25: core::ops::function::FnOnce::call_once
             at /home/chenhuiz/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It seems Rust forbidden me to access both mut speed  in a same function? In setup system, I just spawn a monster and two hunters, all of them have a Speed component. I could move the monster speed to another system to update it, but I just would like to know why it failed? Thanks.

Best Regards,
Hermes

**Comment by bjorn3** [comment]
There is no way to ensure that you don't have an entity with the `Monster`, `Hunter`, `Speed`, `Transform` and `AI` components at the same time. Such an entity would result in both queries returning it. The `&mut Speed` in the result of both queries for this entity would alias, which would be UB and as such isn't allowed. Normally rustc would return a borrowck error for aliasing `&mut T`, but due to the way bevy_ecs works, this has to be checked at runtime instead.

**Comment by ChenhuiZhang** [comment]
Aha！Then it make sense, It will borrow twice if one entity has both Monster and Hunter. Thanks for quick answer. 

BTW, is there some other solution to solve this in a better way? What I did is create another system to handle the Speed for Monster. just curious.

**Comment by minecrawler** [comment]
Personally, I have a policy of never using more than one query per system. Imho, it means that you want to do too many things in one system or have a bad architecture, which may lead to problems now or in the future (as demonstrated above). The architecture should be changed so that there is only one query needed.

Depending on what you want to achieve, this may mean that you will need an additional data structure and sort systems in a specific order. Sometimes, it's just rethinking a few components early on.

For example, you could have an `EntityType` component, which contains the differentiation between hunter and monster, and a `Controller` component instead of `AI`, which capsules AI. That way, one query would be enough. Also it would allow you to easily put a network solution in place instead of the AI, or just another keyboard input handler, and that way implement multiplayer. Or develop different kinds of AI agents, which you could use for debugging or on different levels or create different hunter types easily.

**Comment by cart** [comment]
Making the queries disjoint (the solution @Ixentus posted above) is generally the right call. You can also use QuerySets, which allow multiple conflicting queries in the same system. However you are only allowed to access one at a time, which is enforced by rust's borrow checker:
https://bevy-cheatbook.github.io/programming/query-sets.html

**Comment by speakk** [comment]
Though querysets are a solution, often times I think minecrawler's advice is very good to keep in mind, and I would generally try to consider it first.

**Comment by ChenhuiZhang** [comment]
Hi all,

Thanks a lot for the help. Yes, all of above solutions are good to know and solve my problem. :)
