### ISSUE TITLE
Breakout example crashes with SIGSEGV

### ISSUE THREAD

**Issue by halvko** [bevyengine/bevy#2384]
## Bevy version

Hash: 97d8e4e1793ede3df8c77ed44736e800b38ff7a4
Version: v0.5.0

## Operating system & version

Arch 5.12.12-arch1-1

## What you did

Following the quickstart guide on bevyengine.org I cloned the repository, checked out "latest" (which was v0.5.0), and ran `cargo run --example breakout`

## What you expected to happen

After compilation finished I think a game should have played in a window that popped up

## What actually happened

Compilation finished, a black window appeared with bevy as the title, before disappearing, and in the console was written:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/breakout`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Unable to query surface formats: ERROR_INITIALIZATION_FAILED', /home/erikfc/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.7.0/src/window.rs:315:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Jun 24 13:57:37.973 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
Jun 24 13:57:37.973 ERROR gpu_alloc::block: Memory block wasn't deallocated
Jun 24 13:57:37.973 ERROR gpu_alloc::block: Memory block wasn't deallocated
fish: Job 1, 'cargo run --example breakout' terminated by signal SIGSEGV (Address boundary error)
```

When downgrading to bevy v0.4.0 the error changes to:
```
    Finished dev [unoptimized + debuginfo] target(s) in 34.31s
     Running `target/debug/examples/breakout`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

thread 'main' panicked at 'Unable to query surface formats: ERROR_INITIALIZATION_FAILED', /home/erikfc/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.6.5/src/window.rs:402:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is my first interaction with bevy and may somehow be my fault, but a have no clue as to what is wrong or how to go about fixing it.

**Comment by bjorn3** [comment]
> thread 'main' panicked at 'Unable to query surface formats: ERROR_INITIALIZATION_FAILED'

This is the actual error. The SIGSEGV happens as a result of failing to deinitialize the vulkan context I think. (Initialization failed after all)

Can you follow the steps in the verification section at https://wiki.archlinux.org/title/Vulkan to verify if Vulkan works? If you have the vulkan-tools package installed you can also try the vkcube demo that is part of this package.

**Comment by halvko** [comment]
Thanks a lot, put me on the correct track. Seems to be a Nvidia PRIME + Wayland issue. As this have nothing to do with the library, I'm closing the issue.

**Comment by matthew-salerno** [comment]
This might not be a closed issue. I'm having trouble running any of the examples that should spawn a window. Issues range from 'not enough memory left' to showing the x window in my task manager but not displaying anything. It seems with breakout that if I manually specify the ICD file, it will go from giving the 'not enough memory' error to showing in the task manager but doing nothing. I'd like to be helpful but I'm not familiar with rust (my goal was to use this engine to learn rust) so please let me know if there are any tests you need from me. I also tried switching to PR #2130 but it only changed the type of error message I got, and I'm not sure I did that one correctly. I only have one ICD file, for nvidia. Vulkan games through proton don't work but I tested a native vulkan game (dota2) and it worked just fine so I don't think it's a vulkan issue on my end, though I wouldn't entirely discount it.
Currently running a GTX 1070, Manjaro on kernel 5.12.9-1-MANJARO, nvidia 465.31, X11, Plasma 5.21.5
Here's my output trying to run array_texture:
```
$VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json RUST_BACKTRACE=1 cargo run --example array_texture
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/array_texture`
Jun 28 17:49:04.388 ERROR gpu_alloc::block: Memory block wasn't deallocated
wgpu error: Validation Error

Caused by:
    In Device::create_texture
    not enough memory left


thread 'main' panicked at 'Handling wgpu errors as fatal by default', /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1896:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:519:12
   1: wgpu::backend::direct::default_error_handler
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1896:5
   2: core::ops::function::Fn::call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:70:5
   3: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1560:9
   4: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1883:9
   5: wgpu::backend::direct::Context::handle_error
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:109:9
   6: <wgpu::backend::direct::Context as wgpu::Context>::device_create_texture
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:1132:13
   7: wgpu::Device::create_texture
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:1591:17
   8: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::create_texture
             at ./crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:258:23
   9: <bevy_render::render_graph::nodes::window_texture_node::WindowTextureNode as bevy_render::render_graph::node::Node>::update
             at ./crates/bevy_render/src/render_graph/nodes/window_texture_node.rs:72:36
  10: bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute
             at ./crates/bevy_wgpu/src/renderer/wgpu_render_graph_executor.rs:75:25
  11: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph::{{closure}}
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:115:13
  12: bevy_ecs::world::World::resource_scope
             at ./crates/bevy_ecs/src/world/mod.rs:695:22
  13: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:104:9
  14: bevy_wgpu::wgpu_renderer::WgpuRenderer::update
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:121:9
  15: bevy_wgpu::get_wgpu_render_system::{{closure}}
             at ./crates/bevy_wgpu/src/lib.rs:112:9
  16: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1553:9
  17: <bevy_ecs::system::exclusive_system::ExclusiveSystemFn as bevy_ecs::system::exclusive_system::ExclusiveSystem>::run
             at ./crates/bevy_ecs/src/system/exclusive_system.rs:41:9
  18: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/stage.rs:812:25
  19: bevy_ecs::schedule::Schedule::run_once
             at ./crates/bevy_ecs/src/schedule/mod.rs:201:13
  20: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/mod.rs:219:21
  21: bevy_app::app::App::update
             at ./crates/bevy_app/src/app.rs:58:9
  22: bevy_winit::winit_runner_with::{{closure}}
             at ./crates/bevy_winit/src/lib.rs:485:17
  23: winit::platform_impl::platform::sticky_exit_callback
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  24: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:303:17
  25: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:398:9
  26: winit::platform_impl::platform::EventLoop<T>::run
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652:56
  27: winit::event_loop::EventLoop<T>::run
             at /home/matt/.config/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  28: bevy_winit::run
             at ./crates/bevy_winit/src/lib.rs:171:5
  29: bevy_winit::winit_runner_with
             at ./crates/bevy_winit/src/lib.rs:493:9
  30: bevy_winit::winit_runner
             at ./crates/bevy_winit/src/lib.rs:211:5
  31: core::ops::function::Fn::call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:70:5
  32: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/alloc/src/boxed.rs:1560:9
  33: bevy_app::app::App::run
             at ./crates/bevy_app/src/app.rs:68:9
  34: bevy_app::app_builder::AppBuilder::run
             at ./crates/bevy_app/src/app_builder.rs:49:9
  35: array_texture::main
             at ./examples/shader/array_texture.rs:16:5
  36: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jun 28 17:49:04.438 ERROR gpu_alloc::block: Memory block wasn't deallocated
Jun 28 17:49:04.438 ERROR gpu_alloc::block: Memory block wasn't deallocated
zsh: segmentation fault (core dumped)  VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json RUST_BACKTRACE=1  ru

```

**Comment by matthew-salerno** [comment]
Setting font dpi as per #2617 has resolved this issue. I recommend we close this as a duplicate.
