### ISSUE TITLE
WGPU renderer panics on `ColorMaterial` edition

### ISSUE THREAD

**Issue by ManevilleF** [bevyengine/bevy#2679]
## Bevy version

0.5.0

## Operating system & version

MacOS Big Sur

## What you did

Have a `ColorMaterial` like this:

```rust
let mat = materials.add(ColorMaterial {
    color: Color::WHITE,
    texture: asset_server.load("my_texture.png")
});
```

Edit the material removing the texture:

```
let material = materials.get_mut(mat.clone()).unwrap();
material.texture = None;
```

The texture is corretly removed.

Now edit the material back:

```
let material = materials.get_mut(mat.clone()).unwrap();
material.texture = Some(asset_server.load("my_texture.png"));
```

## What you expected to happen

The material should have its texture back 

## What actually happened

The program panics:

```
thread 'main' panicked at 'TextureId(b6c3f65b-1c59-443d-8787-1dc9f6d9fa74)', /Users/Me/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.5.0/src/renderer/wgpu_render_resource_context.rs:554:52
```
or
```
thread 'Compute Task Pool (2)' panicked at 'TextureId(fb1f8e83-4b2b-42fd-9152-2842cd76effc)', /Users/Me/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_wgpu-0.5.0/src/renderer/wgpu_render_resource_context.rs:554:52
```

**Comment by NiklasEi** [comment]
This is because the texture handle gets unloaded in between removing and adding it. If you keep the handle loaded (e.g. keep a reference in a resource), the crash does not happen.
The engine usually just skips rendering of unloaded textures, so I would still consider this a bug.

**Comment by ManevilleF** [comment]
I can try to keep the handle somewhere but I don't see why re-loading a texture using `asset_server.load()` would crash. So I agree this should still be considered a bug.

What I don't understand is that if I replace the `Handle<Texture>` by an other texture, and then load back the previous one, it works ! The crash only happens if the `texture` was set to `None` at some point
