### ISSUE TITLE
Adding `DefaultPlugins` causes crash on Windows

### ISSUE THREAD

**Issue by rokit** [bevyengine/bevy#2712]
## Bevy version

0.5

## Operating system & version

Windows 10 version 21H1

## What you did

Followed startup guide and added `DefaultPlugins`:
https://bevyengine.org/learn/book/getting-started/plugins/

## What you expected to happen

Window opens

## What actually happened

Window opens, but then crashes.
![image](https://user-images.githubusercontent.com/1229742/130370110-f17eb51b-c0f9-46ac-a1f3-6c97db8dfdd5.png)

with console error:
`error: process didn't exit successfully: `target\debug\bevy-arpg.exe` (exit code: 255)`

## Additional information

May be similar to [1174](https://github.com/bevyengine/bevy/issues/1174), however inserting resources for `Msaa` and `WindowDescriptor` before adding default plugins did not work for me.

I clicked "Debug" on that dialog, which opened VS2019, and I see this:
`Unhandled exception at 0x00007FFB197665E9 (VkLayer_khronos_validation.dll) in bevy-arpg.exe: 0xC000041D: An unhandled exception was encountered during a user callback.`

![image](https://user-images.githubusercontent.com/1229742/130373247-00839887-f72e-4928-9955-ac69e1ebdddf.png)

**Comment by alice-i-cecile** [comment]
Looks like a graphics driver issue of some flavor. Let's see if we can narrow this down:

1. Which graphics card do you have? 
2. Have you updated the drivers recently? 
3. Can you reproduce on the `pipelined-rendering` branch?
4. Can you reproduce on #2556's branch?

**Comment by rokit** [comment]
1. GTX 970
2. I just updated to the latest.
3. Yes. For `pipelined-rendering` branch I get Vulkan errors in the console, and debugging still fails on `cmd_begin_render_pass`.
4. Yes. I tried @zicklag's `update-to-wgpu-master` branch. I first got an error: `error: Metal API enabled on non-Apple OS. If your project is not using resolver="2" in Cargo.toml, it should.` Once I added `resolver="2"`, I got more Vulkan errors in the console, and it still crashed on the `cmd_begin_render_pass` step.

**Comment by allangalera** [comment]
I have the same problem. I'm trying to toy a little bit with bevy doing the tutorial and it breaks when I add the `DefaultPlugins` as well.

```rust
fn main() {
    App::build()
        .add_plugins(DefaultPlugins)
        .add_startup_system(add_people.system())
        .add_system(hello_world.system())
        .add_system(greet_people.system())
        .run();
}
```
Just after I added the `.add_plugins(DefaultPlugins)` it crashed with this error:

```
Compiling bevy-game-tutorial v0.1.0 (C:\Users\Allan Galera\projects\bevy-game-tutorial)
    Finished dev [unoptimized + debuginfo] target(s) in 6.20s
     Running `target\debug\bevy-game-tutorial.exe`
thread 'main' panicked at 'build_output_stream failed with all supported formats: BackendSpecific { err: BackendSpecificError { description: "OS Error -2004287478 (FormatMessageW() returned error 15100) (os error -2004287478)" } }', C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\rodio-0.13.1\src\stream.rs:208:22
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\result.rs:1355
   3: enum$<core::result::Result<tuple<alloc::sync::Arc<rodio::dynamic_mixer::DynamicMixerController<f32>>, cpal::platform::platform_impl::Stream>, enum$<cpal::error::BuildStreamError>>>::expect<tuple<alloc::sync::Arc<rodio::dynamic_mixer::DynamicMixerControlle
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:997
   4: rodio::stream::{{impl}}::try_new_output_stream::{{closure}}
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\rodio-0.13.1\src\stream.rs:204
   5: enum$<core::result::Result<tuple<alloc::sync::Arc<rodio::dynamic_mixer::DynamicMixerController<f32>>, cpal::platform::platform_impl::Stream>, enum$<cpal::error::BuildStreamError>>>::unwrap_or_else<tuple<alloc::sync::Arc<rodio::dynamic_mixer::DynamicMixerC
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:821
   6: rodio::stream::{{impl}}::try_new_output_stream
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\rodio-0.13.1\src\stream.rs:200
   7: rodio::stream::OutputStream::try_from_device
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\rodio-0.13.1\src\stream.rs:31
   8: rodio::stream::OutputStream::try_default
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\rodio-0.13.1\src\stream.rs:45
   9: bevy_audio::audio_output::{{impl}}::default<bevy_audio::audio_source::AudioSource>
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_audio-0.5.0\src\audio_output.rs:22
  10: bevy_ecs::world::{{impl}}::from_world<bevy_audio::audio_output::AudioOutput<bevy_audio::audio_source::AudioSource>>
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\world\mod.rs:928
  11: bevy_app::app_builder::AppBuilder::init_non_send_resource<bevy_audio::audio_output::AudioOutput<bevy_audio::audio_source::AudioSource>>
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.5.0\src\app_builder.rs:272
  12: bevy_audio::{{impl}}::build
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_audio-0.5.0\src\lib.rs:23
  13: bevy_app::plugin_group::PluginGroupBuilder::finish
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.5.0\src\plugin_group.rs:104
  14: bevy_app::app_builder::AppBuilder::add_plugins<bevy_internal::default_plugins::DefaultPlugins>
             at C:\Users\Allan Galera\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.5.0\src\app_builder.rs:295
  15: bevy_game_tutorial::main
             at .\src\main.rs:33
  16: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\bevy-game-tutorial.exe` (exit code: 101)
```

I just updated my graphics card driver. I have an AMD Radeon RX 560.

Tell me if there is more information for me to add 👍

**Comment by alice-i-cecile** [comment]
@allangalera, yours looks like an audio issue :)

>    9: bevy_audio::audio_output::{{impl}}::default<bevy_audio::audio_source::AudioSource>

Could you try reproducing on main (it should no longer crash if no audio target is found), then if that still breaks, make a new issue with that log, your OS and other sound-relevant information?

**Comment by rokit** [comment]
Here is the render pass struct before the crash. Is there anything odd about it? Also, here are the plugins I was running at the time. One thing that looks odd to me is the window id of 0.

```
        group.add(CorePlugin::default());
        // group.add(TransformPlugin::default());
        // group.add(DiagnosticsPlugin::default());
        // group.add(InputPlugin::default());
        group.add(WindowPlugin::default());
        group.add(AssetPlugin::default());
        // group.add(ScenePlugin::default());

        #[cfg(feature = "bevy_render")]
        group.add(RenderPlugin::default());

        // #[cfg(feature = "bevy_sprite")]
        // group.add(SpritePlugin::default());

        // #[cfg(feature = "bevy_pbr")]
        // group.add(PbrPlugin::default());

        // #[cfg(feature = "bevy_ui")]
        // group.add(UiPlugin::default());
        // #[cfg(feature = "bevy_text")]
        // group.add(TextPlugin::default());

        // #[cfg(feature = "bevy_audio")]
        // group.add(AudioPlugin::default());

        // #[cfg(feature = "bevy_gilrs")]
        // group.add(GilrsPlugin::default());

        // #[cfg(feature = "bevy_gltf")]
        // group.add(GltfPlugin::default());

        #[cfg(feature = "bevy_winit")]
        group.add(WinitPlugin::default());

        #[cfg(feature = "bevy_wgpu")]
        group.add(WgpuPlugin::default());
```

```
WgpuRenderPass {
    render_pass: RenderPass {
        id: RenderPass {
            encoder_id: (0, 1, Vulkan),
            color_targets: [RenderPassColorAttachment {
                view: (1, 1, Vulkan),
                resolve_target: None,
                channel: PassChannel {
                    load_op: Clear,
                    store_op: Store,
                    clear_value: Color {
                        r: 0.13286833465099335, g: 0.13286833465099335, b: 0.13286833465099335, a: 1.0
                    },
                    read_only: false
                }
            }],
            depth_stencil_target: Some(RenderPassDepthStencilAttachment {
                view: (0, 1, Vulkan),
                depth: PassChannel {
                    load_op: Clear,
                    store_op: Store,
                    clear_value: 1.0,
                    read_only: false
                },
                stencil: PassChannel {
                    load_op: Load,
                    store_op: Store,
                    clear_value: 0,
                    read_only: true
                }
            }),
            data: 0 commands, 0 dynamic offsets, and 0 push constant u32s
        },
        parent: CommandEncoder {
            context: Context {
                type: "Native"
            },
            id: Some(CommandEncoder {
                id: (0, 1, Vulkan),
                error_sink: Mutex {
                    data: ErrorSink
                },
                open: true
            }),
            _p: PhantomData
        }
    },
    render_context: WgpuRenderContext {
        device: Device {
            context: Context {
                type: "Native"
            },
            id: Device {
                id: (0, 1, Vulkan),
                error_sink: Mutex {
                    data: ErrorSink
                },
                features: (empty)
            }
        },
        command_encoder: LazyCommandEncoder {
            command_encoder: None
        },
        render_resource_context: WgpuRenderResourceContext {
            device: Device {
                context: Context {
                    type: "Native"
                },
                id: Device {
                    id: (0, 1, Vulkan),
                    error_sink: Mutex {
                        data: ErrorSink
                    },
                    features: (empty)
                }
            },
            resources: WgpuResources {
                buffer_infos: RwLock {
                    data: {}
                },
                texture_descriptors: RwLock {
                    data: {
                        TextureId(79746153-ca70-4ec5-aac1-ab1724386324): TextureDescriptor {
                            size: Extent3d {
                                width: 1280,
                                height: 720,
                                depth_or_array_layers: 1
                            },
                            mip_level_count: 1,
                            sample_count: 1,
                            dimension: D2,
                            format: Depth32Float,
                            usage: OUTPUT_ATTACHMENT
                        }
                    }
                },
                window_surfaces: RwLock {
                    data: {
                        WindowId(00000000-0000-0000-0000-000000000000): Surface {
                            context: Context {
                                type: "Native"
                            },
                            id: (0, 1, Empty)
                        }
                    }
                },
                window_swap_chains: RwLock {
                    data: {
                        WindowId(00000000-0000-0000-0000-000000000000): SwapChain {
                            context: Context {
                                type: "Native"
                            },
                            id: (0, 1, Vulkan)
                        }
                    }
                },
                swap_chain_frames: RwLock {
                    data: {
                        TextureId(c93cf771-2fe5-4279-9530-8d391116f138): SwapChainFrame {
                            output: SwapChainTexture {
                                view: TextureView {
                                    context: Context {
                                        type: "Native"
                                    },
                                    id: (1, 1, Vulkan),
                                    owned: false
                                },
                                detail: SwapChainOutputDetail {
                                    swap_chain_id: (0, 1, Vulkan)
                                }
                            },
                            suboptimal: false
                        }
                    }
                },
                buffers: RwLock {
                    data: {}
                },
                texture_views: RwLock {
                    data: {
                        TextureId(79746153-ca70-4ec5-aac1-ab1724386324): TextureView {
                            context: Context {
                                type: "Native"
                            },
                            id: (0, 1, Vulkan),
                            owned: true
                        }
                    }
                },
                textures: RwLock {
                    data: {
                        TextureId(79746153-ca70-4ec5-aac1-ab1724386324): Texture {
                            context: Context {
                                type: "Native"
                            },
                            id: Texture {
                                id: (0, 1, Vulkan),
                                error_sink: Mutex {
                                    data: ErrorSink
                                }
                            },
                            owned: true
                        }
                    }
                },
                samplers: RwLock {
                    data: {}
                },
                shader_modules: RwLock {
                    data: {}
                },
                render_pipelines: RwLock {
                    data: {}
                },
                bind_groups: RwLock {
                    data: {}
                },
                bind_group_layouts: RwLock {
                    data: {}
                },
                asset_resources: RwLock {
                    data: {}
                },
                bind_group_counter: BindGroupCounter {
                    used_bind_group_sender: Sender { .. },
                    used_bind_group_receiver: Receiver { .. },
                    bind_group_usage_counts: RwLock {
                        data: {}
                    }
                }
            }
        }
    },
    wgpu_resources: WgpuResourceRefs {
        buffers: {},
        textures: {
            TextureId(79746153-ca70-4ec5-aac1-ab1724386324): TextureView {
                context: Context {
                    type: "Native"
                },
                id: (0, 1, Vulkan),
                owned: true
            }
        },
        swap_chain_frames: {
            TextureId(c93cf771-2fe5-4279-9530-8d391116f138): SwapChainFrame {
                output: SwapChainTexture {
                    view: TextureView {
                        context: Context {
                            type: "Native"
                        },
                        id: (1, 1, Vulkan),
                        owned: false
                    },
                    detail: SwapChainOutputDetail {
                        swap_chain_id: (0, 1, Vulkan)
                    }
                },
                suboptimal: false
            }
        },
        render_pipelines: {},
        bind_groups: {},
        used_bind_group_sender: Sender { .. }
    },
    pipeline_descriptor: None
}
```

**Comment by allangalera** [comment]
@alice-i-cecile I clone the bevy repo and ran the `cargo run --example breakout`. It worked fine.

I also tried running Godot and the console told me the same problem with audio source so as far as I understand it's an audio source problem and bevy latest/main version avoid crashing when that problem occurs right?

Thank you for the help :)

**Comment by rokit** [comment]
I installed the latest [Vulkan SDK](https://vulkan.lunarg.com/sdk/home#windows), in my case 1.2.189.2, and this problem disappeared.
