### ISSUE TITLE
error: failed to run custom build command for `libudev-sys v0.1.4` when running examples

### ISSUE THREAD

**Issue by LeSnake04** [bevyengine/bevy#2826]
## Bevy version

The release number or commit hash of the version you're using.

## Operating system & version

Artix(runit)

## What you did
Tried running an example (Hello World failed too).

## What you expected to happen
The example game starts.  

## What actually happened
The example fails to compile.

## Additional information
Error log:
``` $ RUST_BACKTRACE=1 cargo run --example breakout                                                                                                                                                                                     18:59:48
   Compiling libudev-sys v0.1.4
   Compiling quote v1.0.9
   Compiling memoffset v0.6.4
   Compiling getrandom v0.2.3
error: failed to run custom build command for `libudev-sys v0.1.4`

Caused by:
  process didn't exit successfully: `/home/<user>/tmp/bevy/target/debug/build/libudev-sys-50d1508ede402556/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBUDEV_STATIC
  cargo:rerun-if-env-changed=LIBUDEV_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"` did not exit successfully: exit status: 1\n--- stderr\nPackage libudev was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libudev.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'libudev' found\n"', /home/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/libudev-sys-0.1.4/build.rs:38:41
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/std/src/panicking.rs:517:5
     1: core::panicking::panic_fmt
               at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/panicking.rs:96:14
     2: core::result::unwrap_failed
               at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/result.rs:1617:5
     3: core::result::Result<T,E>::unwrap
               at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/result.rs:1299:23
     4: build_script_build::main
               at ./build.rs:38:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/9bb77da74dac4768489127d21e32db19b59ada5b/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed```

**Comment by DJMcNab** [comment]
Have you tried installing `libudev` or `udev` from your system package manager? I do agree that this error message could be nicer.

Once you've worked out how to do so (for all the required dependencies), documenting it here would be welcome, and we can add it to https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md

**Comment by LeSnake04** [comment]
Looks like there  is no udev on Artix, they use system/eudev and system/libeudev instead.

**Comment by LeSnake04** [comment]
But i dont think its worth making workarounds, since gentoo stopped maintaining it and  is swithcung back to udev, so its very likely artix will go back to udev too.

**Comment by bjorn3** [comment]
Seems like it will continue to be maintained after all:

https://github.com/eudev-project/eudev/commit/4aeeabe313a81bbe692df96eb8f4246d3477c0e8 and https://github.com/eudev-project/eudev/commit/1d093c25fbf5de9ecdec65c0aaddfd49b4b4a831

> ADOPTION NOTICE (2021-09-14)
>
> Currently eudev is in the process of being adopted by a newly formed project by Alpine, Devuan and Gentoo contributors (a-z order). Some of the below links and/or contacts may be outdated until the process is complete and all the infra set up.
>
> [...]

**Comment by lavaeater** [comment]
For anyone searching for the libudev issue and is using Ubuntu, I had as suggested in some stackexchange link (https://unix.stackexchange.com/questions/715215/unable-to-find-libudev-pc#answers) installed libudev both using apt and homebrew (installed rbenv using homebrew) and by uninstalling the homebrew version all of my issues with this disappeared. Normally I install rbenv from git sources but this time after upgrading Ubuntu I chose to do it the "easy" way and that immediately screwed me over. ;)
