### ISSUE TITLE
'thread '<unnamed><unnamed>' panicked at '' panicked at 'Resource does not exist

### ISSUE THREAD

**Issue by huangjj27** [bevyengine/bevy#286]
## Environment
rustc version: rustc 1.45.2 (d3fb005a3 2020-07-31)
cargo version: cargo 1.45.1 (f242df6ed 2020-07-22)
OS: Windows 10 Pro 1909
Processer: AMD A10-5750M with Radeon(tm) HD graphics
Graphics: AMD Radeon HD 8650G + AMD Radeon HD 8790M (Microsoft detected dirvers, date to 2019/8/16, driver version: 26.20.12028.2) (Not update to AMD drivers for the super slow download.)

NOTE that my graphics don’t support newer drivers which support Vulkan.

## Demo
```toml
# Cargo.toml
[package]
name = "game_demo"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.bevy]
version = "0.1.2"
default-features = false
```

```rs
// main.rs
use bevy::prelude::*;

fn main() {
    App::build()
        .add_default_plugins()
        .run();
}
```

## Expected Behavior
Pop up a window that contains nothing

## Actual  Behavior
```
PS > $env:RUST_BACKTRACE=1
PS > cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target\debug\game_demo.exe`
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'Resource does not exist alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>Resource does not exist alloc::boxed::Box<dyn bevy_render::renderer::render_resource_context::RenderResourceContext>', ', C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libstd\macros.rsC:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\src\libstd\macros.rs::1616::99

stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic_handler
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:388
  11: std::panicking::begin_panic_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:342
  12: bevy_ecs::resource::resources::{{impl}}::get_unsafe_ref::{{closure}}<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\macros.rs:16
  13: core::option::Option<core::ptr::non_null::NonNull<alloc::boxed::Box<RenderResourceContext>>>::unwrap_or_else<core::ptr::non_null::NonNull<alloc::boxed::Box<RenderResourceContext>>,closure-1>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\option.rs:430
  14: bevy_ecs::resource::resources::Resources::get_unsafe_ref<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resources.rs:144   
  15: bevy_ecs::resource::resource_query::{{impl}}::get<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resource_query.rs:150
  16: bevy_ecs::resource::resource_query::{{impl}}::get<bevy_ecs::resource::resource_query::FetchResourceWrite<bevy_render::texture::texture::TextureResourceSystemState>,bevy_ecs::resource::resource_query::FetchResourceRead<alloc::boxed::Box<RenderResourceConte
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resource_query.rs:255
  17: bevy_ecs::resource::resources::Resources::query_system<(bevy_ecs::resource::resource_query::ResMut<bevy_render::texture::texture::TextureResourceSystemState>, bevy_ecs::resource::resource_query::Res<alloc::boxed::Box<RenderResourceContext>>, bevy_ecs::res
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resources.rs:139   
  18: bevy_ecs::system::into_system::{{impl}}::system::{{closure}}<fn(bevy_ecs::resource::resource_query::ResMut<bevy_render::texture::texture::TextureResourceSystemState>, bevy_ecs::resource::resource_query::Res<alloc::boxed::Box<RenderResourceContext>>, bevy_
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\system\into_system.rs:178   
  19: bevy_ecs::system::into_system::{{impl}}::run<bevy_ecs::system::into_system::QuerySystemState,closure-0,closure-1,closure-2,closure-3>      
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\system\into_system.rs:61    
  20: bevy_ecs::schedule::parallel_executor::{{impl}}::run_ready_systems::{{closure}}
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\schedule\parallel_executor.rs:270
  21: rayon_core::scope::{{impl}}::spawn_fifo::{{closure}}::{{closure}}<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:496
  22: std::panic::{{impl}}::call_once<(),closure-0>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  23: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:297
  24: core::ptr::non_null::{{impl}}::from<alloc::vec::Vec<bevy_ecs::system::commands::Command>>
  25: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  26: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  27: rayon_core::unwind::halt_unwinding<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\unwind.rs:17
  28: rayon_core::scope::ScopeBase::execute_job_closure<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:562
  29: rayon_core::scope::ScopeBase::execute_job<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:550
  30: rayon_core::scope::{{impl}}::spawn_fifo::{{closure}}<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:496
  31: rayon_core::job::{{impl}}::execute<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:167
  32: rayon_core::job::JobRef::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:59
  33: rayon_core::job::{{impl}}::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:209
  34: rayon_core::job::JobRef::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:59
  35: rayon_core::registry::WorkerThread::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:685
  36: rayon_core::registry::WorkerThread::wait_until_cold<rayon_core::latch::CountLatch>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:669
  37: rayon_core::registry::WorkerThread::wait_until<rayon_core::latch::CountLatch>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:643
  38: rayon_core::registry::main_loop
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:763
  39: rayon_core::registry::ThreadBuilder::run
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:56
  40: rayon_core::registry::{{impl}}::spawn::{{closure}}
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:101
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libcore\fmt\mod.rs:1076
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\io\mod.rs:1537
   5: std::sys_common::backtrace::_print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:198
   8: std::panicking::default_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:218
   9: std::panicking::rust_panic_with_hook
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:486
  10: std::panicking::begin_panic_handler
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:388
  11: std::panicking::begin_panic_fmt
             at /rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54\/src\libstd\panicking.rs:342
  12: bevy_ecs::resource::resources::{{impl}}::get_unsafe_ref::{{closure}}<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\macros.rs:16
  13: core::option::Option<core::ptr::non_null::NonNull<alloc::boxed::Box<RenderResourceContext>>>::unwrap_or_else<core::ptr::non_null::NonNull<alloc::boxed::Box<RenderResourceContext>>,closure-1>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\option.rs:430
  14: bevy_ecs::resource::resources::Resources::get_unsafe_ref<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resources.rs:144   
  15: bevy_ecs::resource::resource_query::{{impl}}::get<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resource_query.rs:150
  16: bevy_ecs::resource::resource_query::{{impl}}::get<bevy_ecs::resource::resource_query::FetchResourceLocalMut<bevy_render::mesh::mesh::MeshResourceProviderState>,bevy_ecs::resource::resource_query::FetchResourceRead<alloc::boxed::Box<RenderResourceContext>>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resource_query.rs:255
  17: bevy_ecs::resource::resources::Resources::query_system<(bevy_ecs::resource::resource_query::Local<bevy_render::mesh::mesh::MeshResourceProviderState>, bevy_ecs::resource::resource_query::Res<alloc::boxed::Box<RenderResourceContext>>, bevy_ecs::resource::r
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\resource\resources.rs:139   
  18: bevy_ecs::system::into_system::{{impl}}::system::{{closure}}<fn(bevy_ecs::resource::resource_query::Local<bevy_render::mesh::mesh::MeshResourceProviderState>, bevy_ecs::resource::resource_query::Res<alloc::boxed::Box<RenderResourceContext>>, bevy_ecs::res
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\system\into_system.rs:178   
  19: bevy_ecs::system::into_system::{{impl}}::run<bevy_ecs::system::into_system::QuerySystemState,closure-0,closure-1,closure-2,closure-3>      
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\system\into_system.rs:61
  20: bevy_ecs::schedule::parallel_executor::{{impl}}::run_ready_systems::{{closure}}
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\bevy_ecs-0.1.0\src\schedule\parallel_executor.rs:270
  21: rayon_core::scope::{{impl}}::spawn_fifo::{{closure}}::{{closure}}<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:496
  22: std::panic::{{impl}}::call_once<(),closure-0>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  23: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:297
  24: core::ptr::non_null::{{impl}}::from<alloc::vec::Vec<bevy_ecs::system::commands::Command>>
  25: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  26: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  27: rayon_core::unwind::halt_unwinding<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\unwind.rs:17
  28: rayon_core::scope::ScopeBase::execute_job_closure<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:562
  29: rayon_core::scope::ScopeBase::execute_job<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:550
  30: rayon_core::scope::{{impl}}::spawn_fifo::{{closure}}<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:496
  31: rayon_core::job::{{impl}}::execute<closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:167
  32: rayon_core::job::JobRef::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:59
  33: rayon_core::job::{{impl}}::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:209
  34: rayon_core::job::JobRef::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:59
  35: rayon_core::registry::WorkerThread::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:685
  36: rayon_core::registry::WorkerThread::wait_until_cold<rayon_core::latch::CountLatch>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:669
  37: rayon_core::registry::WorkerThread::wait_until<rayon_core::latch::CountLatch>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:643
  38: rayon_core::scope::ScopeBase::steal_till_jobs_complete
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:605
  39: rayon_core::scope::ScopeBase::complete<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:538
  40: rayon_core::scope::scope_fifo::{{closure}}<closure-1,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\scope\mod.rs:385
  41: rayon_core::registry::{{impl}}::in_worker_cold::{{closure}}::{{closure}}<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:447
  42: rayon_core::job::{{impl}}::execute::call::{{closure}}<(),closure-0>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:113
  43: std::panic::{{impl}}::call_once<(),closure-0>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
  44: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:297
  45: core::ptr::non_null::{{impl}}::from<alloc::vec::Vec<bevy_ecs::system::commands::Command>>
  46: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
  47: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
             at C:\Users\huangjj27\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
  48: rayon_core::unwind::halt_unwinding<closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\unwind.rs:17
  49: rayon_core::job::{{impl}}::execute<rayon_core::latch::LockLatch*,closure-0,()>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:119
  50: rayon_core::job::JobRef::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\job.rs:59
  51: rayon_core::registry::WorkerThread::execute
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:685
  52: rayon_core::registry::WorkerThread::wait_until_cold<rayon_core::latch::CountLatch>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:669
  53: rayon_core::registry::WorkerThread::wait_until<rayon_core::latch::CountLatch>
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:643
  54: rayon_core::registry::main_loop
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:763
  55: rayon_core::registry::ThreadBuilder::run
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:56
  56: rayon_core::registry::{{impl}}::spawn::{{closure}}
             at C:\Users\huangjj27\.cargo\registry\src\mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b\rayon-core-1.7.1\src\registry.rs:101
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\game_demo.exe` (exit code: 101)
```

this issue is related to #140

**Comment by huangjj27** [comment]
I get the same issue with my new computer.

## Environment
rustc version: rustc 1.46.0 (04488afe3 2020-08-24)
cargo version: cargo 1.46.0 (149022b1d 2020-07-17)
OS: Windows 10 Pro 1909
Processer: AMD Ryzen 7 3700X 8-Core Processor 
Graphics: NVIDIA GeForce GTX 1660 SUPER, DirectX version: 12 (FL 12.1)

**Comment by CleanCut** [comment]
@huangjj27 That's great! Sounds like you can close this issue, then?

**Comment by huangjj27** [comment]
Let‘s archive this, so the people towards here will make their decision to update graphics :)
