### ISSUE TITLE
TextComponents combined with SpriteSheetComponents crashes

### ISSUE THREAD

**Issue by saicu** [bevyengine/bevy#313]
Hi,
spawning a `SpriteSheetComponents` and `TextComponents` seems to always crash.
It errors with 
```
thread 'main' panicked at 'number of dynamic offsets (0) doesn't match the number of dynamic bindings in the bind group layout (2)', /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323:35
```

To reproduce, add a `SpriteSheetComponents` to `examples/ui/text.rs`, e.g:
```rust
fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    let font_handle = asset_server.load("assets/fonts/FiraSans-Bold.ttf").unwrap();
    commands
        // 2d camera
        .spawn(UiCameraComponents::default())
        // texture
        .spawn(TextComponents {
            style: Style {
                align_self: AlignSelf::FlexEnd,
                ..Default::default()
            },
            text: Text {
                value: "FPS:".to_string(),
                font: font_handle,
                style: TextStyle {
                    font_size: 60.0,
                    color: Color::WHITE,
                },
            },
            ..Default::default()
        })
        .spawn(SpriteSheetComponents {
            ..Default::default()
        });
}
```
Tried a lot, nothing seems to work. 
Am I doing something wrong or is this a bug?

OS: Ubuntu 20.04.1
rustc 1.47.0-nightly (663d2f5cd 2020-08-22) - also rustc 1.45.2 (d3fb005a3 2020-07-31)
bevy 0.1.3
<details>
  <summary>full backtrace</summary>

```
stack backtrace:
   0:     0x55ee09244bd5 - backtrace::backtrace::libunwind::trace::ha215bbf14e328799
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55ee09244bd5 - backtrace::backtrace::trace_unsynchronized::h3384b099b135857a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55ee09244bd5 - std::sys_common::backtrace::_print_fmt::hfec93740f7294682
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55ee09244bd5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5fe20777f4174074
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55ee09270f4c - core::fmt::write::he14c3177144df275
                               at src/libcore/fmt/mod.rs:1076
   5:     0x55ee09240d93 - std::io::Write::write_fmt::h8e26323bfab8bcc5
                               at src/libstd/io/mod.rs:1537
   6:     0x55ee09247990 - std::sys_common::backtrace::_print::h9cfa4c87526ba064
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55ee09247990 - std::sys_common::backtrace::print::h94936584848b3272
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55ee09247990 - std::panicking::default_hook::{{closure}}::h733b20cc9b496e46
                               at src/libstd/panicking.rs:198
   9:     0x55ee092476dc - std::panicking::default_hook::h556d8cff6c12a651
                               at src/libstd/panicking.rs:218
  10:     0x55ee09247fc7 - std::panicking::rust_panic_with_hook::ha0c7ca5b39baa9d5
                               at src/libstd/panicking.rs:486
  11:     0x55ee09247bcb - rust_begin_unwind
                               at src/libstd/panicking.rs:388
  12:     0x55ee09247b3b - std::panicking::begin_panic_fmt::ha757bc84d5ed8cb6
                               at src/libstd/panicking.rs:342
  13:     0x55ee07f2d49e - <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::{{closure}}::h299125bcf4bbecd9
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323
  14:     0x55ee07f3a393 - core::result::Result<T,E>::unwrap_or_else::hba04d0ef7c936ef1
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:853
  15:     0x55ee07f460c1 - <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::h7e558aa7504e083d
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323
  16:     0x55ee07f2d004 - <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass::h0034411c957f5604
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1237
  17:     0x55ee080cb53f - <wgpu::RenderPass as core::ops::drop::Drop>::drop::ha9d7fa7cc5b7e308
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/lib.rs:2257
  18:     0x55ee07dedbd6 - core::ptr::drop_in_place::h7bbd22273529dc91
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:184
  19:     0x55ee07def45f - core::ptr::drop_in_place::he0cadfd0612960c3
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:184
  20:     0x55ee07e8d1a1 - <bevy_wgpu::renderer::wgpu_render_context::WgpuRenderContext as bevy_render::renderer::render_context::RenderContext>::begin_pass::h69e4b51186f2875c
                               at crates/bevy_wgpu/src/renderer/wgpu_render_context.rs:151
  21:     0x55ee0891542e - <bevy_render::render_graph::nodes::pass_node::PassNode<Q> as bevy_render::render_graph::node::Node>::update::h3e0729978acf8e84
                               at /home/sam/Schreibtisch/bevy/crates/bevy_render/src/render_graph/nodes/pass_node.rs:172
  22:     0x55ee07e8e803 - bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute::h5ebee9077c460693
                               at crates/bevy_wgpu/src/renderer/wgpu_render_graph_executor.rs:71
  23:     0x55ee07e73815 - bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph::h564e507303753ba4
                               at crates/bevy_wgpu/src/wgpu_renderer.rs:94
  24:     0x55ee07e7391e - bevy_wgpu::wgpu_renderer::WgpuRenderer::update::hd37df5a5219ae31b
                               at crates/bevy_wgpu/src/wgpu_renderer.rs:105
  25:     0x55ee07e00e68 - bevy_wgpu::wgpu_render_system::{{closure}}::hf944d4f581298e7c
                               at crates/bevy_wgpu/src/lib.rs:40
  26:     0x55ee07e00c21 - <F as bevy_ecs::system::into_system::ThreadLocalSystemFn>::run::h3511b508865717fc
                               at /home/sam/Schreibtisch/bevy/crates/bevy_ecs/src/system/into_system.rs:339
  27:     0x55ee07dff08e - <F as bevy_ecs::system::into_system::IntoThreadLocalSystem>::thread_local_system::{{closure}}::h26ae26c403460cda
                               at /home/sam/Schreibtisch/bevy/crates/bevy_ecs/src/system/into_system.rs:315
  28:     0x55ee07dfee1d - <bevy_ecs::system::into_system::SystemFn<State,F,ThreadLocalF,Init,SetArchetypeAccess> as bevy_ecs::system::system::System>::run_thread_local::hf30ab209e3f32f68
                               at /home/sam/Schreibtisch/bevy/crates/bevy_ecs/src/system/into_system.rs:65
  29:     0x55ee09126437 - bevy_ecs::schedule::parallel_executor::ExecutorStage::run::h1224cd76413a9bcc
                               at crates/bevy_ecs/src/schedule/parallel_executor.rs:387
  30:     0x55ee09124026 - bevy_ecs::schedule::parallel_executor::ParallelExecutor::run::h5daefa75c17c720a
                               at crates/bevy_ecs/src/schedule/parallel_executor.rs:57
  31:     0x55ee090fb949 - bevy_app::app::App::update::h941d1a9a5f23daef
                               at crates/bevy_app/src/app.rs:61
  32:     0x55ee085630fc - bevy_winit::winit_runner::{{closure}}::hd47b2c3155985d41
                               at crates/bevy_winit/src/lib.rs:212
  33:     0x55ee08556ea7 - cart_tmp_winit::platform_impl::platform::sticky_exit_callback::h564601039917c04b
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/mod.rs:703
  34:     0x55ee08593508 - cart_tmp_winit::platform_impl::platform::x11::EventLoop<T>::run_return::ha1e76a920d4678c4
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/x11/mod.rs:295
  35:     0x55ee085947df - cart_tmp_winit::platform_impl::platform::x11::EventLoop<T>::run::h367c7f356c24e197
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/x11/mod.rs:386
  36:     0x55ee08556d0c - cart_tmp_winit::platform_impl::platform::EventLoop<T>::run::hcf56b442cbe548e3
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/mod.rs:620
  37:     0x55ee08556ae7 - cart_tmp_winit::event_loop::EventLoop<T>::run::ha5d69bd25eaefe8e
                               at /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/event_loop.rs:149
  38:     0x55ee08561fc7 - bevy_winit::run::hc764e52d22aae345
                               at crates/bevy_winit/src/lib.rs:42
  39:     0x55ee0855649f - bevy_winit::winit_runner::h005e28d33da7cbf0
                               at crates/bevy_winit/src/lib.rs:220
  40:     0x55ee085573f1 - core::ops::function::Fn::call::h005cbf1a81a66f73
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:72
  41:     0x55ee090ee12a - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::hf2a58e3c50782bf4
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/boxed.rs:1090
  42:     0x55ee090fbadd - bevy_app::app::App::run::h3043cff66e4d1160
                               at crates/bevy_app/src/app.rs:74
  43:     0x55ee090fa415 - bevy_app::app_builder::AppBuilder::run::h45a7ce4ec1da1d27
                               at crates/bevy_app/src/app_builder.rs:43
  44:     0x55ee07ddee67 - text::main::h9bbc947a6456b8b2
                               at examples/ui/text.rs:8
  45:     0x55ee07de639b - std::rt::lang_start::{{closure}}::h8527f2b62ff586d5
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  46:     0x55ee09248458 - std::rt::lang_start_internal::{{closure}}::hefb489d56a389b75
                               at src/libstd/rt.rs:52
  47:     0x55ee09248458 - std::panicking::try::do_call::hb2bfa58b743656f1
                               at src/libstd/panicking.rs:297
  48:     0x55ee09248458 - std::panicking::try::haaa85a89ce3784c3
                               at src/libstd/panicking.rs:274
  49:     0x55ee09248458 - std::panic::catch_unwind::h49baa277f74e60cb
                               at src/libstd/panic.rs:394
  50:     0x55ee09248458 - std::rt::lang_start_internal::h7aa2f6739b31fe58
                               at src/libstd/rt.rs:51
  51:     0x55ee07de6377 - std::rt::lang_start::h9ffcf3a9d2952ebb
                               at /home/sam/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  52:     0x55ee07ddf8fa - main
  53:     0x7f89e41b00b3 - __libc_start_main
```
</details>

**Comment by Bobox214** [comment]
This is bug already logged as #134
