### ISSUE TITLE
Failure in graphical examples: `Error in Device::create_swap_chain: surface does not support the adapter's queue family'

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3501]
### Discussed in https://github.com/bevyengine/bevy/discussions/3500

<div type='discussions-op-text'>

<sup>Originally posted by **coreystaten** December 30, 2021</sup>
I'm having trouble running any graphical Bevy examples, getting the following error:

```
   Compiling bevy v0.5.0 (/home/user/code/bevy)
    Finished dev [unoptimized + debuginfo] target(s) in 13.01s
     Running `target/debug/examples/breakout`
thread 'main' panicked at 'Error in Device::create_swap_chain: surface does not support the adapter's queue family', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:129:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 30 17:01:30.225 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
Segmentation fault (core dumped)
```

I've tried on both the v0.5.0 tag and latest.  I'm on fully updated Arch Linux, using i3 and proprietary Nvidia Drivers with 3x RTX 2080 Ti GPUs.  Here's the output of `nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:08:00.0 Off |                  N/A |
| 27%   33C    P8    20W / 250W |      6MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:43:00.0  On |                  N/A |
| 26%   44C    P8    14W / 250W |     54MiB / 11019MiB |     31%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce ...  Off  | 00000000:44:00.0  On |                  N/A |
| 28%   48C    P8    20W / 250W |    279MiB / 11011MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1128      G   /usr/lib/Xorg                       4MiB |
|    1   N/A  N/A      1128      G   /usr/lib/Xorg                      53MiB |
|    2   N/A  N/A      1128      G   /usr/lib/Xorg                     146MiB |
|    2   N/A  N/A      1201      G   ...AAAAAAAAA= --shared-files       69MiB |
|    2   N/A  N/A      5014      G   ...AAAAAAAAA= --shared-files       60MiB |
+-----------------------------------------------------------------------------+
```

And here's with `RUST_BACKTRACE=1` set:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/breakout`
thread 'main' panicked at 'Error in Device::create_swap_chain: surface does not support the adapter's queue family', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:129:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:460:5
   2: wgpu::backend::direct::Context::handle_error_fatal
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:129:9
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/backend/direct.rs:805:25
   4: wgpu::Device::create_swap_chain
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.7.1/src/lib.rs:1623:17
   5: <bevy_wgpu::renderer::wgpu_render_resource_context::WgpuRenderResourceContext as bevy_render::renderer::render_resource_context::RenderResourceContext>::create_swap_chain
             at ./crates/bevy_wgpu/src/renderer/wgpu_render_resource_context.rs:364:26
   6: <bevy_render::render_graph::nodes::window_swapchain_node::WindowSwapChainNode as bevy_render::render_graph::node::Node>::update
             at ./crates/bevy_render/src/render_graph/nodes/window_swapchain_node.rs:65:13
   7: bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute
             at ./crates/bevy_wgpu/src/renderer/wgpu_render_graph_executor.rs:75:25
   8: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph::{{closure}}
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:115:13
   9: bevy_ecs::world::World::resource_scope
             at ./crates/bevy_ecs/src/world/mod.rs:695:22
  10: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:104:9
  11: bevy_wgpu::wgpu_renderer::WgpuRenderer::update
             at ./crates/bevy_wgpu/src/wgpu_renderer.rs:121:9
  12: bevy_wgpu::get_wgpu_render_system::{{closure}}
             at ./crates/bevy_wgpu/src/lib.rs:112:9
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1698:9
  14: <bevy_ecs::system::exclusive_system::ExclusiveSystemFn as bevy_ecs::system::exclusive_system::ExclusiveSystem>::run
             at ./crates/bevy_ecs/src/system/exclusive_system.rs:41:9
  15: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/stage.rs:812:25
  16: bevy_ecs::schedule::Schedule::run_once
             at ./crates/bevy_ecs/src/schedule/mod.rs:201:13
  17: <bevy_ecs::schedule::Schedule as bevy_ecs::schedule::stage::Stage>::run
             at ./crates/bevy_ecs/src/schedule/mod.rs:219:21
  18: bevy_app::app::App::update
             at ./crates/bevy_app/src/app.rs:58:9
  19: bevy_winit::winit_runner_with::{{closure}}
             at ./crates/bevy_winit/src/lib.rs:485:17
  20: winit::platform_impl::platform::sticky_exit_callback
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:736:5
  21: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:303:17
  22: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/mod.rs:398:9
  23: winit::platform_impl::platform::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/mod.rs:652:56
  24: winit::event_loop::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/event_loop.rs:154:9
  25: bevy_winit::run
             at ./crates/bevy_winit/src/lib.rs:171:5
  26: bevy_winit::winit_runner_with
             at ./crates/bevy_winit/src/lib.rs:493:9
  27: bevy_winit::winit_runner
             at ./crates/bevy_winit/src/lib.rs:211:5
  28: core::ops::function::Fn::call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:70:5
  29: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/boxed.rs:1705:9
  30: bevy_app::app::App::run
             at ./crates/bevy_app/src/app.rs:68:9
  31: bevy_app::app_builder::AppBuilder::run
             at ./crates/bevy_app/src/app_builder.rs:49:9
  32: breakout::main
             at ./examples/game/breakout.rs:9:5
  33: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Dec 30 17:05:15.064 ERROR gpu_descriptor::allocator: `DescriptorAllocator` is dropped while some descriptor sets were not deallocated
Dec 30 17:05:15.064 ERROR gpu_alloc::block: Memory block wasn't deallocated
Dec 30 17:05:15.064 ERROR gpu_alloc::block: Memory block wasn't deallocated
Dec 30 17:05:15.064 ERROR gpu_alloc::block: Memory block wasn't deallocated
Segmentation fault (core dumped)
```

I was able to find a few other reported issues in Bevy and wgpu with the same error message, but none looked to apply to my setup.  Any advice, or other information I can supply for help troubleshooting?  Should I open an issue?</div>

**Comment by alice-i-cecile** [comment]
@coreystaten can you run the `wgpu` examples successfully?

**Comment by coreystaten** [comment]
@alice-i-cecile yes, I was able to successfully run all `wgpu` examples on `latest` that are listed in the feature matrix here: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples.

**Comment by alice-i-cecile** [comment]
Okay, so probably our bug then 😆 I'm not a rendering expert, so unfortunately I can't immediately help you troubleshoot further however.

**Comment by coreystaten** [comment]
I managed to resolve the issue: I'd accidentally checked out the branch `latest` instead of `main`.  Looks like `latest` is >500 commits behind.  Everything worked fine after checking out `main`.   Thanks for the help!
