### ISSUE TITLE
Bevy panics if the font is slightly broken and Text2D with VerticalAlign::Bottom is used

### ISSUE THREAD

**Issue by johanhelsing** [bevyengine/bevy#3920]
## Bevy version

bevy: 0.6.0
ab_glyph: 0.2.11, 0.2.13

## Operating system & version

Arch linux

## What you did

1. Replaced assets/fonts/FiraSans-Bold.ttf with quicksand-light.ttf
2. Changed vertical alignment in text2d example to VerticalAlign::Bottom
3. Ran the text2d exapmle

## What you expected to happen

I expected the texts to be aligned to be anchored at the bottom of their transform. (or get some error about what's wrong with the font)

## What actually happened

The example panicked

```
~/d/bevy (font-panic|…1) cargo run --example text2d
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/examples/text2d`
2022-02-12T11:28:10.229763Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2022-02-12T11:28:10.245878Z  INFO bevy_render::renderer: AdapterInfo { name: "NVIDIA GeForce GTX 970", vendor: 4318, device: 5058, device_type: DiscreteGpu, backend: Vulkan }
thread 'Compute Task Pool (13)' panicked at 'Invalid glyph_hor_side_bearing', /home/johan/.cargo/registry/src/github.com-1ecc6299db9ec823/ab_glyph-0.2.11/src/ttfp.rs:339:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', /home/johan/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
```

## Additional information

Repro here https://github.com/johanhelsing/bevy/tree/font-panic

So most likely there is something wrong with the font I'm using. I tried a different version of it that shipped with my distro, and that worked without issues. I'm just thinking that bevy shouldn't panic if the font is slightly broken. So most likely it's something that needs to be fixed in ab_glyph?

Related: #1254

**Comment by lukors** [comment]
I got the same exact error yesterday with the .ttf of the font [Inter](https://rsms.me/inter/).

My workaround was to use one of the also included .otf versions of the font instead.
