### ISSUE TITLE
Android: Runtime Error, ANativeActivity_onCreate symbol missing

### ISSUE THREAD

**Issue by bit-garden** [bevyengine/bevy#4295]
## Bevy version

0.7.0-dev

## Operating system & version

Windows 10

## What you did

Ran `cargo apk run --example android`

## What you expected to happen

Application to open and display something

## What actually happened

The application flickered for a second, then it reported that the application keeps stopping.

## Additional information

logcat reports 
```
03-22 09:44:07.276 18841 18841 W NativeActivity: ANativeActivity_onCreate not found: undefined symbol: ANativeActivity_onCreate
03-22 09:44:07.276 18841 18841 D AndroidRuntime: Shutting down VM
03-22 09:44:07.278 18841 18841 E AndroidRuntime: FATAL EXCEPTION: main
03-22 09:44:07.278 18841 18841 E AndroidRuntime: Process: rust.example.android, PID: 18841
03-22 09:44:07.278 18841 18841 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/~~NF5KHj5ftXFAL9uuF_jQag==/rust.example.android-dPce7sL_PUXQiCoTAQy8Sg==/lib/arm64/libandroid.so": undefined symbol: ANativeActivity_onCreate
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.NativeActivity.onCreate(NativeActivity.java:178)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8098)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8082)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3475)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3670)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:250)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7766)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
03-22 09:44:07.278 18841 18841 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

**Comment by bit-garden** [comment]
https://github.com/katyo/oboe-rs/issues/28#issuecomment-1001103335

This solves the missing symbols.
