### ISSUE TITLE
Crash when running vertex_colors example

### ISSUE THREAD

**Issue by Rivide** [bevyengine/bevy#4829]
## Bevy version

0.7.0

## Operating system & version

Windows 10

## What you did

I ran the vertex_colors example here: https://github.com/bevyengine/bevy/blob/main/examples/3d/vertex_colors.rs

## What you expected to happen

I expected to see a colorful cube.

## What actually happened

Program crashed.

## Additional information
Console output:
```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 1.29s
     Running `target\debug\vertex_colors_test.exe`
2022-05-23T02:23:40.725205Z  INFO bevy_render::renderer: AdapterInfo { name: "GeForce GTX 970M", vendor: 4318, device: 5080, device_type: DiscreteGpu, backend: Vulkan }
thread 'TaskPool (5)' panicked at 'range end index 900 out of range for slice of length 864', library\core\src\slice\index.rs:73:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'task has failed', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\task.rs:425:45
error: process didn't exit successfully: `target\debug\vertex_colors_test.exe` (exit code: 101)
```
With RUST_BACKTRACE=1:
```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 1.29s
     Running `target\debug\vertex_colors_test.exe`
2022-05-23T02:29:10.112333Z  INFO bevy_render::renderer: AdapterInfo { name: "GeForce GTX 970M", vendor: 4318, device: 5080, device_type: DiscreteGpu, backend: Vulkan }
thread 'TaskPool (3)' panicked at 'range end index 900 out of range for slice of length 864', library\core\src\slice\index.rs:73:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\std\src\panicking.rs:584       
   1: core::panicking::panic_fmt
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\panicking.rs:142      
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\slice\index.rs:73     
   3: core::ops::function::FnOnce::call_once<never$ (*)(usize,usize),tuple$<usize,usize> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\ops\function.rs:248   
   4: core::intrinsics::const_eval_select<tuple$<usize,usize>,never$ (*)(usize,usize),never$ (*)(usize,usize),never$>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\intrinsics.rs:2372
   5: core::slice::index::slice_end_index_len_fail
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\slice\index.rs:67     
   6: core::slice::index::impl$3::index_mut<u8>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\slice\index.rs:315    
   7: core::slice::index::impl$1::index_mut<u8,core::ops::range::Range<usize> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\slice\index.rs:30     
   8: alloc::vec::impl$17::index_mut<u8,core::ops::range::Range<usize>,alloc::alloc::Global>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\alloc\src\vec\mod.rs:2603
   9: bevy_render::mesh::mesh::Mesh::get_vertex_buffer_data
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_render-0.7.0\src\mesh\mesh\mod.rs:241
  10: bevy_render::mesh::mesh::impl$11::prepare_asset
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_render-0.7.0\src\mesh\mesh\mod.rs:788
  11: bevy_render::render_asset::prepare_assets<bevy_render::mesh::mesh::Mesh>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_render-0.7.0\src\render_asset.rs:204
  12: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_asset::ExtractedAssets<bevy_render::mesh::mesh::Mesh> >,bevy_ecs::change_detection::ResMut<hashbrown::map::HashMap<bevy_asset::handle::Handle<bevy_render:
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\ops\function.rs:164   
  13: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_asset::ExtractedAssets<bevy_render::mesh::mesh::Mesh> >,bevy_ecs::change_detection::ResMut<hashbrown::map::HashMap<bevy_asset::handle::Handle<bevy_r
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\ops\function.rs:290   
  14: bevy_ecs::system::function_system::impl$24::run::call_inner<tuple$<>,bevy_ecs::change_detection::ResMut<bevy_render::render_asset::ExtractedAssets<bevy_render::mesh::mesh::Mesh> >,bevy_ecs::change_detection::ResMut<hashbrown::map::HashMap<bevy_asset::hand
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.7.0\src\system\function_system.rs:525
  15: bevy_ecs::system::function_system::impl$24::run<tuple$<>,void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_asset::ExtractedAssets<bevy_render::mesh::mesh::Mesh> >,bevy_ecs::change_detection::ResMut<hashbrown::map::HashMap<bevy_asset::handle:
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.7.0\src\system\function_system.rs:528
  16: bevy_ecs::system::function_system::impl$5::run_unsafe<tuple$<>,tuple$<>,tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_asset::ExtractedAssets<bevy_render::mesh::mesh::Mesh> >,bevy_ecs::change_detection::ResMut<hashbrown::map::HashMap<bevy_a
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.7.0\src\system\function_system.rs:399
  17: bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block$0
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.7.0\src\schedule\executor_parallel.rs:196
  18: core::future::from_generator::impl$1::poll<enum$<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block_env$0> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\mod.rs:91      
  19: async_executor::impl$4::spawn::async_block$0<tuple$<>,core::future::from_generator::GenFuture<enum$<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block_env$0> > >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:144
  20: core::future::from_generator::impl$1::poll<enum$<async_executor::impl$4::spawn::async_block_env$0<tuple$<>,core::future::from_generator::GenFuture<enum$<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block_env$0> > > > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\mod.rs:91      
  21: async_task::raw::RawTask<core::future::from_generator::GenFuture<enum$<async_executor::impl$4::spawn::async_block_env$0<tuple$<>,core::future::from_generator::GenFuture<enum$<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block_env$
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\raw.rs:489
  22: async_task::runnable::Runnable::run
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\runnable.rs:309
  23: async_executor::impl$4::run::async_fn$0::async_block$0<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,async_channel::Recv<tuple$<> > >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:235
  24: core::future::from_generator::impl$1::poll<enum$<async_executor::impl$4::run::async_fn$0::async_block_env$0<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,async_channel::Recv<tuple$<> > > > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\mod.rs:91      
  25: futures_lite::future::impl$12::poll<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,async_channel::Recv<tuple$<> >,core::future::from_generator::GenFuture<enum$<async_executor::impl$4::run::async_fn$0::async_block_env$0<enum$<core::result:
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:529
  26: async_executor::impl$4::run::async_fn$0<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,async_channel::Recv<tuple$<> > >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:242
  27: core::future::from_generator::impl$1::poll<enum$<async_executor::impl$4::run::async_fn_env$0<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,async_channel::Recv<tuple$<> > > > >       
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\mod.rs:91      
  28: futures_lite::future::block_on::closure$0<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,core::future::from_generator::GenFuture<enum$<async_executor::impl$4::run::async_fn_env$0<enum$<core::result::Result<tuple$<>,async_channel::RecvErro
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:89
  29: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> 
> >::try_with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum$<core::result::Result<t
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\thread\local.rs:445    
  30: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> 
> >::with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum$<core::result::Result<tuple
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\thread\local.rs:421    
  31: futures_lite::future::block_on<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,core::future::from_generator::GenFuture<enum$<async_executor::impl$4::run::async_fn_env$0<enum$<core::result::Result<tuple$<>,async_channel::RecvError> >,async_
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:79
  32: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.7.0\src\task_pool.rs:150
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'task has failed', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\task.rs:425:45
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\std\src\panicking.rs:584       
   1: core::panicking::panic_fmt
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\panicking.rs:142      
   2: core::panicking::panic_display<str>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\panicking.rs:72       
   3: core::panicking::panic_str
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\panicking.rs:56       
   4: core::option::expect_failed
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library\core\src\option.rs:1854        
   5: enum$<core::option::Option<tuple$<> > >::expect<tuple$<> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\option.rs:718
   6: async_task::task::impl$7::poll<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\task.rs:425
   7: bevy_tasks::task_pool::impl$2::scope::closure$0::async_block$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$1,tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.7.0\src\task_pool.rs:205
   8: core::future::from_generator::impl$1::poll<enum$<bevy_tasks::task_pool::impl$2::scope::closure$0::async_block_env$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$1,tuple$<> > > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\mod.rs:91      
   9: core::future::future::impl$1::poll<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,alloc::vec::Vec<tuple$<>,alloc::alloc::Global> > > > > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\future.rs:124  
  10: async_executor::impl$9::spawn::async_block$0<alloc::vec::Vec<tuple$<>,alloc::alloc::Global>,core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,alloc::vec::Vec<tuple$<>,alloc::alloc::Global> > > > > > >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:376
  11: core::future::from_generator::impl$1::poll<enum$<async_executor::impl$9::spawn::async_block_env$0<alloc::vec::Vec<tuple$<>,alloc::alloc::Global>,core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,alloc::vec::Vec<tuple$<>,alloc::alloc:
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\future\mod.rs:91      
  12: async_task::raw::RawTask<core::future::from_generator::GenFuture<enum$<async_executor::impl$9::spawn::async_block_env$0<alloc::vec::Vec<tuple$<>,alloc::alloc::Global>,core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,alloc::vec::Vec<
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\raw.rs:489
  13: async_task::runnable::Runnable::run
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.2.0\src\runnable.rs:309
  14: async_executor::Executor::try_tick
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:181
  15: async_executor::LocalExecutor::try_tick
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.1\src\lib.rs:405
  16: bevy_tasks::task_pool::impl$2::scope::closure$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$1,tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.7.0\src\task_pool.rs:234
  17: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with<async_executor::LocalExecutor,bevy_tasks::task_pool::impl$2::scope::closure_env$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$1,tuple$<> >,alloc::vec::Vec<tu
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\thread\local.rs:445    
  18: std::thread::local::LocalKey<async_executor::LocalExecutor>::with<async_executor::LocalExecutor,bevy_tasks::task_pool::impl$2::scope::closure_env$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$1,tuple$<> >,alloc::vec::Vec<tuple$
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\thread\local.rs:421    
  19: bevy_tasks::task_pool::TaskPool::scope<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$1,tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.7.0\src\task_pool.rs:180
  20: bevy_ecs::schedule::executor_parallel::impl$1::run_systems
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.7.0\src\schedule\executor_parallel.rs:129
  21: bevy_ecs::schedule::stage::impl$1::run
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.7.0\src\schedule\stage.rs:852
  22: bevy_render::impl$2::build::closure$1
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_render-0.7.0\src\lib.rs:223
  23: alloc::boxed::impl$46::call<tuple$<ref_mut$<bevy_ecs::world::World>,ref_mut$<bevy_app::app::App> 
>,dyn$<core::ops::function::Fn<tuple$<ref_mut$<bevy_ecs::world::World>,ref_mut$<bevy_app::app::App> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\alloc\src\boxed.rs:1886        
  24: bevy_app::app::App::update
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.7.0\src\app.rs:116
  25: bevy_winit::winit_runner_with::closure$0
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.7.0\src\lib.rs:563
  26: winit::platform_impl::platform::event_loop::impl$2::run_return::closure$0<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:206
  27: alloc::boxed::impl$45::call_mut<tuple$<enum$<winit::event::Event<tuple$<> > >,ref_mut$<enum$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum$<winit::event::Event<tuple$<> > >,ref_mut$<enum$<winit::event_loop::ControlFlow> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\alloc\src\boxed.rs:1879        
  28: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:245
  29: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\panic\unwind_safe.rs:271
  30: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\panicking.rs:492       
  31: hashbrown::raw::inner::bitmask::BitMask::invert
  32: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\panicking.rs:456       
  33: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\panic.rs:137
  34: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:152
  35: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_event_handler<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:239
  36: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:341
  37: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::main_events_cleared<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:227
  38: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:726
  39: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<tuple$<> >   
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:941
  40: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> >,tuple$<> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\ops\function.rs:248   
  41: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\panic\unwind_safe.rs:271
  42: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\panicking.rs:492       
  43: hashbrown::raw::inner::bitmask::BitMask::invert
  44: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > > >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\panicking.rs:456       
  45: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\std\src\panic.rs:137
  46: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop\runner.rs:152
  47: winit::platform_impl::platform::event_loop::public_window_callback_inner<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:2030
  48: winit::platform_impl::platform::event_loop::public_window_callback<tuple$<> >
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:846
  49: CallWindowProcW
  50: DispatchMessageW
  51: SendMessageTimeoutW
  52: KiUserCallbackDispatcher
  53: NtUserDispatchMessage
  54: DispatchMessageW
  55: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_return<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:221
  56: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\platform_impl\windows\event_loop.rs:191
  57: winit::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.26.1\src\event_loop.rs:154
  58: bevy_winit::run<bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.7.0\src\lib.rs:180
  59: bevy_winit::winit_runner_with
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.7.0\src\lib.rs:604
  60: bevy_winit::winit_runner
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.7.0\src\lib.rs:220
  61: core::ops::function::Fn::call<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\ops\function.rs:77    
  62: alloc::boxed::impl$46::call<tuple$<bevy_app::app::App>,dyn$<core::ops::function::Fn<tuple$<bevy_app::app::App>,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\alloc\src\boxed.rs:1886        
  63: bevy_app::app::App::run
             at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.7.0\src\app.rs:130
  64: vertex_colors_test::main
             at .\src\main.rs:6
  65: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff\library\core\src\ops\function.rs:248   
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\vertex_colors_test.exe` (exit code: 101)
```

**Comment by hoshino111** [comment]
Try to run it on master branch.

**Comment by Rivide** [comment]
Thanks, that worked. I didn't realize this feature was new.
