### ISSUE TITLE
Adding DefaultPlugins to the App panics with `default-features = false`

### ISSUE THREAD

**Issue by FelixBrakel** [bevyengine/bevy#5573]
## Bevy version
0.8

## What you did
Use Bevy without default features and add the `DefaultPlugins` to the `App`

`cargo.toml`:
```toml
[dependencies.bevy]
version = "0.8.0"
default-features = false
features = ["dynamic"]
```
`main.rs`:
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).run();
}
```

## What went wrong
The code panics with the following backtrace:
```
thread 'main' panicked at 'Requested resource bevy_asset::asset_server::AssetServer does not exist in the `World`. 
                Did you forget to add it using `app.insert_resource` / `app.init_resource`? 
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.', /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.8.0/src/assets.rs:324:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1b57946a405d5b2a87e612335db033edb2c3427f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1b57946a405d5b2a87e612335db033edb2c3427f/library/core/src/panicking.rs:142:14
   2: bevy_ecs::world::World::resource
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.8.0/src/world/mod.rs:817:21
   3: <bevy_app::app::App as bevy_asset::assets::AddAsset>::add_asset
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.8.0/src/assets.rs:324:32
   4: <bevy_render::RenderPlugin as bevy_app::plugin::Plugin>::build
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.8.0/src/lib.rs:130:9
   5: bevy_app::plugin_group::PluginGroupBuilder::finish
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.8.0/src/plugin_group.rs:135:21
   6: bevy_app::app::App::add_plugins
             at /home/felix/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.8.0/src/app.rs:810:9
   7: viewer::main
             at ./bin/viewer/main.rs:20:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/1b57946a405d5b2a87e612335db033edb2c3427f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Additional information
It looks like the recent change that removed `bevy_asset` from `no-default-features` caused this issue as adding `bevy_asset` to the features functions as a workaround.

**Comment by alice-i-cecile** [comment]
Ping @mockersf with complaints ;)

**Comment by alice-i-cecile** [comment]
We should really be testing this specific combination in CI IMO. It's natural and important.

**Comment by mockersf** [comment]
I can't reproduce locally, `default-features = false` is working correctly.

Given your stack trace, you have at least the feature `bevy_render` enabled. Enabling that one, I can reproduce. Are you sure about your features?

**Comment by FelixBrakel** [comment]
Hey, sorry for the late response. Turns out one of my dependencies did enable the `render` feature. I can confirm that if I remove all dependencies except for bevy and disable the default features it does not panic unless I add `render`. Again if I add the `bevy_asset` feature that fixes the problem.

I haven't checked if there are any other features also cause it to panic.
