### ISSUE TITLE
AssetLoadError: No such file or directory

### ISSUE THREAD

**Issue by Karatla** [bevyengine/bevy#563]
```
use bevy::prelude::*;
fn main() {
    App::build()
        .add_default_plugins()
        .add_startup_system(setup.system())
        .add_system(animate_sprite_system.system())
        .run();
}

fn animate_sprite_system(
    texture_atlases: Res<Assets<TextureAtlas>>,
    mut query: Query<(&mut Timer, &mut TextureAtlasSprite, &Handle<TextureAtlas>)>,
) {
    for (timer, mut sprite, texture_atlas_handle) in &mut query.iter() {
        if timer.finished {
            let texture_atlas = texture_atlases.get(&texture_atlas_handle).unwrap();
            sprite.index = ((sprite.index as usize + 1) % texture_atlas.textures.len()) as u32;
        }
    }
}

fn setup(
    mut commands: Commands,
    asset_server: Res<AssetServer>,
    mut textures: ResMut<Assets<Texture>>,
    mut texture_atlases: ResMut<Assets<TextureAtlas>>,
) {
    let texture_handle = asset_server
        .load_sync(
            &mut textures,
            "assets/icon2.png",
        )
        .unwrap();
    let texture = textures.get(&texture_handle).unwrap();
    let texture_atlas = TextureAtlas::from_grid(texture_handle, texture.size, 7, 1);
    let texture_atlas_handle = texture_atlases.add(texture_atlas);
    commands
        .spawn(Camera2dComponents::default())
        .spawn(SpriteSheetComponents {
            texture_atlas: texture_atlas_handle,
            transform: Transform::from_scale(6.0),
            ..Default::default()
        })
        .with(Timer::from_seconds(0.1, true));}
````

I tried example 2d sprite_sheet.rs. but it error.
````
thread 'Compute Task Pool (4)' panicked at 'called `Result::unwrap()` on an `Err` value: AssetLoadError(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', src/main.rs:34:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (1)' panicked at 'task has failed', /Users/july/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.2/src/task.rs:368:45
thread 'main' panicked at 'task has failed', /Users/july/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.2/src/task.rs:368:45
thread 'main' panicked at 'task thread panicked while executing: Any', /Users/july/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.2.1/src/task_pool.rs:72:18
stack backtrace:
   0:        0x10e9bcebe - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h24bb64d98a7e25d6
   1:        0x10e9e4cec - core::fmt::write::h8fdc9cddb01cd8b2
   2:        0x10e9b8ba9 - std::io::Write::write_fmt::hcc3030013983bab6
   3:        0x10e9bf385 - std::panicking::default_hook::{{closure}}::h95817712c5ff0736
   4:        0x10e9bf0c2 - std::panicking::default_hook::h34e085f4e0b1062d
   5:        0x10e9bf8e5 - std::panicking::rust_panic_with_hook::haf571858f996ac45
   6:        0x10e9bf4b2 - rust_begin_unwind
   7:        0x10ea0ab1f - core::panicking::panic_fmt::h11676ba6a846d9f4
   8:        0x10ea0aa25 - core::option::expect_none_failed::h312e48bacb63d8ec
   9:        0x10e94d566 - core::result::Result<T,E>::expect::hccba4598032c3fc7
  10:        0x10e946da5 - <bevy_tasks::task_pool::TaskPoolInner as core::ops::drop::Drop>::drop::h10b7d32cfc423061
  11:        0x10e943fb5 - core::ptr::drop_in_place::h867fd16053841198
  12:        0x10e8aa232 - alloc::sync::Arc<T>::drop_slow::h89466007fee365e8
  13:        0x10e8aa4ea - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::hd17b6cb5b660a0d4
  14:        0x10e8c4a81 - core::ptr::drop_in_place::h873c5dbf2c9a6bd8
  15:        0x10e8c42ee - core::ptr::drop_in_place::h3ba5a5e9f322dd21
  16:        0x10e8c5081 - core::ptr::drop_in_place::hcca84559224499d7
  17:        0x10e88e5d1 - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::hbbb1c5e967090493
  18:        0x10e88681e - bevy_hecs::archetype::TypeInfo::of::drop_ptr::h99c649af2f70879e
  19:        0x10e99fed6 - bevy_hecs::archetype::Archetype::clear::h7902221687699689
  20:        0x10e9a1275 - <bevy_hecs::archetype::Archetype as core::ops::drop::Drop>::drop::h26717570de4ff620
  21:        0x10e992815 - core::ptr::drop_in_place::hcd5661a3b8145998
  22:        0x10e88dde5 - core::ptr::drop_in_place::h99502588e04febb7
  23:        0x10e88e558 - core::ptr::drop_in_place::hfd1ad68ced37981b
  24:        0x10e874fb1 - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::hce58d892be349064
  25:        0x10e86b1ce - hashbrown::raw::Bucket<T>::drop::h8a053bca44993875
  26:        0x10e86a9b1 - <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop::h5fcffd6babdb635a
  27:        0x10e88e241 - core::ptr::drop_in_place::hd82e3d5b3de8e5f0
  28:        0x10e88dbc8 - core::ptr::drop_in_place::h6064242c6bbf413a
  29:        0x10e88e591 - core::ptr::drop_in_place::hfffd864059302576
  30:        0x10e88d521 - core::ptr::drop_in_place::h1341675f3b020e50
  31:        0x10e88dadc - core::ptr::drop_in_place::h4f1c43afc3945a37
  32:        0x10e887887 - bevy_app::app::App::run::h7fa59cf71e00d3ae
  33:        0x10e88a190 - bevy_app::app_builder::AppBuilder::run::hf4077c4d04a50325
  34:        0x10d5479b1 - game::main::hcdf658c0f1824563
  35:        0x10d55075e - std::rt::lang_start::{{closure}}::h718e957d2c568218
  36:        0x10e9bfbaf - std::rt::lang_start_internal::hcd84a36052901671
  37:        0x10d550741 - std::rt::lang_start::h9061a70f0675a0ba
  38:        0x10d5480b2 - main
thread panicked while panicking. aborting.
Illegal instruction: 4
````

i have assets in my folder

**Comment by Karatla** [comment]
sorry i made a misstake. I create assets folder in src.
