### ISSUE TITLE
Panic when running the breakout example

### ISSUE THREAD

**Issue by mcobzarenco** [bevyengine/bevy#575]
First off -- great project! I think it has great potential and :100: for all the hard work.

Cloning a fresh copy of the repo and running `cargo run --example breakout` panics with
```
thread 'main' panicked at 'index 12 extends beyond limit 7', /home/marius/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1
```

This is on Linux (Ubuntu 20.04) with an integrated Intel card. The relevant part of the backtrace:
```
  13: <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty::{{closure}}
             at /home/marius/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323
  14: core::result::Result<T,E>::unwrap_or_else
             at /home/marius/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:853
  15: <core::result::Result<T,E> as wgpu::backend::direct::PrettyResult<T>>::unwrap_pretty
             at /home/marius/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1323
  16: <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass
             at /home/marius/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/backend/direct.rs:1237
  17: <wgpu::RenderPass as core::ops::drop::Drop>::drop
             at /home/marius/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.6.0/src/lib.rs:2257
  18: core::ptr::drop_in_place
             at /home/marius/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:184
  19: core::ptr::drop_in_place
             at /home/marius/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ptr/mod.rs:184
  20: <bevy_wgpu::renderer::wgpu_render_context::WgpuRenderContext as bevy_render::renderer::render_context::RenderContext>::begin_pass
             at crates/bevy_wgpu/src/renderer/wgpu_render_context.rs:151
  21: <bevy_render::render_graph::nodes::pass_node::PassNode<Q> as bevy_render::render_graph::node::Node>::update
             at ./crates/bevy_render/src/render_graph/nodes/pass_node.rs:175
  22: bevy_wgpu::renderer::wgpu_render_graph_executor::WgpuRenderGraphExecutor::execute
             at crates/bevy_wgpu/src/renderer/wgpu_render_graph_executor.rs:72
  23: bevy_wgpu::wgpu_renderer::WgpuRenderer::run_graph
             at crates/bevy_wgpu/src/wgpu_renderer.rs:94
  24: bevy_wgpu::wgpu_renderer::WgpuRenderer::update
             at crates/bevy_wgpu/src/wgpu_renderer.rs:105
```

**Comment by cart** [comment]
Hey sorry about that. A few hours ago we merged something that caused text rendering to panic. You are hitting the same problem reported in #573.

This should be fixed by #574

**Comment by cart** [comment]
Can you fetch the latest master and try again?

**Comment by mcobzarenco** [comment]
Thanks for the prompt response. 

Fair enough re:text rendering being the issue, I noticed that removing the scoreboard system fixed the panic. I'll try again with latest master tonight. Happy to close the issue asap if you could reproduce and it's now fixed 👍

**Comment by mcobzarenco** [comment]
All good :+1:
