### ISSUE TITLE
Setting texture to png loaded from asset server causes crash

### ISSUE THREAD

**Issue by jmrgibson** [bevyengine/bevy#588]
Please see minimal example here https://github.com/jmrgibson/tntw/blob/bug_example/src/main.rs#L91

Trying to set a texture to a handle loaded from the asset server causes a crash. Setting a normal color texture works fine.

or, if I'm doing something wrong, please let me know :)

On ubuntu 20.04, nightly-2020-09-20

```
thread 'Compute Task Pool (1)' panicked at 'called `Option::unwrap()` on a `None` value', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.2.1/src/shader/shader_defs.rs:101:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (3)' panicked at 'task has failed', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.0/src/task.rs:368:45
thread 'main' panicked at 'task has failed', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.0/src/task.rs:368:45
thread 'main' panicked at 'task thread panicked while executing: Any', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.2.1/src/task_pool.rs:72:18
stack backtrace:
thread '<unnamed>' panicked at 'loaded asset should have been sent: "SendError(..)"', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.2.1/src/load_request.rs:71:14
thread '<unnamed>' panicked at 'loaded asset should have been sent: "SendError(..)"', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.2.1/src/load_request.rs:71:14
thread '<unnamed>' panicked at 'loaded asset should have been sent: "SendError(..)"', /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_asset-0.2.1/src/load_request.rs:71:14
   0:     0x55c4b0437320 - std::backtrace_rs::backtrace::libunwind::trace::he85dfb3ae4206056
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55c4b0437320 - std::backtrace_rs::backtrace::trace_unsynchronized::h1ad28094d7b00c21
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55c4b0437320 - std::sys_common::backtrace::_print_fmt::h901b54610713cd21
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/sys_common/backtrace.rs:79
   3:     0x55c4b0437320 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb0ad78ee1571f7e0
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/sys_common/backtrace.rs:58
   4:     0x55c4b045ee0c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/core/src/fmt/mod.rs:1080
   5:     0x55c4b0433337 - std::io::Write::write_fmt::hf7b7d7b243f84a36
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/io/mod.rs:1517
   6:     0x55c4b0439bf0 - std::sys_common::backtrace::_print::hd093978a5287b8ff
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/sys_common/backtrace.rs:61
   7:     0x55c4b0439bf0 - std::sys_common::backtrace::print::h20f46787581d56d7
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/sys_common/backtrace.rs:48
   8:     0x55c4b0439bf0 - std::panicking::default_hook::{{closure}}::h486cbb4b82ffc357
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:208
   9:     0x55c4b04398a8 - std::panicking::default_hook::h4190c9e3edd4d591
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:227
  10:     0x55c4b043a2c1 - std::panicking::rust_panic_with_hook::h72e78719cdda225c
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:577
  11:     0x55c4b0439e69 - std::panicking::begin_panic_handler::{{closure}}::h8bd07dbd34150a96
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:484
  12:     0x55c4b04377ac - std::sys_common::backtrace::__rust_end_short_backtrace::hdb6b3066ad29028a
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/sys_common/backtrace.rs:153
  13:     0x55c4b0439e29 - rust_begin_unwind
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:483
  14:     0x55c4b045ca01 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/core/src/panicking.rs:85
  15:     0x55c4b045c823 - core::option::expect_none_failed::he492a18657d97593
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/core/src/option.rs:1221
  16:     0x55c4b03913a1 - core::result::Result<T,E>::expect::h29b73787a8ec70e0
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:933
  17:     0x55c4b0381276 - <bevy_tasks::task_pool::TaskPoolInner as core::ops::drop::Drop>::drop::h07d7a271a6e64ee3
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.2.1/src/task_pool.rs:70
  18:     0x55c4b0387276 - core::ptr::drop_in_place::ha33072fcd31a74ba
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  19:     0x55c4b02e8c24 - alloc::sync::Arc<T>::drop_slow::hfba4894fb3363d8f
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:934
  20:     0x55c4b02e8f76 - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::ha231f7977809cc16
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/sync.rs:1454
  21:     0x55c4b030050f - core::ptr::drop_in_place::hd041741fcc4318a7
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  22:     0x55c4b02ffad1 - core::ptr::drop_in_place::h5aef3c8ecf67e347
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  23:     0x55c4b030052f - core::ptr::drop_in_place::hd6e7cfea87e41473
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  24:     0x55c4b02c3adb - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::h04a1c99d74b9da05
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mut_ptr.rs:963
  25:     0x55c4b02b202f - bevy_hecs::archetype::TypeInfo::of::drop_ptr::h3701eca5cc01d600
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_hecs-0.2.1/src/archetype.rs:487
  26:     0x55c4b040b917 - bevy_hecs::archetype::Archetype::clear::h4344c469837b101e
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_hecs-0.2.1/src/archetype.rs:85
  27:     0x55c4b040cee3 - <bevy_hecs::archetype::Archetype as core::ops::drop::Drop>::drop::h19ad5305120b9321
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_hecs-0.2.1/src/archetype.rs:419
  28:     0x55c4b03fb6f6 - core::ptr::drop_in_place::h432379367e45f215
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  29:     0x55c4b02c3446 - core::ptr::drop_in_place::hb719a9db07c96e63
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  30:     0x55c4b02c3056 - core::ptr::drop_in_place::h8ca4bdf0dfebb0f9
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  31:     0x55c4b02ab99b - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::hbcfdd441977c9288
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mut_ptr.rs:963
  32:     0x55c4b02b4a4f - hashbrown::raw::Bucket<T>::drop::h98e9e116732d5d7c
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:334
  33:     0x55c4b02b4285 - <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop::hf403b266fd453f7a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.9.0/src/raw/mod.rs:1325
  34:     0x55c4b02c2c2f - core::ptr::drop_in_place::h42fa54e8e3b3b63e
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  35:     0x55c4b02c2c86 - core::ptr::drop_in_place::h4adfc0f0d4f132cc
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  36:     0x55c4b02c351f - core::ptr::drop_in_place::hcb40e1804e3902af
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  37:     0x55c4b02c302f - core::ptr::drop_in_place::h8c7dd30c3ce21ea2
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  38:     0x55c4b02c2908 - core::ptr::drop_in_place::h1ce4310c4ce29d7e
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  39:     0x55c4af54625f - core::ptr::drop_in_place::hb5c60abefdc71d8d
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:175
  40:     0x55c4af5bea8a - cart_tmp_winit::platform_impl::platform::x11::EventLoop<T>::run_return::h684465e584349341
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/x11/mod.rs:380
  41:     0x55c4af5c010e - cart_tmp_winit::platform_impl::platform::x11::EventLoop<T>::run::hb8adc26821864fda
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/x11/mod.rs:386
  42:     0x55c4af5b0463 - cart_tmp_winit::platform_impl::platform::EventLoop<T>::run::ha7e88c559280c211
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/platform_impl/linux/mod.rs:620
  43:     0x55c4af598c78 - cart_tmp_winit::event_loop::EventLoop<T>::run::h3041865cdb1f45d0
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/cart-tmp-winit-0.22.2/src/event_loop.rs:149
  44:     0x55c4af53bac8 - bevy_winit::run::hd6ea2d6615e5ba5a
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.2.1/src/lib.rs:42
  45:     0x55c4af53be22 - bevy_winit::winit_runner::h76562bf684cedd90
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_winit-0.2.1/src/lib.rs:220
  46:     0x55c4af542c2f - core::ops::function::Fn::call::h691d5eeee3ea0cf7
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:70
  47:     0x55c4b02c040a - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h763f938a74cba494
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1056
  48:     0x55c4b02c0aa1 - bevy_app::app::App::run::h2006cb9719c95d1c
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.2.1/src/app.rs:82
  49:     0x55c4b02c18e5 - bevy_app::app_builder::AppBuilder::run::hd46ca25e51b7cda6
                               at /home/joel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.2.1/src/app_builder.rs:45
  50:     0x55c4aebb7835 - tntw::main::h1e51cf1c80f537de
                               at /home/joel/workspace/tntw/src/main.rs:43
  51:     0x55c4aebbeb5b - core::ops::function::FnOnce::call_once::hcadb5f3a731eed44
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  52:     0x55c4aebadc3e - std::sys_common::backtrace::__rust_begin_short_backtrace::h980b7c68b4bb93fa
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  53:     0x55c4aebacd01 - std::rt::lang_start::{{closure}}::h4e8e3842a6d781a2
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  54:     0x55c4b043a6a1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5e15f43ce28787f7
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/core/src/ops/function.rs:259
  55:     0x55c4b043a6a1 - std::panicking::try::do_call::h764f1891769113e9
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:381
  56:     0x55c4b043a6a1 - std::panicking::try::h0f2fe4fdd5e0ad19
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panicking.rs:345
  57:     0x55c4b043a6a1 - std::panic::catch_unwind::h1634e40dd3a19f80
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/panic.rs:382
  58:     0x55c4b043a6a1 - std::rt::lang_start_internal::h8d4bc7b854bbd5fe
                               at /rustc/f68e08933d8f519a9655934fedebbc509661b219/library/std/src/rt.rs:51
  59:     0x55c4aebaccd7 - std::rt::lang_start::h8ca3085e736e35a7
                               at /home/joel/.rustup/toolchains/nightly-2020-09-20-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  60:     0x55c4aebb803a - main
  61:     0x7f7eb39800b3 - __libc_start_main
  62:     0x55c4aebaaeee - _start
  63:                0x0 - <unknown>
```

**Comment by Bobox214** [comment]
The texture you are loading must be added to the materials assets in the same way your are doing with the Color, or like the sprite.rs example is doing.
I have removed the panic with the modification of the following code : 
```rust
fn setup(
    mut commands: Commands,
    selection_materials: Res<SelectionMaterials>,
    asset_server: Res<AssetServer>,
    mut materials: ResMut<Assets<ColorMaterial>>,   // NEW
) {
    
    commands.insert_resource(UiStateMaterials {
        idle: materials.add(asset_server.load("assets/textures/idle.png").unwrap().into()),  // UPDATED
        moving: materials.add(asset_server.load("assets/textures/move.png").unwrap().into()),  // UPDATED
        moving_fast: materials.add(asset_server.load("assets/textures/move_fast.png").unwrap().into()), // UPDATED
    });
   .....
```

Error handling is currently almost non-existent in bevy, and is not yet the main priority.

Let us know if this answer helped you move forward.

**Comment by jmrgibson** [comment]
Yup, that fixes things, thanks. Are you looking for people to help with error handling? I'm pretty familiar with rust and have become spoiled by the compilers good error messages and have gotten into a "if-it-compiles-it-works" mentality, but I understand if there is not much point focusing on this area if everything is still in a state of flux.

**Comment by cart** [comment]
In this particular case, I'm working on a pretty major Asset overhaul, so theres not much point investing in a fix here. However in general I would like to start improving our error handling. For non-asset things, feel free to open issues and/or prs to add error handling where it is needed.

We favor `thiserror` for error types in most cases (search the repo for current examples of how we do this).

**Comment by alice-i-cecile** [comment]
Closing due to staleness + solution given <3 Error handling is slowly improving; we'll do our best to improve this as we work on asset improvements.
