### ISSUE TITLE
Intermittent test failure on `systems::test::correct_transforms_when_no_children` in `bevy_transform`

### ISSUE THREAD

**Issue by targrub** [bevyengine/bevy#6081]
## Bevy version

Any recent commit, like https://github.com/bevyengine/bevy/commit/fb74ca3d4644cf31afefe62ecd5e566794211290 or https://github.com/bevyengine/bevy/commit/a09dd034a2695dec504fbe45c4441cc459c9b08d

## Relevant system information

Windows 11, stable 1.64.0

## What you did

`cargo run -p ci` on my machine

## What went wrong

```
     Running unittests src\lib.rs (target\debug\deps\bevy_transform-15b5c6f3f18cfb6b.exe)

running 5 tests
test systems::test::did_propagate_command_buffer ... ok
test systems::test::did_propagate ... ok
test systems::test::correct_children ... ok
test systems::test::correct_transforms_when_no_children ... FAILED
test systems::test::panic_when_hierarchy_cycle - should panic ... ok

failures:

---- systems::test::correct_transforms_when_no_children stdout ----
thread 'systems::test::correct_transforms_when_no_children' panicked at 'assertion failed: `(left == right)`
  left: `0v0`,
 right: `2v0`: Malformed hierarchy. This probably means that your hierarchy has been improperly maintained, or contains a cycle', crates\bevy_transform\src\systems.rs:69:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
   2: core::fmt::Arguments::new_v1
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\fmt\mod.rs:394
   3: core::panicking::assert_failed_inner
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:218
   4: core::panicking::assert_failed<bevy_ecs::entity::Entity,bevy_ecs::entity::Entity>
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\panicking.rs:181
   5: bevy_transform::systems::propagate_recursive
             at .\src\systems.rs:69
   6: bevy_transform::systems::transform_propagate_system
             at .\src\systems.rs:38
   7: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::system::query::Query<tuple$<enum$<core::option::Option<tuple$<ref$<bevy_hierarchy::components::children::Children>,bevy_ecs::query::filter::Changed<bevy_hierarchy::components::children::Children> > >
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:164
   8: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::system::query::Query<tuple$<enum$<core::option::Option<tuple$<ref$<bevy_hierarchy::components::children::Children>,bevy_ecs::query::filter::Changed<bevy_hierarchy::components::children::Childre
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:290
  ...
  29: bevy_transform::systems::test::correct_transforms_when_no_children
             at .\src\systems.rs:303
  30: bevy_transform::systems::test::correct_transforms_when_no_children::closure$0
             at .\src\systems.rs:278
  31: core::ops::function::FnOnce::call_once<bevy_transform::systems::test::correct_transforms_when_no_children::closure_env$0,tuple$<> >
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
  32: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    systems::test::correct_transforms_when_no_children

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass '-p bevy_transform --lib'
thread 'main' panicked at 'Please fix failing tests in output above.: command exited with non-zero code `cargo test --workspace --lib --bins --tests --benches`: 101', tools\ci\src\main.rs:103:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library\core\src\result.rs:1814
   3: enum$<core::result::Result<tuple$<>,xshell::error::Error>, 1, 18446744073709551615, Err>::expect<tuple$<>,xshell::error::Error>
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\result.rs:1064
   4: ci::main
             at .\tools\ci\src\main.rs:101
   5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\ci.exe` (exit code: 101)
```

## Additional information

The same command almost always works ok (i.e., the test passes) if I run it immediately afterwards.

**Comment by hymm** [comment]
I think this is the same issue as https://github.com/bevyengine/bevy/issues/6036.

**Comment by targrub** [comment]
Interesting.  I've never had a failure in the did_propagate test, always in this one.  But the commonality of the assert, `Malformed hierarchy. This probably means that your hierarchy has been improperly maintained`, is a gun producing some smoke.

**Comment by hymm** [comment]
it's an issue with the panicking test. When the test panics it causes other test's systems not to run if they're on the thread that panics.

**Comment by oddfacade** [comment]
i think this may also affect `systems::test::correct_children` as i'm getting an intermittent failure there too.

**Comment by mockersf** [comment]
closing for #5285
