### ISSUE TITLE
AudioOutput.play() panics on Ogg Vorbis files if `vorbis` feature is not opted in

### ISSUE THREAD

**Issue by akien-mga** [bevyengine/bevy#640]
- Bevy 0.2.1 and 6f287fb81570b40a3ca4c1f4734d901cb254c41d, no custom feature enabled
- Rust 1.46.0
- Mageia 8 x86_64

With the following startup system, I get an unrecoverable panic when calling `AudioOutput.play()` with an Ogg Vorbis file:
```rust
fn setup(asset_server: Res<AssetServer>, audio_output: Res<AudioOutput>) {
    let music = asset_server
        .load("WindlessSlopes.ogg")
        .unwrap(); // No load error.
    audio_output.play(music); // Panic.
}
```

Enabling the `vorbis` feature in `Cargo.toml` solves it, but I think that users should be given the opportunity to handle a load or play error before panicking.

Error output:
```
thread 'Compute Task Pool (0)' panicked at 'called `Result::unwrap()` on an `Err` value: UnrecognizedFormat', /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_audio/src/audio_source.rs:44:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (2)' panicked at 'task has failed', /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.2/src/task.rs:368:45
thread 'main' panicked at 'task has failed', /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.2/src/task.rs:368:45
thread 'main' panicked at 'task thread panicked while executing: Any', /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_tasks/src/task_pool.rs:74:18
stack backtrace:
   0:     0x5631db0a8fe5 - backtrace::backtrace::libunwind::trace::h494717d7f79335cb
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/vendor/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5631db0a8fe5 - backtrace::backtrace::trace_unsynchronized::h735c859cde79e119
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/vendor/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5631db0a8fe5 - std::sys_common::backtrace::_print_fmt::h295999a958796628
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5631db0a8fe5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hccef9928fd5d8e8e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5631db0d16cc - core::fmt::write::h26a0fba054cf05aa
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5631db0a4f92 - std::io::Write::write_fmt::hd57143dc22113315
                               at src/libstd/io/mod.rs:1537
   6:     0x5631db0abc80 - std::sys_common::backtrace::_print::h922f6b97c13c1b42
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5631db0abc80 - std::sys_common::backtrace::print::hfb0d19ec5a7345d4
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5631db0abc80 - std::panicking::default_hook::{{closure}}::h99172b9922b7418f
                               at src/libstd/panicking.rs:198
   9:     0x5631db0ab9cc - std::panicking::default_hook::h32d36b757bdc2acf
                               at src/libstd/panicking.rs:217
  10:     0x5631db0ac2c3 - std::panicking::rust_panic_with_hook::ha0df282b33979e96
                               at src/libstd/panicking.rs:526
  11:     0x5631db0abebb - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x5631db0cf311 - core::panicking::panic_fmt::h4a347a4fdf0d3bfc
                               at src/libcore/panicking.rs:85
  13:     0x5631db0cf133 - core::option::expect_none_failed::h17cceb7a5f52e35c
                               at src/libcore/option.rs:1269
  14:     0x5631db0189c6 - core::result::Result<T,E>::expect::h6059a49660a3d525
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/result.rs:963
  15:     0x5631db013cf6 - <bevy_tasks::task_pool::TaskPoolInner as core::ops::drop::Drop>::drop::hc82c84871bc834b8
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_tasks/src/task_pool.rs:72
  16:     0x5631db00e3f6 - core::ptr::drop_in_place::h3c3e1983f63a4350
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  17:     0x5631daf70b04 - alloc::sync::Arc<T>::drop_slow::h4438e22dcfbed5e6
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/liballoc/sync.rs:864
  18:     0x5631daf70efc - <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop::hc29a1d4235257045
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/liballoc/sync.rs:1386
  19:     0x5631daf8b8bf - core::ptr::drop_in_place::h9db3d74c9d49be8f
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  20:     0x5631daf8acf1 - core::ptr::drop_in_place::h2738079d518d5f6c
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  21:     0x5631daf8b6ef - core::ptr::drop_in_place::h7b7624366e039f2e
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  22:     0x5631daf8369b - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::ha5af73cb91ac44f3
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mut_ptr.rs:846
  23:     0x5631daf844df - bevy_hecs::archetype::TypeInfo::of::drop_ptr::h21853a681164198a
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_ecs/hecs/src/archetype.rs:496
  24:     0x5631db089c39 - bevy_hecs::archetype::Archetype::clear::h2b26099e78130915
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_ecs/hecs/src/archetype.rs:86
  25:     0x5631db08b353 - <bevy_hecs::archetype::Archetype as core::ops::drop::Drop>::drop::h638f7fb2325a5563
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_ecs/hecs/src/archetype.rs:427
  26:     0x5631db071966 - core::ptr::drop_in_place::hd02c8c675667b57a
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  27:     0x5631daf8c0c6 - core::ptr::drop_in_place::hd18b4913cf894784
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  28:     0x5631daf8b646 - core::ptr::drop_in_place::h6c8818d611ecef38
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  29:     0x5631daf8c6ab - core::ptr::mut_ptr::<impl *mut T>::drop_in_place::h6d3e2a977d750692
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mut_ptr.rs:846
  30:     0x5631daf5544f - hashbrown::raw::Bucket<T>::drop::h0178da6687ad073a
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/vendor/hashbrown/src/raw/mod.rs:307
  31:     0x5631daf546b1 - <hashbrown::raw::RawTable<T> as core::ops::drop::Drop>::drop::hc3640c02b9a50a0d
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/vendor/hashbrown/src/raw/mod.rs:1041
  32:     0x5631daf8aacf - core::ptr::drop_in_place::h20ec906088fd5cc9
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  33:     0x5631daf43836 - core::ptr::drop_in_place::hb81141c05dcac69e
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  34:     0x5631daf429bf - core::ptr::drop_in_place::h0fe16ddc76ede995
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  35:     0x5631daf4291f - core::ptr::drop_in_place::h03a166407e9f052d
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  36:     0x5631daf42b28 - core::ptr::drop_in_place::h1459e755f4036dcb
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  37:     0x5631da43c00f - core::ptr::drop_in_place::h3f647a6614b477b9
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ptr/mod.rs:184
  38:     0x5631da412b0a - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h077b5133685b1255
                               at /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:380
  39:     0x5631da41412f - winit::platform_impl::platform::x11::EventLoop<T>::run::h673e850bbee83e28
                               at /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/x11/mod.rs:386
  40:     0x5631da40bf8c - winit::platform_impl::platform::EventLoop<T>::run::hcc8ddd0dfc3c8aa2
                               at /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/platform_impl/linux/mod.rs:642
  41:     0x5631da40bdb7 - winit::event_loop::EventLoop<T>::run::h3b9aa76291d2e7de
                               at /home/akien/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.23.0/src/event_loop.rs:154
  42:     0x5631da41f597 - bevy_winit::run::h286c19adc4d15095
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_winit/src/lib.rs:40
  43:     0x5631da41f8ef - bevy_winit::winit_runner::hfc23224447195d01
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_winit/src/lib.rs:218
  44:     0x5631da43b361 - core::ops::function::Fn::call::h7b799c5b0f51117d
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libcore/ops/function.rs:72
  45:     0x5631daf3ed6a - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::h472ca16a4f27496e
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/liballoc/boxed.rs:1095
  46:     0x5631daf3d7b6 - bevy_app::app::App::run::hafe649eca90e1215
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_app/src/app.rs:78
  47:     0x5631daf44285 - bevy_app::app_builder::AppBuilder::run::h0a446f96161c4dc0
                               at /home/akien/.cargo/git/checkouts/bevy-f7ffde730c324c74/6f287fb/crates/bevy_app/src/app_builder.rs:43
  48:     0x5631d9c3b4d8 - bevy_audio_play_panic::main::hcaf1e037b7cb5585
                               at src/main.rs:5
  49:     0x5631d9c3dd1b - std::rt::lang_start::{{closure}}::h4b6c129e45189f88
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libstd/rt.rs:67
  50:     0x5631db0ac693 - std::rt::lang_start_internal::{{closure}}::h8af6d7a330c65c2b
                               at src/libstd/rt.rs:52
  51:     0x5631db0ac693 - std::panicking::try::do_call::hb65cf0ee5bc234f8
                               at src/libstd/panicking.rs:348
  52:     0x5631db0ac693 - std::panicking::try::hc148103d32eaf87f
                               at src/libstd/panicking.rs:325
  53:     0x5631db0ac693 - std::panic::catch_unwind::he14af95145cd9e7b
                               at src/libstd/panic.rs:394
  54:     0x5631db0ac693 - std::rt::lang_start_internal::h08007c1e8473743f
                               at src/libstd/rt.rs:51
  55:     0x5631d9c3dcf7 - std::rt::lang_start::h259ec88f69153ac1
                               at /home/iurt/rpmbuild/BUILD/rustc-1.46.0-src/src/libstd/rt.rs:67
  56:     0x5631d9c3b5ba - main
  57:     0x7f5093023cda - __libc_start_main
  58:     0x5631d9c3421a - _start
  59:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

**Minimal reproduction project:**
[bevy_audio_play_panic.zip](https://github.com/bevyengine/bevy/files/5339216/bevy_audio_play_panic.zip)
(Adapted from the official `example/audio/audio.rs`, the MP3 file converted to OGG Vorbis with `fmpeg -i <input>.mp3 <output>.ogg`.)

**Comment by cart** [comment]
Loading happens asynchronously in a non-blocking manner.  We can't provide / handle load errors at the point where load is called because the load hasn't happened yet.

`audio_output.play()` is also asynchronous. It will play the audio as soon as it has loaded.

```rust
// this just kicks off the process
let music = asset_server
    .load("WindlessSlopes.ogg")
    .unwrap(); // No load error.

// doesn't immediately panic. it panics (in a separate thread without crashing) in the latest Bevy
audio_output.play(music); // Panic.
```

That being said, we should provide a way for users to respond to asset load errors. This should probably happen by adding downcastable errors to an event queue.
