### ISSUE TITLE
PBR involved examples are broken

### ISSUE THREAD

**Issue by floppyhammer** [bevyengine/bevy#6844]
## Bevy version

6ada3566aca363414cb4a117dabbb6727acae4d5

## What you did

Run PBR involved examples.

## What went wrong

App panics.

## Additional information

```
C:/Users/tannh/.cargo/bin/cargo.exe +nightly run --color=always --package bevy --example pbr
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target\debug\examples\pbr.exe`
2022-12-04T08:00:59.622227Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 6500 XT", vendor: 4098, device: 29759, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "22.20.27.06", backend: Vulkan }
2022-12-04T08:01:00.581404Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    error matching FRAGMENT shader requirements against the pipeline
    shader global ResourceBinding { group: 0, binding: 6 } is not available in the layout pipeline layout
    storage class Storage { access: LOAD } doesn't match the shader Uniform

', C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:2403:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library\core\src\panicking.rs:64
   2: wgpu::backend::direct::default_error_handler
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:2403
   3: core::ops::function::Fn::call<void (*)(enum2$<wgpu::Error>),tuple$<enum2$<wgpu::Error> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:161
   4: alloc::boxed::impl$47::call<tuple$<enum2$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler<assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2032
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:2389
   6: wgpu::backend::direct::Context::handle_error<enum2$<wgpu_core::pipeline::CreateRenderPipelineError> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:254
   7: wgpu::backend::direct::impl$3::device_create_render_pipeline
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:1412
   8: wgpu::Device::create_render_pipeline
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\lib.rs:2194
   9: bevy_render::renderer::render_device::RenderDevice::create_render_pipeline
             at .\crates\bevy_render\src\renderer\render_device.rs:105
  10: bevy_render::render_resource::pipeline_cache::PipelineCache::process_render_pipeline
             at .\crates\bevy_render\src\render_resource\pipeline_cache.rs:577
  11: bevy_render::render_resource::pipeline_cache::PipelineCache::process_queue
             at .\crates\bevy_render\src\render_resource\pipeline_cache.rs:635
  12: bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system
             at .\crates\bevy_render\src\render_resource\pipeline_cache.rs:670
  13: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>),tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:337
  14: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache> >,void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>)
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:617
  15: bevy_ecs::system::function_system::impl$16::run::call_inner<tuple$<>,bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>,ref_mut$<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipelin
             at .\crates\bevy_ecs\src\system\function_system.rs:579
  16: bevy_ecs::system::function_system::impl$16::run<tuple$<>,void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>),bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCac
             at .\crates\bevy_ecs\src\system\function_system.rs:582
  17: bevy_ecs::system::function_system::impl$6::run_unsafe<tuple$<>,tuple$<>,tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache> >,tuple$<>,void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resou
             at .\crates\bevy_ecs\src\system\function_system.rs:409
  18: bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::closure$0
             at .\crates\bevy_ecs\src\schedule\executor_parallel.rs:218
  19: bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block$1
             at .\crates\bevy_ecs\src\schedule\executor_parallel.rs:223
  20: async_executor::impl$4::spawn::async_block$0<tuple$<>,enum2$<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block_env$1> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:139
  21: async_task::raw::RawTask<enum2$<async_executor::impl$4::spawn::async_block_env$0<tuple$<>,enum2$<bevy_ecs::schedule::executor_parallel::impl$2::prepare_systems::async_block_env$1> > >,tuple$<>,async_executor::impl$4::schedule::closure_env$0>::run<enum2$<a
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\raw.rs:511
  22: async_task::runnable::Runnable::run
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.3.0\src\runnable.rs:309
  23: async_executor::Executor::try_tick
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.5.0\src\lib.rs:176
  24: bevy_tasks::task_pool::impl$1::scope::closure$1<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >
             at .\crates\bevy_tasks\src\task_pool.rs:288
  25: std::panicking::try::do_call<bevy_tasks::task_pool::impl$1::scope::closure_env$1<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:483
  26: std::panicking::try::do_catch<bevy_tasks::task_pool::impl$1::scope::closure_env$1<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >,tuple$<> >
  27: std::panicking::try<tuple$<>,bevy_tasks::task_pool::impl$1::scope::closure_env$1<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:447
  28: std::panic::catch_unwind<bevy_tasks::task_pool::impl$1::scope::closure_env$1<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panic.rs:137
  29: bevy_tasks::task_pool::TaskPool::scope<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >
             at .\crates\bevy_tasks\src\task_pool.rs:287
  30: bevy_ecs::schedule::executor_parallel::impl$1::run_systems
             at .\crates\bevy_ecs\src\schedule\executor_parallel.rs:127
  31: bevy_ecs::schedule::stage::impl$3::run
             at .\crates\bevy_ecs\src\schedule\stage.rs:802
  32: bevy_render::impl$2::build::closure$2
             at .\crates\bevy_render\src\lib.rs:298
  33: alloc::boxed::impl$47::call<tuple$<ref_mut$<bevy_ecs::world::World>,ref_mut$<bevy_app::app::App> >,dyn$<core::ops::function::Fn<tuple$<ref_mut$<bevy_ecs::world::World>,ref_mut$<bevy_app::app::App> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2032
  34: bevy_app::app::App::update
             at .\crates\bevy_app\src\app.rs:154
  35: bevy_winit::winit_runner_with::closure$0
             at .\crates\bevy_winit\src\lib.rs:610
  36: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:254
  37: alloc::boxed::impl$46::call_mut<tuple$<enum2$<winit::event::Event<tuple$<> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<tuple$<> > >,ref_mut$<enum2$<winit::event_loop::ControlFlo
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2016
  38: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:250
  39: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\panic\unwind_safe.rs:271
  40: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:483
  41: winit::window::impl$58::eq
  42: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:447
  43: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panic.rs:137
  44: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:157
  45: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_event_handler<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:242
  46: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:344
  47: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::main_events_cleared<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:230
  48: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:755
  49: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:1055
  50: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:507
  51: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\panic\unwind_safe.rs:271
  52: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:483
  53: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
  54: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:447
  55: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panic.rs:137
  56: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:157
  57: winit::platform_impl::platform::event_loop::public_window_callback_inner<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:2248
  58: winit::platform_impl::platform::event_loop::public_window_callback<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:939
  59: GetPropW
  60: DispatchMessageW
  61: SystemParametersInfoW
  62: KiUserCallbackDispatcher
  63: NtUserDispatchMessage
  64: DispatchMessageW
  65: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_return<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:276
  66: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:239
  67: winit::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\event_loop.rs:278
  68: bevy_winit::run<bevy_winit::winit_runner_with::closure_env$0>
             at .\crates\bevy_winit\src\lib.rs:271
  69: bevy_winit::winit_runner_with
             at .\crates\bevy_winit\src\lib.rs:655
  70: bevy_winit::winit_runner
             at .\crates\bevy_winit\src\lib.rs:311
  71: core::ops::function::Fn::call<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:161
  72: alloc::boxed::impl$47::call<tuple$<bevy_app::app::App>,dyn$<core::ops::function::Fn<tuple$<bevy_app::app::App>,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2032
  73: bevy_app::app::App::run
             at .\crates\bevy_app\src\app.rs:168
  74: pbr::main
             at .\examples\3d\pbr.rs:6
  75: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', D:\Dev\Projects\bevy\crates\bevy_tasks\src\task_pool.rs:273:45
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library\core\src\panicking.rs:64
   2: core::panicking::panic
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3/library\core\src\panicking.rs:111
   3: enum2$<core::option::Option<tuple$<> > >::unwrap<tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\option.rs:778
   4: bevy_tasks::task_pool::impl$1::scope::async_block$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >
             at .\crates\bevy_tasks\src\task_pool.rs:273
   5: core::future::future::impl$1::poll<ref_mut$<enum2$<bevy_tasks::task_pool::impl$1::scope::async_block_env$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> > > > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\future\future.rs:124
   6: core::future::future::impl$0::poll<core::pin::Pin<ref_mut$<enum2$<bevy_tasks::task_pool::impl$1::scope::async_block_env$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> > > > > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\future\future.rs:112
   7: futures_lite::future::impl$4::poll<alloc::vec::Vec<tuple$<>,alloc::alloc::Global>,ref_mut$<core::pin::Pin<ref_mut$<enum2$<bevy_tasks::task_pool::impl$1::scope::async_block_env$0<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tup
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:194
   8: futures_lite::future::block_on::closure$0<enum2$<core::option::Option<alloc::vec::Vec<tuple$<>,alloc::alloc::Global> > >,futures_lite::future::PollOnce<ref_mut$<core::pin::Pin<ref_mut$<enum2$<bevy_tasks::task_pool::impl$1::scope::async_block_env$0<bevy_ec
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:89
   9: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum2$<core::option::Option<
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\thread\local.rs:446
  10: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<enum2$<core::option::Option<allo
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\thread\local.rs:422
  11: futures_lite::future::block_on<enum2$<core::option::Option<alloc::vec::Vec<tuple$<>,alloc::alloc::Global> > >,futures_lite::future::PollOnce<ref_mut$<core::pin::Pin<ref_mut$<enum2$<bevy_tasks::task_pool::impl$1::scope::async_block_env$0<bevy_ecs::schedule
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-lite-1.12.0\src\future.rs:79
  12: bevy_tasks::task_pool::TaskPool::scope<bevy_ecs::schedule::executor_parallel::impl$1::run_systems::closure_env$0,tuple$<> >
             at .\crates\bevy_tasks\src\task_pool.rs:283
  13: bevy_ecs::schedule::executor_parallel::impl$1::run_systems
             at .\crates\bevy_ecs\src\schedule\executor_parallel.rs:127
  14: bevy_ecs::schedule::stage::impl$3::run
             at .\crates\bevy_ecs\src\schedule\stage.rs:802
  15: bevy_render::impl$2::build::closure$2
             at .\crates\bevy_render\src\lib.rs:298
  16: alloc::boxed::impl$47::call<tuple$<ref_mut$<bevy_ecs::world::World>,ref_mut$<bevy_app::app::App> >,dyn$<core::ops::function::Fn<tuple$<ref_mut$<bevy_ecs::world::World>,ref_mut$<bevy_app::app::App> >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2032
  17: bevy_app::app::App::update
             at .\crates\bevy_app\src\app.rs:154
  18: bevy_winit::winit_runner_with::closure$0
             at .\crates\bevy_winit\src\lib.rs:610
  19: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:254
  20: alloc::boxed::impl$46::call_mut<tuple$<enum2$<winit::event::Event<tuple$<> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<tuple$<> > >,ref_mut$<enum2$<winit::event_loop::ControlFlo
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2016
  21: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:250
  22: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\panic\unwind_safe.rs:271
  23: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:483
  24: winit::window::impl$58::eq
  25: std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:447
  26: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panic.rs:137
  27: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:157
  28: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_event_handler<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:242
  29: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:344
  30: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::main_events_cleared<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:230
  31: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:755
  32: winit::platform_impl::platform::event_loop::public_window_callback_inner::closure$0<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:1055
  33: core::ops::function::FnOnce::call_once<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> >,tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:507
  34: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\panic\unwind_safe.rs:271
  35: std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:483
  36: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
  37: std::panicking::try<isize,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > > >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panicking.rs:447
  38: std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >,isize>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\std\src\panic.rs:137
  39: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,isize,winit::platform_impl::platform::event_loop::public_window_callback_inner::closure_env$0<tuple$<> > >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop\runner.rs:157
  40: winit::platform_impl::platform::event_loop::public_window_callback_inner<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:2248
  41: winit::platform_impl::platform::event_loop::public_window_callback<tuple$<> >
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:939
  42: GetPropW
  43: DispatchMessageW
  44: SystemParametersInfoW
  45: KiUserCallbackDispatcher
  46: NtUserDispatchMessage
  47: DispatchMessageW
  48: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_return<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:276
  49: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\platform_impl\windows\event_loop.rs:239
  50: winit::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner_with::closure_env$0>
             at C:\Users\tannh\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.27.5\src\event_loop.rs:278
  51: bevy_winit::run<bevy_winit::winit_runner_with::closure_env$0>
             at .\crates\bevy_winit\src\lib.rs:271
  52: bevy_winit::winit_runner_with
             at .\crates\bevy_winit\src\lib.rs:655
  53: bevy_winit::winit_runner
             at .\crates\bevy_winit\src\lib.rs:311
  54: core::ops::function::Fn::call<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:161
  55: alloc::boxed::impl$47::call<tuple$<bevy_app::app::App>,dyn$<core::ops::function::Fn<tuple$<bevy_app::app::App>,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\alloc\src\boxed.rs:2032
  56: bevy_app::app::App::run
             at .\crates\bevy_app\src\app.rs:168
  57: pbr::main
             at .\examples\3d\pbr.rs:6
  58: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/32e613bbaafee1bcabba48a2257b838f8d1c03d3\library\core\src\ops\function.rs:507
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\examples\pbr.exe` (exit code: 101)

Process finished with exit code 101
```

**Comment by floppyhammer** [comment]
Duplicate of #6841.
