### ISSUE TITLE
`wgsl` shaders without `@vertex`/`@fragment` entry point cause panic

### ISSUE THREAD

**Issue by Possseidon** [bevyengine/bevy#7022]
## Bevy version

[v0.9.1](https://github.com/bevyengine/bevy/tree/v0.9.1)

## What you did

Hot-Reloading of `wgsl` shaders, triggering the reload by saving with vscode (on Windows 10).

## What went wrong

When vscode saves to disk, bevy seems to randomly pick up an empty file first, which is technically valid `wgsl` file, but misses an entry point. This missing entry point causes a panic (see error and backtrace below).

I also tried saving the shader in Notepad++ instead, which causes the same issue but seemingly more often (after very limited testing).

Finally I also tried Windows Notepad (the old Window 10 version) for the fun of it, but to my surprise, this one seems to work fine no matter how much I save (yes, I modified the content inbetween each save). Now if only Windows Notepad was a decent editor 😛 

---

Is a panic considered as works-as-intended for this case in particular? I don't think so, but if it were, that would be a very unfortunate coincidence, considering that regular shader compilation errors do not panic and simply log the error and continue without the shader, making hot-reloading of shaders an absolute joy (as long as the empty-file issue doesn't occur).

<details>
<summary>

## The Error and Backtrace

</summary>

```
2022-12-24T13:06:08.385322Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (2)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `position_based_pbr_opaque_mesh_pipeline`
    error matching VERTEX shader requirements against the pipeline
    unable to find entry point 'vertex'

', D:\dev\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.14.2\src\backend\direct.rs:2403:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
   2: <&T as core::fmt::Debug>::fmt
   3: <wgpu::backend::direct::Context as wgpu::Context>::device_create_render_pipeline
   4: wgpu::Device::create_render_pipeline
   5: bevy_render::render_resource::pipeline_cache::PipelineCache::process_queue
   6: <bevy_ecs::system::function_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::run_unsafe
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: async_task::raw::RawTask<F,T,S>::run
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: std::thread::local::LocalKey<T>::with
  12: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', D:\dev\Rust\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.9.1\src\task_pool.rs:273:45   
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:115
   3: <&mut F as core::future::future::Future>::poll
   4: std::thread::local::LocalKey<T>::with
   5: bevy_tasks::task_pool::TaskPool::scope
   6: <bevy_ecs::schedule::executor_parallel::ParallelExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems
   7: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
   8: <bevy_render::texture::fallback_image::FallbackImage as bevy_ecs::world::FromWorld>::from_world
   9: bevy_app::app::App::update
  10: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  12: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::register_window
  13: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::move_state_to
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind
  16: winit::platform_impl::platform::event_loop::EventLoopThreadExecutor::execute_in_thread
  17: CallWindowProcW
  18: DispatchMessageW
  19: SendMessageTimeoutW
  20: KiUserCallbackDispatcher
  21: NtUserDispatchMessage
  22: DispatchMessageW
  23: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return
  24: winit::platform_impl::platform::event_loop::EventLoop<T>::run
  25: core::ptr::drop_in_place<hashbrown::map::HashMap<winit::window::WindowId,winit::window::Window>>
  26: <bevy_winit::WinitPlugin as bevy_app::plugin::Plugin>::build
  27: bevy_winit::winit_runner_with
  28: core::ops::function::Fn::call
  29: bevy_app::app::App::run
  30: wgpu_core::device::queue::PendingWrites<A>::dispose
```

</details>

**Comment by stefanmitic** [comment]
I did some testing and notify does send two Modify(Any) events. The only discernible difference seems to be that the file has a size of 0 at the moment of the first event and a valid size at the moment of the second event.
This is probably because of multiple Windows File API operations being done in succession like writing, setting attributes etc.
Since we don't get the type of Modify event being triggered there is no real way to know when the file is ready for ingestion except from reading the file size and checking that it's not 0.
This could be a quick fix for this problem.
If this is the rout we want to take I could try and implement this.

**Comment by mockersf** [comment]
A file size of 0 may be a valid case for some asset types, it can't just be ignored.

A proper fix would be to keep a queue of file events from notify, and only send one to Bevy events when there hasn't been a new one in a few milliseconds

**Comment by stefanmitic** [comment]
The only problem with that approach could be how to define a few milliseconds. Did some testing with Notepad++ and the time between events could be anywhere from 1.2ms for a few KB of data to 122ms for a 40+MB file. And that's on an SSD, HDDs are still in use and their write time could be significantly higher.
Maybe we could make the timeout configurable? That would allow the user to adapt it to their use case.

**Comment by mockersf** [comment]
Acceptable time to wait is very dependent on feeling, but around 500ms should be ok I think and cover most cases...

**Comment by Possseidon** [comment]
If we're just looking for workarounds rather than preventing the panic in wgpu:

What about simply treating empty wgsl files as an error up front, right before they get sent over to wgpu? Still log some kindof error (and maybe mention the whole file size 0 thing, to avoid others from reporting it because they think it's an actual error), but as long as it's not being sent over to wgpu we can avoid the panic.

**Comment by Possseidon** [comment]
A proper fix would also be nice though, as it might happen that you accidentally delete or comment out your entry point, which will still lead to a panic. While admittedly rare, it would be nicer to avoid the panic and handle it more like other errors (as in, just log the error and keep running).

**Comment by ruabmbua** [comment]
I think instantly reloading the shader asset if changed on disk is a bad idea in general. Many more possible states, that can mess with your program. E.g. even a simple logic problem in your shader might force you to restart, since the program is e.g. reusing a baked texture from the shader.

A much better alternative would be to only notify the program of changes on disk, and then let the game developer choose when to reload in game with a hotkey.

From API side I think we should provide events / status of changed asset state on disk, and a way to reload easily with one function call.

This behavior could be added without breaking backwards compatibility by adding a property `auto_apply_changes: bool` to AssetPlugin, which defaults to true.
