### ISSUE TITLE
Panic: add with overflow in exclusive function system

### ISSUE THREAD

**Issue by zheilbron** [bevyengine/bevy#7140]
## Bevy version
0.9.1

## What you did
I left the system running overnight.

## What went wrong
```
thread 'main' panicked at 'attempt to add with overflow', /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/system/exclusive_function_system.rs:106:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:115:5
   3: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Param,Marker,F> as bevy_ecs::system::system::System>::run
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/system/exclusive_function_system.rs:106:9
   4: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/schedule/stage.rs:782:29
   5: bevy_ecs::schedule::Schedule::run_once
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.9.1/src/schedule/mod.rs:370:13
   6: bevy_app::app::App::update
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.9.1/src/app.rs:152:9
   7: <bevy_app::schedule_runner::ScheduleRunnerPlugin as bevy_app::plugin::Plugin>::build::{{closure}}::{{closure}}
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.9.1/src/schedule_runner.rs:94:25
   8: <bevy_app::schedule_runner::ScheduleRunnerPlugin as bevy_app::plugin::Plugin>::build::{{closure}}
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.9.1/src/schedule_runner.rs:119:47
   9: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/boxed.rs:2001:9
  10: bevy_app::app::App::run
             at /Users/zheilbron/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_app-0.9.1/src/app.rs:168:9
  11: spiritbound_server::main
             at ./server/src/main.rs:21:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by alice-i-cecile** [comment]
https://github.com/bevyengine/bevy/blob/v0.9.1/crates/bevy_ecs/src/system/exclusive_function_system.rs#L106

The line responsible. @maniwani should we just be doing a wrapping addition here, or is there a more complex strategy required?

**Comment by maniwani** [comment]
> Should we just be doing a wrapping addition here, or is there a more complex strategy required?

Wow, apparently, we've had this bug all this time. Yes, it should be `wrapping_add` to match the `fetch_add` used by non-exclusive systems (wraps on overflow in both debug and release mode).

**Comment by Tirthnp** [comment]
Hi, I just added a PR for this. Let me know if I am missing anything, as it's my first time contributing :)
