### ISSUE TITLE
Postcard scene deserialization does not provide readable error for unregistered types.

### ISSUE THREAD

**Issue by Wcubed** [bevyengine/bevy#7337]
# What you did

I was creating the tests listed in https://github.com/bevyengine/bevy/pull/7336.
During the testing, I was missing one of the `.register_type()` calls, which made all 4 of the backends fail to deserialize. The error messages were clear, except the one for postcard, which was less helpful.

# What went wrong

The output for postcard is this:
```
Serde Deserialization Error
thread 'components::postcard_roundtrip_equality' panicked at 'Scene failed to deserialize: Serde Deserialization Error', tests/scenes/components.rs:61:37
stack backtrace:
```

Which is a lot less helpful than the output for ron, bincode, and messagepack:
```
no registration found for type `(i32, alloc::string::String, f32)`
thread 'components::bincode_roundtrip_equality' panicked at 'Scene failed to deserialize: no registration found for type `(i32, alloc::string::String, f32)`', tests/scenes/components.rs:94:37
stack backtrace:
```

I'd expect the output for "failing to deserialize because of a missing type registration" to be the same, regardless of the backend.

# Additional information
To reproduce, comment out one of the `.register_type` calls in `components.rs` from this pull request: https://github.com/bevyengine/bevy/pull/7336. All 4 backends will fail to deserialize, but postcard will have a criptic message.

**Comment by MrGVSV** [comment]
I could be wrong but I think this is an issue with postcard itself. I think it catches our errors and instead returns its own cryptic error 😅

**Comment by Wcubed** [comment]
Ah, that would be unfortunate 😅

**Comment by jamesmunns** [comment]
Hey, author of Postcard here.

I may in fact be eating your error. If you can make a repro case and open an issue on the postcard repo, I'd be happy to diagnose!

This might be related to:

* https://github.com/jamesmunns/postcard/issues/38
* https://github.com/jamesmunns/postcard/issues/80
* https://github.com/jamesmunns/postcard/pull/81
