### ISSUE TITLE
texture_binding_array example panics

### ISSUE THREAD

**Issue by rparrett** [bevyengine/bevy#7373]
## Bevy version

main

## Relevant system information

I am assuming this is metal and/or m1 specific, but I don't know for sure. 

```
AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
SystemInfo { os: "MacOS 13.1 ", kernel: "22.2.0", cpu: "Apple M1 Max", core_count: "10", memory: "64.0 GiB" }
```

## What you did

`cargo run --example texture_binding_array`
`cargo run --example texture_binding_array --release`

## What went wrong

```
2023-01-26T17:38:43.013800Z ERROR wgpu_hal::metal::device: Resource limit exceeded: StageInfo { stage: Fragment, counters: ResourceData { buffers: 8, textures: 20, samplers: 18 }, pc_buffer: None, pc_limit: 0, sizes_buffer: Some(7), sizes_count: 3, resources: {ResourceBinding { group: 0, binding: 0 }: BindTarget { buffer: Some(0), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 1 }: BindTarget { buffer: Some(1), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 2 }: BindTarget { buffer: None, texture: Some(0), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 3 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(0)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 4 }: BindTarget { buffer: None, texture: Some(1), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 5 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(1)), binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 6 }: BindTarget { buffer: Some(2), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 7 }: BindTarget { buffer: Some(3), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 8 }: BindTarget { buffer: Some(4), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 9 }: BindTarget { buffer: Some(5), texture: None, sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 10 }: BindTarget { buffer: None, texture: Some(2), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 0, binding: 11 }: BindTarget { buffer: None, texture: Some(3), sampler: None, binding_array_size: None, mutable: false }, ResourceBinding { group: 1, binding: 0 }: BindTarget { buffer: None, texture: Some(4), sampler: None, binding_array_size: Some(16), mutable: false }, ResourceBinding { group: 1, binding: 1 }: BindTarget { buffer: None, texture: None, sampler: Some(Resource(2)), binding_array_size: Some(16), mutable: false }, ResourceBinding { group: 2, binding: 0 }: BindTarget { buffer: Some(6), texture: None, sampler: None, binding_array_size: None, mutable: false }} }    
2023-01-26T17:38:43.013998Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (2)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_pipeline_layout
    not enough memory left

', /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.14.2/src/backend/direct.rs:2403:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/me/src/bevy/crates/bevy_tasks/src/task_pool.rs:354:49
thread 'Compute Task Pool (1)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/bevy_render/src/pipelined_rendering.rs:144:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/me/src/bevy/crates/bevy_tasks/src/task_pool.rs:354:49
```

**Comment by superdump** [comment]
The problem is that we're binding too many samplers. The example ends up using 18 where M1 GPUs only support 16. I'm first trying to understand if there is any reason to bind multiple samplers of the same type in a shader stage. If not then we should try to minimise the number of samplers we bind somehow.

**Comment by superdump** [comment]
Right, it seems like the example itself creates 16 samplers in the sampler binding array, and the view binding contains 2 comparison samplers for the shadow map textures. There only really needs to be 1 comparison sampler, and 1 sampler for the bindless material. @cryscan do you feel like changing the example to use 1 sampler as that is all that it needs?

**Comment by cryscan** [comment]
Agreed. Also I think it'll be helpful to add a note about the constraints in the example too.
