### ISSUE TITLE
Bevy should propagate system's panic payloads rather than creating additional panics

### ISSUE THREAD

**Issue by SludgePhD** [bevyengine/bevy#8152]
## What problem does this solve or what need does it fill?

I just got this unwieldy panic:

```
thread '<unnamed>' panicked at 'Error in Queue::submit: Buffer (2, 1, Vulkan) is still mapped', /home/sludge/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.1/src/backend/direct.rs:316:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: wgpu::backend::direct::Context::handle_error_fatal
   3: <T as wgpu::context::DynContext>::queue_submit
   4: wgpu::Queue::submit
   5: bevy_render::renderer::graph_runner::RenderGraphRunner::run
   6: bevy_render::renderer::render_system
   7: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
   8: async_task::raw::RawTask<F,T,S>::run
   9: bevy_tasks::thread_executor::ThreadExecutorTicker::tick::{{closure}}
  10: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
  11: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}
  12: std::thread::local::LocalKey<T>::with
  13: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
  14: <bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
  15: bevy_ecs::world::World::run_schedule_ref
  16: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
  17: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
  18: bevy_ecs::world::World::run_schedule_ref
  19: bevy_app::app::SubApp::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'Compute Task Pool (7)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /home/sludge/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.0/src/schedule/executor/multi_threaded.rs:194:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: async_task::raw::RawTask<F,T,S>::run
   4: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
   5: async_executor::Executor::run::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/sludge/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.0/src/task_pool.rs:376:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
   3: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}::{{closure}}
   4: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
   5: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
   8: <bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
   9: bevy_ecs::world::World::run_schedule_ref
  10: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
  11: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
  12: bevy_ecs::world::World::run_schedule_ref
  13: bevy_app::app::SubApp::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'Compute Task Pool (7)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/sludge/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.10.0/src/pipelined_rendering.rs:136:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
   3: async_task::raw::RawTask<F,T,S>::run
   4: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
   5: async_executor::Executor::run::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: std::thread::local::LocalKey<T>::with
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/sludge/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.0/src/task_pool.rs:376:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:111:5
   3: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}::{{closure}}
   4: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
   5: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}
   6: std::thread::local::LocalKey<T>::with
   7: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
   8: bevy_ecs::world::World::resource_scope
   9: bevy_app::app::App::update
  10: bevy_winit::winit_runner::{{closure}}
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
  12: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  13: winit::platform_impl::platform::x11::EventLoop<T>::run
  14: winit::platform_impl::platform::EventLoop<T>::run
  15: winit::event_loop::EventLoop<T>::run
  16: bevy_winit::run
  17: bevy_winit::winit_runner
  18: core::ops::function::Fn::call
  19: bevy_app::app::App::run
  20: sludgerender::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Only the very first panic is actually relevant, all the subsequent panics and their backtraces are noise ultimately caused by the first one.

## What solution would you like?

Ideally, bevy's executor should catch and propagate all panics originating from a system by using [`resume_unwind`](https://doc.rust-lang.org/stable/std/panic/fn.resume_unwind.html), all the way up to the user's `App::run` invocation.

This establishes a 1-to-1 relationship between panics caused by the user, and panics seen or caught by the user, which seems like a much cleaner design than what's happening now.

Doing this might require a rather large refactoring, so maybe treat this as more of a wishlist item :)

## What alternative(s) have you considered?

Embrace the Javaist backtraces and do nothing :coffee: 

## Additional context

Any other information you would like to add such as related previous work,
screenshots, benchmarks, etc.

**Comment by hymm** [comment]
Fixed in #8219
