### ISSUE TITLE
Not able to update WGPU settings in bevy render plugin

### ISSUE THREAD

**Issue by sybernatus** [bevyengine/bevy#8248]
## Bevy version

0.10.0

## \[Optional\] Relevant system information
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
Rust version : 1.67.1 

## What you did

I'm trying to load a 3D scene with .glb format. The texture of the scene is 20k.
I'm trying to load the scene via asset_server in a custom plugin 
```rust
pub struct MapPlugin;
impl Plugin for MapPlugin {
	fn build(&self, app: &mut App) {
		app
			.add_startup_system(spawn_gltf);
	}
}

fn spawn_glb(
	mut commands: Commands,
	ass: Res<AssetServer>,
) {
	let my_glb = ass.load("domain/maps/geometer_map.glb");
	commands.spawn(SceneBundle {
		scene: my_glb,
		transform: Transform::from_xyz(0.0, 0.0, 0.0),
		..Default::default()
	});
}
```
Then including the plugin to my app 
```rust
fn main() {

  App::new()
    .add_plugins(DefaultPlugins)
    .add_plugin(MapPlugin)
    .run();
}
```

## What went wrong

When I launch `cargo run --release`, the app is launched and the window is opened but empty. After few seconds, the app crashed with the following error.
```
2023-03-29T14:04:57.013377Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (6)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_texture
    Dimension X value 20000 exceeds the limit of 16384

', /home/ash/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.15.1/src/backend/direct.rs:3024:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (6)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /home/ash/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.10.0/src/schedule/executor/multi_threaded.rs:194:60
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/ash/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.0/src/task_pool.rs:376:49
thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/ash/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_render-0.10.0/src/pipelined_rendering.rs:136:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/ash/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_tasks-0.10.0/src/task_pool.rs:376:49
```

Then I tried to update wgpu settings as follow : 
```rust
fn main() {
  let mut options = WgpuSettings::default();
  options.limits.max_texture_dimension_1d = 30000;
  options.limits.max_texture_dimension_2d = 30000;
  options.limits.max_texture_dimension_3d = 30000;
  options.limits.max_compute_workgroup_storage_size = 30000;

  App::new()
    .add_plugins(DefaultPlugins
        .set(RenderPlugin {
          wgpu_settings: options
        })
    )
    .add_plugin(MapPlugin)
    .run();
}
```

And here is the issue, I still get the same error: 
```
Dimension X value 20000 exceeds the limit of 16384
```

The limit is still 16384, so that means that my value is not taken into account. 

I am probably doing wrong. 
Have you any idea, how I can increase this value? 

## Additional information

Other information that can be used to further reproduce or isolate the problem.
This commonly includes:

- I pasted the minimal code to reproduce the issue, but the complete example also include 3D Camera and other stuffs.

**Comment by mockersf** [comment]
`16384` is the limit reported by your GPU... You can reduce it, but you can't increase it.

**Comment by sybernatus** [comment]
Thanks for the quick answer @mockersf, closing the issue then.
