### ISSUE TITLE
ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    

### ISSUE THREAD

**Issue by diybl** [bevyengine/bevy#8320]
## Bevy version

version :0.10.0

system:windows10

run 3d project the error happend
2d have not the error

023-04-07T04:22:17.270797Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2023-04-07T04:22:18.066961Z  INFO bevy_render::renderer: AdapterInfo { name: "GeForce GTX 970M", vendor: 4318, device: 5080, device_type: DiscreteGpu, driver: "?", driver_info: "?", backend: Vulkan }
2023-04-07T04:22:19.354713Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Windows 10 Pro", kernel: "19043", cpu: "Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz", core_count: "4", memory: "24.0 GiB" }
2023-04-07T04:22:20.405987Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (3)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    parent device is lost

', C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:3024:5
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\std\src\panicking.rs:575
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library\core\src\panicking.rs:64
   2: wgpu::backend::direct::default_error_handler
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:3024
   3: core::ops::function::Fn::call<void (*)(enum2$<wgpu::Error>),tuple$<enum2$<wgpu::Error> > >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:79
   4: alloc::boxed::impl$47::call<tuple$<enum2$<wgpu::Error> >,dyn$<wgpu::UncapturedErrorHandler<assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\alloc\src\boxed.rs:2002
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:3010
   6: wgpu::backend::direct::Context::handle_error<enum2$<wgpu_core::pipeline::CreateRenderPipelineError> >
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:296
   7: wgpu::backend::direct::impl$7::device_create_render_pipeline
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\backend\direct.rs:1185
   8: wgpu::context::impl$5::device_create_render_pipeline<wgpu::backend::direct::Context>
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\context.rs:2191
   9: wgpu::Device::create_render_pipeline
             at C:\Users\jack\.cargo\registry\src\github.com-1ecc6299db9ec823\wgpu-0.15.1\src\lib.rs:2055
  10: bevy_render::renderer::render_device::RenderDevice::create_render_pipeline
             at .\crates\bevy_render\src\renderer\render_device.rs:105
  11: bevy_render::render_resource::pipeline_cache::PipelineCache::process_render_pipeline
             at .\crates\bevy_render\src\render_resource\pipeline_cache.rs:612
  12: bevy_render::render_resource::pipeline_cache::PipelineCache::process_queue
             at .\crates\bevy_render\src\render_resource\pipeline_cache.rs:683
  13: bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system
             at .\crates\bevy_render\src\render_resource\pipeline_cache.rs:718
  14: core::ops::function::FnMut::call_mut<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>),tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache> > >
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:166
  15: core::ops::function::impls::impl$3::call_mut<tuple$<bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache> >,void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>)
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\ops\function.rs:298
  16: bevy_ecs::system::function_system::impl$11::run::call_inner<tuple$<>,bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipeline_cache::PipelineCache>,ref_mut$<void (*)(bevy_ecs::change_detection::ResMut<bevy_render::render_resource::pipelin
             at .\crates\bevy_ecs\src\system\function_system.rs:629

**Comment by TotalKrill** [comment]
I have a suspicion this is related to some other open issues regarding shaders and changes from 0.9, to 0.10. Could you verify if this issue is there in 0.9? and if not maybe perform a git-bisect to find the issue? 

Basically my suspicion is that a lot of the added shader code between 0.9 and 0.10 is not very cross compatible.

**Comment by litttley** [comment]
i got the same error when i learn 3d of examples 

version: 0.10.1

system:windows10

error like this
```
     Running `target\debug\learn-01.exe`
2023-05-14T01:58:40.393122Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
2023-05-14T01:58:41.611108Z  INFO bevy_render::renderer: AdapterInfo { name: "GeForce GTX 1050", vendor: 4318, device: 7309, device_type: DiscreteGpu, driver: "", driver_info: "", backend: Vulkan }
2023-05-14T01:58:42.051056Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (0)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    parent device is lost
```

**Comment by Bigdusk** [comment]
解决了吗，我也出现了相同问题。
D:/rust/.cargo/bin/cargo.exe run --color=always --package rust-bevy --bin rust-bevy
    Finished dev [optimized + debuginfo] target(s) in 0.24s
     Running `target\debug\rust-bevy.exe`
2023-11-26T14:13:33.547886Z  INFO bevy_winit::system: Creating new window "App" (0v0)
2023-11-26T14:13:33.666817Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) Arc(TM) A730M Graphics", vendor: 32902, device: 22161, device_type: DiscreteGpu, driver: "Intel Corporation", driver_info: "Intel driver", backend: Vulkan }
2023-11-26T14:13:33.883373Z ERROR log: Handling wgpu errors as fatal by default    
thread 'Compute Task Pool (6)' panicked at D:\rust\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\wgpu-0.17.2\src\backend\direct.rs:3056:5:
wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `sprite_pipeline`
    Error matching ShaderStages(FRAGMENT) shader requirements against the pipeline
    Shader global ResourceBinding { group: 0, binding: 15 } is not available in the layout pipeline layout
    Binding is missing from the pipeline layout
