### ISSUE TITLE
App panics when entering fullscreen after startup

### ISSUE THREAD

**Issue by Ar4m1s** [bevyengine/bevy#9042]
## Bevy version
0.10.0.1

## Relevant system information
Using Xorg with dwm
Os: Arch
Kernel: 6.3.9-arch1-1
GPU: Quadro K2000M
Driver: Nvidia 470.182.03

AdapterInfo { name: "Quadro K2000M", vendor: 4318, device: 4091, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "470.182.03", backend: Vulkan }
SystemInfo { os: "Linux  Arch Linux", kernel: "6.3.9-arch1-1", cpu: "Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz", core_count: "4", memory: "23.4 GiB" }

## What I did

I entered fullscreen after the app started

## What went wrong

The program panicked. 

## Additional information

output:
thread 'main' panicked at 'Error in Surface::configure: parent device is lost', /home/vbm/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.15.1/src/backend/direct.rs:316:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'Compute Task Pool (2)' panicked at 'A system has panicked so the executor cannot continue.: RecvError', /home/vbm/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.10.1/src/schedule/executor/multi_threaded.rs:194:60
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/vbm/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49
thread 'Compute Task Pool (0)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/vbm/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_render-0.10.1/src/pipelined_rendering.rs:136:45
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/vbm/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.10.1/src/task_pool.rs:376:49

Example with wgpu worked as expected.
Example with winit worked as expected.
Both stable and nightly did not work.

Entering  fullscreen both using hotkey and bevy functionality results in panic. The following code was used to enter fullscreen with bevy functionality:

```
fn switch_window_mode(input: Res<Input<KeyCode>>, mut windows: Query<&mut Window>) {
    if input.just_pressed(KeyCode::F) {
        let mut window = windows.single_mut();

        window.mode = match window.mode {
            WindowMode::Fullscreen => WindowMode::Windowed,
            WindowMode::Windowed => WindowMode::Fullscreen,
            WindowMode::BorderlessFullscreen => WindowMode::Windowed,
            WindowMode::SizedFullscreen => WindowMode::Windowed,
        };
        info!("WINDOW_MODE: {:?}", window.mode);
    }
}
```
The app is able to run in fullscreen if it is on before the app starts which can be set with the following code:

```
  .add_plugins(DefaultPlugins.set(WindowPlugin {
            primary_window: Some(Window {
                mode: WindowMode::Fullscreen,
                ..default()
            }),
            ..default()
        }))

```

Even though I don't have a clue what is going wrong, it seems the problem is possible to fix as both winit and wgpu examples worked.
Please tell me if there is something I can do to improve the issue.

**Comment by VegardMatthey** [comment]
Still does not work in bevy 0.11 with the latest drivers.

**Comment by DDiekmann** [comment]
I couldn't reproduce this error with Ubuntu on an AMD Radeon RX 5600. Sadly no clue where the problem is.

**Comment by VegardMatthey** [comment]
I know this is almost certainly an issue spesific to Nvidia but I don't know if it works on other Nvidia driver versions.

**Comment by iwek7** [comment]
I also have issues with using fullscreen mode, my error message is slightly different tho:
spec:
nvidia driver 470.199.02  
Cinnamon 4.6.7
Linux Mint 20

Error:
```
2023-08-03T09:52:58.718918Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux 20 Linux Mint", kernel: "5.15.0-78-generic", cpu: "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz", core_count: "8", memory: "15.5 GiB" }
thread 'main' panicked at 'failed to set video mode', /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/window.rs:740:26
stack backtrace:
   0: begin_panic_handler
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:593:5
   1: panic_fmt
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panicking.rs:67:14
   2: panic_display<&str>
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panicking.rs:150:5
   3: panic_str
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panicking.rs:134:5
   4: expect_failed
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/option.rs:1952:5
   5: core::option::Option<T>::expect
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/option.rs:898:21
   6: winit::platform_impl::platform::x11::window::UnownedWindow::set_fullscreen_inner
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/window.rs:740:26
   7: winit::platform_impl::platform::x11::window::UnownedWindow::set_fullscreen
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/window.rs:765:32
   8: winit::platform_impl::platform::Window::set_fullscreen
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:479:50
   9: winit::window::Window::set_fullscreen
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/window.rs:927:9
  10: bevy_winit::system::changed_window
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/system.rs:164:34
  11: core::ops::function::FnMut::call_mut
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:166:5
  12: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:294:13
  13: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1) .> Out>>::run::call_inner
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/system/function_system.rs:622:21
  14: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1) .> Out>>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/system/function_system.rs:625:17
  15: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/system/function_system.rs:460:19
  16: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_system_task::{{closure}}::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/schedule/executor/multi_threaded.rs:505:26
  17: core::ops::function::FnOnce::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:250:5
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panic/unwind_safe.rs:271:9
  19: std::panicking::try::do_call
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:500:40
  20: std::panicking::try
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:464:19
  21: std::panic::catch_unwind
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panic.rs:142:14
  22: bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor::spawn_system_task::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/schedule/executor/multi_threaded.rs:500:23
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panic/unwind_safe.rs:296:9
  24: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  25: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panic/unwind_safe.rs:271:9
  26: std::panicking::try::do_call
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:500:40
  27: std::panicking::try
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:464:19
  28: std::panic::catch_unwind
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panic.rs:142:14
  29: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  30: async_executor::Executor::spawn::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.1/src/lib.rs:145:20
  31: async_task::raw::RawTask<F,T,S,M>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
  32: async_task::runnable::Runnable<M>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18
  33: async_executor::Executor::tick::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-executor-1.5.1/src/lib.rs:210:9
  34: bevy_tasks::thread_executor::ThreadExecutorTicker::tick::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/thread_executor.rs:105:39
  35: bevy_tasks::task_pool::TaskPool::execute_scope::{{closure}}::{{closure}}::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/task_pool.rs:503:45
  36: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panic/unwind_safe.rs:296:9
  37: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:42
  38: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panic/unwind_safe.rs:271:9
  39: std::panicking::try::do_call
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:500:40
  40: std::panicking::try
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:464:19
  41: std::panic::catch_unwind
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panic.rs:142:14
  42: <futures_lite::future::CatchUnwind<F> as core::future::future::Future>::poll
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:626:9
  43: bevy_tasks::task_pool::TaskPool::execute_scope::{{closure}}::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/task_pool.rs:506:77
  44: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:526:33
  45: bevy_tasks::task_pool::TaskPool::execute_scope::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/task_pool.rs:509:41
  46: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/task_pool.rs:420:85
  47: futures_lite::future::block_on::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:89:27
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/thread/local.rs:270:16
  49: std::thread::local::LocalKey<T>::with
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/thread/local.rs:246:9
  50: futures_lite::future::block_on
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-lite-1.13.0/src/future.rs:79:11
  51: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/task_pool.rs:374:13
  52: bevy_tasks::task_pool::TaskPool::scope_with_executor::{{closure}}
  53: std::thread::local::LocalKey<T>::try_with
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/thread/local.rs:270:16
  54: std::thread::local::LocalKey<T>::with
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/thread/local.rs:246:9
  55: bevy_tasks::task_pool::TaskPool::scope_with_executor
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_tasks-0.11.0/src/task_pool.rs:307:31
  56: <bevy_ecs::schedule::executor::multi_threaded::MultiThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/schedule/executor/multi_threaded.rs:190:9
  57: bevy_ecs::world::World::try_run_schedule::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1851:55
  58: bevy_ecs::world::World::try_schedule_scope
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1782:21
  59: bevy_ecs::world::World::try_run_schedule
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1851:9
  60: bevy_app::main_schedule::Main::run_main::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.0/src/main_schedule.rs:146:31
  61: bevy_ecs::world::World::resource_scope
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1344:22
  62: core::ops::function::FnMut::call_mut
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:166:5
  63: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:294:13
  64: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run::call_inner
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/system/exclusive_function_system.rs:203:21
  65: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/system/exclusive_function_system.rs:206:17
  66: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/system/exclusive_function_system.rs:103:19
  67: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/schedule/executor/single_threaded.rs:98:21
  68: core::ops::function::FnOnce::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:250:5
  69: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/panic/unwind_safe.rs:271:9
  70: std::panicking::try::do_call
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:500:40
  71: std::panicking::try
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panicking.rs:464:19
  72: std::panic::catch_unwind
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/std/src/panic.rs:142:14
  73: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/schedule/executor/single_threaded.rs:97:27
  74: bevy_ecs::world::World::run_schedule::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1865:51
  75: bevy_ecs::world::World::try_schedule_scope
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1782:21
  76: bevy_ecs::world::World::schedule_scope
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1836:9
  77: bevy_ecs::world::World::run_schedule
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.11.0/src/world/mod.rs:1865:9
  78: bevy_app::app::App::update
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.0/src/app.rs:244:24
  79: bevy_winit::winit_runner::{{closure}}
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/lib.rs:699:21
  80: winit::platform_impl::platform::sticky_exit_callback
  81: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/mod.rs:358:17
  82: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/mod.rs:443:31
  83: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/x11/mod.rs:498:25
  84: winit::platform_impl::platform::EventLoop<T>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:792:56
  85: winit::event_loop::EventLoop<T>::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/event_loop.rs:305:25
  86: bevy_winit::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/lib.rs:186:16
  87: bevy_winit::winit_runner
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.11.0/src/lib.rs:787:9
  88: core::ops::function::FnOnce::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:250:5
  89: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:250:5
  90: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/alloc/src/boxed.rs:1985:9
  91: bevy_app::app::App::run
             at /home/iwek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.11.0/src/app.rs:292:9
  92: SpaceJunkCollector::main
             at ./src/main.rs:32:5
  93: core::ops::function::FnOnce::call_once
             at /rustc/43062c43d2a63cf4e261c6eddc417575c4f3062f/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_winit::system::changed_window`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by VegardMatthey** [comment]
Which bevy

**Comment by VegardMatthey** [comment]
Which bevy are you using?

**Comment by VegardMatthey** [comment]
This confirms that there are issues when using the 470.xx Nvidia driver

**Comment by VegardMatthey** [comment]
Which version of Rust and Bevy are you using?

**Comment by iwek7** [comment]
Bevy: ebdf5063df5d2b89f4bf94b52eef03ad027fb8e3
rustc 1.72.0-nightly (43062c43d 2023-06-09)

**Comment by VegardMatthey** [comment]
As of version 0.12 the crash also happens when the window is configured to full screen in the window plugin. This means that I am not able to run bevy apps in full screen.

**Comment by unknownK19** [comment]
Similarly I got same problem
OS : POP!_OS 22.04 LTS
Graphics : Nvidia GT710 (version: 470.xx)
Processor: Intel Duo core E74000
Firstly, I try `cargo run ` on X11 (windows manager)
I got this problem
Then I try to switch wayland (windows manager)
It throw permission denied
So I tried 'sudo cargo run'
It run perfectly fine, it means Nvidia is Sūck at making driver, it work well on wayland.

I think this will never issue on next Cosmic DE update . Because Cosmic DE use wayland for more performance.

**Comment by VegardMatthey** [comment]
I tried with wayland. As far as I know the only supported compositor that supports this driver is mutter part of the gnome project. [source](https://wiki.archlinux.org/title/Wayland#Requirements). I have tested with other compositors to make sure, and the tty just froze and became unresponsive.

**Comment by Ar4m1s** [comment]
As of bevy 0.13 this problem has been resolved. However there still are issues when using this particular driver. If I repeatedly go in and out of fullscreen i will after a few tries get this error: ```thread 'Compute Task Pool (0)' panicked at /home/vbm/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.1/src/backend/wgpu_core.rs:724:18:
Error in Surface::configure: Validation Error

Caused by:
    Parent device is lost```
