### ISSUE TITLE
[Example] compute_shader_game_of_life crashes.

### ISSUE THREAD

**Issue by So1aric** [bevyengine/bevy#9670]
## Bevy version

0.11.2

## \[Optional\] Relevant system information
Rust: 1.70.0
OS: Arch Linux

```
AdapterInfo { name: "Mesa Intel(R) UHD Graphics 630 (CML GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Gl }
```

## What you did

```fish
cargo run --features wayland --features dynamic_linking --example compute_shader_game_of_life
```

## What went wrong

It crashed:
```
2023-09-02T13:14:00.305416Z ERROR wgpu_hal::gles::egl: GLES: [ShaderCompiler/Error] ID 1 : 0:9(1): error: image variables of format other than r32f, r32i or r32ui must be qualified `readonly' or `writeonly'
2023-09-02T13:14:00.306334Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (5)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_compute_pipeline
    Internal error: 0:9(1): error: image variables of format other than r32f, r32i or r32ui must be qualified `readonly' or `writeonly'


', /home/so1aric/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/wgpu-0.16.3/src/backend/direct.rs:3019:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (5)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/bevy_render/src/pipelined_rendering.rs:143:45
warning: queue 0x55e43da78ed0 destroyed while proxies still attached:
  xdg_wm_base@23 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```

**Comment by So1aric** [comment]
```
2023-09-02T13:22:43.389053Z  WARN bevy_pbr::ssao: ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
2023-09-02T13:22:44.395480Z ERROR wgpu_hal::gles::egl: GLES: [API/Error] ID 1 : GL_INVALID_ENUM in glTexStorage2DMultisample(target=GL_TEXTURE_2D)
2023-09-02T13:22:44.395642Z ERROR wgpu_hal::gles::egl: GLES: [API/Error] ID 1 : GL_INVALID_ENUM in glTexStorage2DMultisample(target=GL_TEXTURE_2D)
2023-09-02T13:22:44.623244Z ERROR wgpu::backend::direct: Shader translation error for stage ShaderStages(FRAGMENT): gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias
2023-09-02T13:22:44.623279Z ERROR wgpu::backend::direct: Please report it to https://github.com/gfx-rs/naga
2023-09-02T13:22:44.623307Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'Compute Task Pool (3)' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `pbr_opaque_mesh_pipeline`
    Internal error in ShaderStages(FRAGMENT) shader: gsamplerCubeArrayShadow isn't supported in textureGrad, textureLod or texture with bias

', /home/so1aric/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-2eab394af869c8a2/wgpu-0.16.3/src/backend/direct.rs:3019:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::render_resource::pipeline_cache::PipelineCache::process_pipeline_queue_system`!
thread 'Compute Task Pool (3)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', crates/bevy_render/src/pipelined_rendering.rs:143:45
warning: queue 0x55730ad944d0 destroyed while proxies still attached:
  xdg_wm_base@23 still attached
  wl_output@15 still attached
  wp_fractional_scale_manager_v1@14 still attached
  xdg_activation_v1@13 still attached
  zwp_text_input_manager_v3@12 still attached
  zwp_relative_pointer_manager_v1@11 still attached
  zwp_pointer_constraints_v1@10 still attached
  zxdg_decoration_manager_v1@9 still attached
  wl_seat@8 still attached
  wp_viewporter@7 still attached
  wl_subcompositor@6 still attached
  wl_compositor@5 still attached
  wl_shm@4 still attached
  wl_registry@2 still attached
```
Another example also crashes. I suspect it's my computer's fault😂

**Comment by CiderSlime** [comment]
Example works fine on my system. Got 1 error but program didn`t crash.
```
 ERROR sctk_adwaita::config: XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme    
2023-09-08T10:51:07.750294Z  INFO bevy_render::renderer: AdapterInfo { name: "Intel(R) UHD Graphics 770 (ADL-S GT1)", vendor: 32902, device: 18048, device_type: IntegratedGpu, driver: "Intel open-source Mesa driver", driver_info: "Mesa 23.0.4-0ubuntu1~22.04.1", backend: Vulkan }
```
