### ISSUE TITLE
Panic when using WindowMode::Fullscreen with examples/2d/pixel_perfect.rs

### ISSUE THREAD

**Issue by Retrodad0001** [bevyengine/bevy#9978]
## Bevy version

0.11.3

## \[Optional\] Relevant system information

If your bug is rendering-related, copy the adapter info that appears when you run Bevy.

GPU - AMD Radeon RX 5700 - Primary/Discrete
VRAM - 8176 MB - GDDR6 1750 MHz
Graphics - AMD Radeon RX 5700
Graphics Manufacturer - Powered by AMD
Usable Memory Size - 8176 MB
Core Clock - 1725 MHz
Total Memory Bandwidth - 448 GByte/s
Device ID - 731F
Revision ID - C4
Vendor ID - 1002
SubSystem ID - 04E4
SubSystem Vendor ID - 1043
Bus Type - PCI Express 4.0
Current Bus Settings - PCI Express 4.0 x16
Driver Version - 23.20.11.04-230921a-396203C-AMD-Software-Adrenalin-Edition
AMD Windows Driver Version - 31.0.22011.4008
Direct3D API Version - 12.1
Vulkan™ API Version - 1.3.262
OpenCL™ API Version - 2.0
OpenGL® API Version - 4.6
Direct3D® Driver Version - 9.14.10.01526
Vulkan™ Driver Version - 2.0.283
OpenCL® Driver Version - 31.0.22011.4008
OpenGL® Driver Version - 23.09.230729_569461f
2D Driver Version - 8.1.1.1634
UI Version - 2023.0921.2013.1996
AMD Audio Driver Version - 10.0.1.30
Driver Provider - Advanced Micro Devices, Inc.
Windows Edition - Windows 11 Professional (64 bit)
Windows Version - 22H2

the code of example with some small tweaks:

```
use bevy::prelude::*;
use bevy::render::RenderPlugin;
use bevy::render::settings::{Backends, WgpuSettings};
use bevy::window::WindowMode;

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::rgb(0.00, 0.00, 0.00)))
        .add_plugins(
            DefaultPlugins
                .set(RenderPlugin {
                    wgpu_settings: WgpuSettings {
                        //BUG: workaround repeating render errors in log https://github.com/gfx-rs/wgpu/issues/3959
                        backends: Some(Backends::VULKAN),
                        ..default()
                    },
                })
                .set(ImagePlugin::default_nearest())
                .set(WindowPlugin {
                    primary_window: Some(Window {
                        title: "Hold the line!".into(),
                        mode: WindowMode::Fullscreen,
                        ..default()
                    }),
                    ..default()
                }),
        )
        .add_systems(Startup, setup)
        .add_systems(Update, sprite_movement)
        .run();
}

#[derive(Component)]
enum Direction {
    Left,
    Right,
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());
    commands.spawn((
        SpriteBundle {
            texture: asset_server.load("pixel/bevy_pixel_light.png"),
            transform: Transform::from_xyz(100., 0., 0.),
            ..default()
        },
        Direction::Right,
    ));
}

fn sprite_movement(time: Res<Time>, mut sprite_position: Query<(&mut Direction, &mut Transform)>) {
    for (mut logo, mut transform) in &mut sprite_position {
        match *logo {
            Direction::Right => transform.translation.x += 30. * time.delta_seconds(),
            Direction::Left => transform.translation.x -= 30. * time.delta_seconds(),
        }

        if transform.translation.x > 200. {
            *logo = Direction::Left;
        } else if transform.translation.x < -200. {
            *logo = Direction::Right;
        }
    }
}

```

## What you did

1. run without WindowMode::Fullscreen  --> works!
2. run with WindowMode::Fullscreen  --> error/panic

## What went wrong

got this error:

   Parent device is lost
...........\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:734:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (8)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', .........cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\pipelined_rendering.rs:143:45
error: process didn't exit successfully: `target\debug\fullscreen_issue_project.exe` (exit code: 101)

or more detail: 

stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
   2: wgpu::backend::direct::Context::handle_error_fatal<enum2$<wgpu_core::present::ConfigureSurfaceError> >
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:308
   3: wgpu::backend::direct::impl$7::surface_configure
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\backend\direct.rs:734
   4: wgpu::context::impl$5::surface_configure<wgpu::backend::direct::Context>
             at ……...\xx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\context.rs:2056
   5: wgpu::Surface::configure
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-0.16.3\src\lib.rs:4150
   6: bevy_render::view::window::prepare_windows
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\view\window.rs:339
   7: core::ops::function::FnMut::call_mut
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:166
   8: core::ops::function::impls::impl$3::call_mut
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:294
   9: bevy_ecs::system::function_system::impl$29::run::call_inner
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\system\function_system.rs:622
  10: bevy_ecs::system::function_system::impl$29::run
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\system\function_system.rs:625
  11: bevy_ecs::system::function_system::impl$6::run_unsafe<void (*)(bevy_ecs::system::system_param::NonSend<bevy_render::view::window::NonSendMarker>,bevy_ecs::change_detection::ResMut<bevy_render::view::window::ExtractedWindows>,bevy_ecs::change_detection::Re
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\system\function_system.rs:460
  12: core::panic::unwind_safe::impl$26::poll
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:296
  13: futures_lite::future::impl$14::poll::closure$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  14: core::panic::unwind_safe::impl$23::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:271
  15: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:500
  16: std::panicking::try<enum2$<core::task::poll::Poll<tuple$<> > >,core::panic::unwind_safe::AssertUnwindSafe<futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_ecs::schedule::executor::multi_threaded::im
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:464
  17: futures_lite::future::impl$14::poll
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  18: async_executor::impl$5::spawn::async_block$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:152
  19: async_task::raw::RawTask<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core::panic::unwind
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.4.1\src\raw.rs:563
  20: async_task::runnable::Runnable<tuple$<> >::run
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.4.1\src\runnable.rs:784
  21: async_executor::impl$5::tick::async_fn$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:217
  22: bevy_tasks::thread_executor::impl$2::tick::async_fn$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\thread_executor.rs:105
  23: bevy_tasks::task_pool::impl$2::execute_global_scope::async_fn$0::async_block$0::async_block$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:482
  24: futures_lite::future::impl$12::poll
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:526
  25: async_executor::impl$5::run::async_fn$0::async_block$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:255
  26: async_executor::impl$19::with::impl$0::set::async_fn$0::closure$3
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:943
  27: futures_lite::future::impl$6::poll<tuple$<>,async_executor::impl$19::with::impl$0::set::async_fn$0::closure_env$3<enum2$<async_executor::impl$5::run::as
ync_fn$0::async_block_env$0<tuple$<>,enum2$<bevy_tasks::task_pool::impl$2::execute_glo                                                                       obal_scope::async_
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:246
  28: async_executor::impl$19::with::impl$0::set::async_fn$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:945
  29: async_executor::impl$5::run::async_fn$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:258
  30: core::panic::unwind_safe::impl$26::poll
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:296
  31: futures_lite::future::impl$14::poll::closure$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  32: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<tuple$<> > >,futures_lite::future::impl$14::poll::closure_env$0<core::panic::
unwind_safe::AssertUnwindSafe<enum2$<async_executor::impl$5::run::async_fn_env$0<tuple                                                                       e$<>,enum2$<bevy_t
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:271
  33: futures_lite::future::impl$14::poll
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
  34: bevy_tasks::task_pool::impl$2::execute_global_scope::async_fn$0::async_block$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:487
  35: futures_lite::future::impl$12::poll
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:526
  36: bevy_tasks::task_pool::impl$2::execute_global_scope::async_fn$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:491
  37: bevy_tasks::task_pool::impl$2::scope_with_executor_inner::async_block$0<bevy_render::pipelined_rendering::update_rendering::closure$0::closure_env$0,bevy_app::app::SubApp>
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:418
  38: futures_lite::future::block_on::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:89
  39: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:270
  40: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:246
  41: futures_lite::future::block_on<alloc::vec::Vec<bevy_app::app::SubApp,alloc::alloc::Global>,enum2$<bevy_tasks::task_pool::impl$2::scope_with_executor_inner::async_block_env$0<bevy_render::pipelined_rendering::update_rendering::closure$0::closure_env$0,bevy
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:79
  42: bevy_tasks::task_pool::TaskPool::scope_with_executor_inner
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:374
  43: bevy_tasks::task_pool::impl$2::scope_with_executor::closure$0
             at ……...\xxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:0
  44: std::thread::local::LocalKey<alloc::sync::Arc<bevy_tasks::thread_executor::ThreadExecutor> >::try_with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:270
  45: std::thread::local::LocalKey<alloc::sync::Arc<bevy_tasks::thread_executor::ThreadExecutor> >::with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:246
  46: bevy_tasks::task_pool::TaskPool::scope_with_executor<bevy_render::pipelined_rendering::update_rendering::closure$0::closure_env$0,bevy_app::app::SubApp>
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:307
  47: bevy_render::pipelined_rendering::update_rendering::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\pipelined_rendering.rs:139
  48: bevy_ecs::world::World::resource_scope
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_ecs-0.11.3\src\world\mod.rs:1344
  49: bevy_render::pipelined_rendering::update_rendering
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\pipelined_rendering.rs:136
  50: alloc::boxed::impl$49::call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\alloc\src\boxed.rs:2007
  51: bevy_app::app::SubApp::extract
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:165
  52: bevy_app::app::App::update
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:249
  53: bevy_winit::winit_runner::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_winit-0.11.3\src\lib.rs:707
  54: winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<tuple$<>,bevy_winit::winit_runner::closure_env$0>
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:260
  55: alloc::boxed::impl$48::call_mut
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\alloc\src\boxed.rs:2000
  56: winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:250
  57: core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:271
  58: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:500
  59: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:464
  60: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panic.rs:142
  61: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:157
  62: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:372
  63: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::main_events_cleared
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:230
  64: winit::platform_impl::platform::event_loop::flush_paint_messages
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:805
  65: winit::platform_impl::platform::event_loop::thread_event_target_callback::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:2370
  66: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
  67: core::panic::unwind_safe::impl$23::call_once<isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:271
  68: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:500
  69: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:464
  70: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panic.rs:142
  71: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,isize,winit::platform_impl::platform::event_loop::thread_event_target_callback::closure_env$0<tuple$<> > >
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop\runner.rs:157
  72: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple$<> >
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:2547
  73: DispatchMessageW
  74: DispatchMessageW
  75: GetClassLongW
  76: KiUserCallbackDispatcher
  77: NtUserDispatchMessage
  78: DispatchMessageW
  79: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_return<tuple$<>,bevy_winit::winit_runner::closure_env$0>
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:282
  80: winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,bevy_winit::winit_runner::closure_env$0>
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:245
  81: bevy_winit::winit_runner
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_winit-0.11.3\src\lib.rs:795
  82: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
  83: core::ops::function::FnOnce::call_once<void (*)(bevy_app::app::App),tuple$<bevy_app::app::App> >
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
  84: alloc::boxed::impl$47::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\alloc\src\boxed.rs:1993
  85: bevy_app::app::App::run
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_app-0.11.3\src\app.rs:292
  86: fullscreen_issue_project::main
             at .\src\main.rs:7
  87: core::ops::function::FnOnce::call_once
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_render::view::window::prepare_windows`!
thread 'Compute Task Pool (12)' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\pipelined_rendering.rs:143:45
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\result.rs:1651
   3: enum2$<core::result::Result<bevy_app::app::SubApp,async_channel::RecvError> >::unwrap
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\result.rs:1076
   4: bevy_render::pipelined_rendering::update_rendering::closure$0::closure$0::async_block$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_render-0.11.3\src\pipelined_rendering.rs:143
   5: core::panic::unwind_safe::impl$26::poll
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:296
   6: futures_lite::future::impl$14::poll::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
   7: core::panic::unwind_safe::impl$23::call_once<enum2$<core::task::poll::Poll<bevy_app::app::SubApp> >,futures_lite::future::impl$14::poll::closure_env$0<core::panic::unwind_safe::AssertUnwindSafe<enum2$<bevy_render::pipelined_rendering::update_rendering::cl
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\core\src\panic\unwind_safe.rs:272
   8: futures_lite::future::impl$14::poll
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:626
   9: async_executor::impl$5::spawn::async_block$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:152
  10: async_task::raw::RawTask<enum2$<async_executor::impl$5::spawn::async_block_env$0<enum2$<core::result::Result<bevy_app::app::SubApp,alloc::boxed::Box<dyn$<core::any::Any,core::marker::Send>,alloc::alloc::Global> > >,futures_lite::future::CatchUnwind<core::
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.4.1\src\raw.rs:563
  11: futures_lite::future::impl$12::poll
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:529
  12: async_executor::impl$5::run::async_fn$0::async_block$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:255
  13: async_executor::impl$19::with::impl$0::set::async_fn$0::closure$3
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:943
  14: futures_lite::future::impl$6::poll
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:246
  15: async_executor::impl$19::with::impl$0::set::async_fn$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:945
  16: async_executor::impl$5::run::async_fn$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0::async_block_env$0>,async_chan
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-executor-1.5.4\src\lib.rs:258
  17: futures_lite::future::block_on::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:89
  18: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:270
  19: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:246
  20: futures_lite::future::block_on<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,enum2$<async_executor::impl$5::run::async_fn_env$0<enum2$<core::result::Result<tuple$<>,async_channel::RecvError> >,futures_lite::future::Or<enum2$<bevy_tasks:
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:79
  21: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:171
  22: std::panicking::try::do_call
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:500
  23: std::panicking::try
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panicking.rs:464
  24: std::panic::catch_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\panic.rs:142
  25: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:165
  26: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:270
  27: std::thread::local::LocalKey<async_executor::LocalExecutor>::with
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3\library\std\src\thread\local.rs:246
  28: bevy_tasks::task_pool::impl$2::new_internal::closure$0::closure$0
             at ……...\xxxx\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy_tasks-0.11.3\src\task_pool.rs:158

**Comment by Elabajaba** [comment]
Does borderless instead of fullscreen work?

**Comment by Retrodad0001** [comment]
WindowMode::BorderlessFullscreen is working

**Comment by alice-i-cecile** [comment]
Hmm. Do any other examples crash in fullscreen? Ideally we can get it down to a truly minimal reproduction.

**Comment by Retrodad0001** [comment]
the same result when using the https://bevyengine.org/examples/2D%20Rendering/2d-gizmos/) 
works with WindowMode::BorderlessFullscreen ibut not with : WindowMode::Fullscreen --> error/panic

i used this one code file with bevy 0.11.3: (and the latest rust update and so on:

```
use std::f32::consts::PI;
use bevy::prelude::*;
use bevy::window::WindowMode;

fn main() {
    App::new()
        .insert_resource(ClearColor(Color::rgb(0.00, 0.00, 0.00)))
        .add_plugins(
            DefaultPlugins
                .set(WindowPlugin {
                    primary_window: Some(Window {
                        title: "Hold the line!".into(),
                        mode: WindowMode::Fullscreen,
                        ..default()
                    }),
                    ..default()
                }),
        )
        .add_systems(Startup, setup)
        .add_systems(Update, (system, update_config))
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn(Camera2dBundle::default());
    // text
    commands.spawn(TextBundle::from_section(
        "Hold 'Left' or 'Right' to change the line width",
        TextStyle {
            font: asset_server.load("fonts/FiraMono-Medium.ttf"),
            font_size: 24.,
            color: Color::WHITE,
        },
    ));
}

fn system(mut gizmos: Gizmos, time: Res<Time>) {
    let sin = time.elapsed_seconds().sin() * 50.;
    gizmos.line_2d(Vec2::Y * -sin, Vec2::splat(-80.), Color::RED);
    gizmos.ray_2d(Vec2::Y * sin, Vec2::splat(80.), Color::GREEN);

    // Triangle
    gizmos.linestrip_gradient_2d([
        (Vec2::Y * 300., Color::BLUE),
        (Vec2::new(-255., -155.), Color::RED),
        (Vec2::new(255., -155.), Color::GREEN),
        (Vec2::Y * 300., Color::BLUE),
    ]);

    gizmos.rect_2d(
        Vec2::ZERO,
        time.elapsed_seconds() / 3.,
        Vec2::splat(300.),
        Color::BLACK,
    );

    // The circles have 32 line-segments by default.
    gizmos.circle_2d(Vec2::ZERO, 120., Color::BLACK);
    // You may want to increase this for larger circles.
    gizmos.circle_2d(Vec2::ZERO, 300., Color::NAVY).segments(64);

    // Arcs default amount of segments is linerarly interpolated between
    // 1 and 32, using the arc length as scalar.
    gizmos.arc_2d(Vec2::ZERO, sin / 10., PI / 2., 350., Color::ORANGE_RED);
}

fn update_config(mut config: ResMut<GizmoConfig>, keyboard: Res<Input<KeyCode>>, time: Res<Time>) {
    if keyboard.pressed(KeyCode::Right) {
        config.line_width += 5. * time.delta_seconds();
    }
    if keyboard.pressed(KeyCode::Left) {
        config.line_width -= 5. * time.delta_seconds();
    }
}
```

**Comment by Elabajaba** [comment]
It looks like AMD drivers are now using DXGI flip mode for vulkan surfaces (instead of legacy flip. dxgi flip is much better, see https://devblogs.microsoft.com/directx/dxgi-flip-model/). The downside of this is that exclusive fullscreen isn't supported (and imo winit should automatically use a borderless window when fullscreen is requested for dxgi surfaces).

This was already an issue when using bevy with dx12.

You can check what presentmode is being used on windows with presentmon (for the new version with the overlay you have to add presentmode to the overlay).

**Comment by alice-i-cecile** [comment]
Can you please file an issue upstream for `winit` in that case?

**Comment by Elabajaba** [comment]
https://github.com/rust-windowing/winit/issues/3124

**Comment by Retrodad0001** [comment]
reusing bevy again and still this issue so i reopen it
